### ISSUE TITLE
Error when migrate from version 3.24.7 to latest

### ISSUE THREAD

**Issue by Spaceman2019** [xdan/jodit#1016]
**Jodit Version:**  4.0.0-beta.61

**Browser:**   Chrome/FF 
**OS:**  Windows
**Is React App:**  False

**Actual behavior:**
I switch from version 3.24.7 to 4.0.0-beta.61 and change only the import for css from **jodit/build/jodit.es2018.en.min.css** to **jodit/es2021.en/jodit.min.css**. When I start the app the browser show an external error and in the console I see:
ReferenceError: css is not defined
I check the problem for all folders, but it is the same.
![jodit-error](https://github.com/xdan/jodit/assets/53607207/3b7ac25b-82bc-48f1-a641-05ae5fd5b8aa)

**Comment by emololftw** [comment]
same here :/ temp works: 

```
import 'jodit/es2021/jodit.min.css'
import { Jodit } from 'jodit/es2021/jodit'
```

**Comment by xdan** [comment]
Hi, Is this being reproduced in the latest beta?

**Comment by lucky-zouzou** [comment]
Me too! ! 
I use the latest beta  in Vue3 Project, the same error occurs.

But  version 3.24.7  is OK!
