### ISSUE TITLE
Jodit Pro License "Need Valid Domain"

### ISSUE THREAD

**Issue by ChiKangMa** [xdan/jodit#1022]
Hi there,

I purchased Jodit pro for my organization. Getting this error when I tried to generate a license with our internally hostname, a short name.

Can you help us generating a license that can be applied to our hostname.

I will be very grateful if anyone can help us out.
![image](https://github.com/xdan/jodit/assets/11554652/8122f552-52d8-42ae-a40b-e4a7d3443655)

This hint shows as we don't setup the license in Jodit config.
![image](https://github.com/xdan/jodit/assets/11554652/62589bba-5e25-4569-81a6-1e80c03e69af)

**Comment by xdan** [comment]
Hi, is it your valid domain? http://short-name ? Or do you use it for local work?

**Comment by ChiKangMa** [comment]
Hi Valerie,

It’s a valid domain in our company’s network.
The actual domain name is http://imx-help

Please let me know how to get a pro license for that domain.

Thanks,
Kent

Valeriy ***@***.***>於 2023年10月21日 週六，22:13寫道：

**Comment by xdan** [comment]
Hello, we have decided to remove any validation in this service, you can add any domain you want.

**Comment by ChiKangMa** [comment]
Thank you for your support.

Valeriy ***@***.***>於 2023年10月23日 週一，15:57寫道：
