### ISSUE TITLE
Firefox specific execCommands no longer needed

### ISSUE THREAD

**Issue by johanneswilm** [xdan/jodit#1028]
Hey,
Firefox stopped requiring disabling controls five years ago [1]. So you are now able to remove your last usages of `document.execCommand` for things like "enableInlineTableEditing" or "enableObjectResizing".

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1490641

**Comment by xdan** [comment]
Yes, this was written 7 years ago) I will remove it
