### ISSUE TITLE
Issues with ESM

### ISSUE THREAD

**Issue by julianpoemp** [xdan/jodit#1029]
**Jodit Version:**  4.0.0-beta.89

**Browser:**  all
**OS:**  all
**Is React App:** False

**Code**: See https://github.com/julianpoemp/jodit-ts-import-bug/blob/main/src/app/app.component.ts . You can clone the repository and call npm start to run local web server.

**Expected behavior:**
Jodit Editor generated by ESM build should have the same functionality like that one from the other builds (e.g. es2021). For example if I set two buttons "bold" and "underline" I expect Jodit to show the buttons with icons.

**Actual behavior:**
![Bildschirmfoto 2023-10-16 um 11 16 49](https://github.com/xdan/jodit/assets/25926588/fe524f0d-aa0e-4162-a7bd-18c2d976783f)

For both editors the exact same configurations were set. As you can see there are three visible points missing:

1. Missing icons.
2. Missing status bar.
3. Missing placeholder.

**Comment by xdan** [comment]
Hello, thanks for the problem
1 This is an error
2.3 Since not all plugins are included in the esm build, you should enable all required plugins yourself https://github.com/xdan/jodit#esm-modules

**Comment by julianpoemp** [comment]
Hello @xdan,

thank you for your response. I was able to inject the "stat" and "placeholder" plugins so these features are working now. Only one further question: Do Angular/react users need to import autobind-decorator? I didn't import it to my example app and Jodit still works:

````Typescript
import {Component, OnInit} from '@angular/core';
import {Config} from 'jodit/esm/config';
import "jodit/esm/plugins/stat/stat.js"
import "jodit/esm/plugins/placeholder/placeholder.js"
import {Jodit} from 'jodit';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  ngOnInit(){
    Jodit.make('#editor', {
      width: 600,
      height: 400,
      buttons: ["bold", "underline"],
      textIcons: false
    } as Config);
  }
}
````

**Comment by xdan** [comment]
Because autobind-decorator is the only non-dev dependency and it comes with Jodit https://github.com/xdan/jodit/blob/main/package.json#L50

I've added "stat" and "placeholder" to the basic list so you don't have to include them yourself.

**Comment by julianpoemp** [comment]
Still issue with v4 beta 98. I debugged it and found out, that somehow the ESM JS files from affected plugins like "bold" or "underline" are not injected. For example "bold": a breakpoint here: https://github.com/xdan/jodit/blob/f9fd995ce1d1a4febf649acc4ed0c5a158a2933e/src/plugins/bold/bold.ts#L113 does not trigger. If I do the same with "font" (which icon is visible) the breakpoint triggers. So I think bold.js is not imported correctly.

Further more it seems that Jodit can't set the icon because the name is empty ("") in makeIcon from https://github.com/xdan/jodit/blob/f9fd995ce1d1a4febf649acc4ed0c5a158a2933e/src/core/ui/icon.ts#L79

For now I debugged the ESM build itself. Perhaps I find time to dive in this repository.

**Comment by julianpoemp** [comment]
the issue with missing icons for "bold" and "underline" still exists in beta 105. Perhaps there is a missing `"bold"` item in array here:

https://github.com/xdan/jodit/blob/73f06b6fd7888e8e9d7736e0a034a5311e247b15/tools/utils/resolve-alias-imports.ts#L59 

I would have tested it myself but I didn't get an environment running that allows me to test the newly built esm version.

**Comment by xdan** [comment]
Hi, yes, just add bold in your build

import "jodit/esm/plugins/bold/bold.js"

**Comment by julianpoemp** [comment]
Hi @xdan, it works, thank you!
