### ISSUE TITLE
The dotall flag used in this module causes an error in MSEdge and Firefox

### ISSUE THREAD

**Issue by Jongerr** [xdan/jodit#103]
**Jodit Version:**  3.2.14

jodit tries to create this regex `RegExp("<" + n + "[^>]+data-" + t + "[^>]+>(.+?)</" + n + ">", "igs")` but the "s" (dotAll) flag is not supported in MSEdge or Firefox, causing an RegExp syntax error and stopping edits from being made. Currently, this is stopping us from using the editor, as we can't afford to not support chrome. One possible workaround is to use `[^]` to match all characters, including new lines. Would it be possible to take the dotAll flag out or even add an option somewhere that could remove it?

**Comment by xdan** [comment]
Already fixed in 3.2.21
