### ISSUE TITLE
Need change domain when migrate from development to production environment

### ISSUE THREAD

**Issue by denny-zefanya** [xdan/jodit#1045]
I want to buy Jodit Pro License, but I read in documentation that license generate per domain. 

1.  After I buy license, can I change the domain after I registered?,  
2. Our web address  still use IP Address cause it use in intranet, can i use that ip address to generate license?

**Comment by xdan** [comment]
Hi, 
1. yes, you should remove license and create it again
2. Yes, we are not validate domain name
