### ISSUE TITLE
ESM typings for plugin options 

### ISSUE THREAD

**Issue by julianpoemp** [xdan/jodit#1049]
In Typescript using ESM from v4 beta we need to import each plugin separately, for example:

```typescript
import {Jodit} from "jodit";
import 'jodit/esm/plugins/add-new-line/add-new-line.js';
import 'jodit/esm/plugins/fullsize/fullsize.js';
import de from 'jodit/esm/langs/de.js';
import {Config} from 'jodit/types/config';

Jodit.lang.de = de;

const options: Partial<Config> = {};

const jodit = Jodit.make(...., options);
```

Because `Config` contains only core options without plugin options, is there a way to extend the type of options manually in a way an IDE suggests needed options for plugins (intellisense)?

I'm thinking of something like that:

```typescript

interface JoditAddNewLineOptions {
        /**
         * Create helper
         */
        addNewLine: boolean;
        /**
         * What kind of tags it will be impact
         */
        addNewLineTagsTriggers: HTMLTagNames[];
        /**
         * On dbl click on empty space of editor it add new P element
         * @example
         * ```js
         * Jodit.make('#editor', {
         *   addNewLineOnDBLClick: false // disable
         * })
         * ```
         */
        addNewLineOnDBLClick: boolean;
        /**
         * Absolute delta between cursor position and edge(top or bottom)
         * of element when show line
         */
        addNewLineDeltaShow: number;
}

// extending Config with options from the add new line plugin:
type JoditOptionsWithPlugins = Partial<Config> & JoditAddNewLineOptions;
// ....
// now the IDE suggests the attributes needed for add new line plugin
const options: JoditOptionsWithPlugins = {
  addNewLine: true
};
```

I know that typings for each plugin and its config exists, but I don't find a way to import it.

**Comment by xdan** [comment]
No, all plugin types are included. They do not need to be connected separately.

**Comment by ZimnitskiYury** [comment]
I have the same problem with all properties related to plugin's config. Looking for solution... ![image](https://github.com/xdan/jodit/assets/57269588/a674924a-5a26-4cce-9e16-5cf6040a42d7) 
![image](https://github.com/xdan/jodit/assets/57269588/e28179c9-ec89-4611-af6b-47bb7d1dc818)

**Comment by julianpoemp** [comment]
I re-open this issue because I still didn't find a solution to include the types for plugins in that way the IDE recognize it. The typings exist in the plugin folder but we are unable to use it.

**Comment by julianpoemp** [comment]
@ZimnitskiYury I just found out that importing from "jodit/config" works. Does it work for you, too?

```typescript
import "node_modules/jodit/esm/plugins/paste-from-word/paste-from-word";
import {Config} from "jodit/config";
```
types seem to be included even if you didn't import a plugin.

**Comment by ZimnitskiYury** [comment]
@julianpoemp if i change import to `import {Config} from "jodit/config"` i get errors for properties theme, readonly and etc. 
![image](https://github.com/xdan/jodit/assets/57269588/39b61d44-f3e7-43e9-9272-82d2273de8d3)

**Comment by julianpoemp** [comment]
@ZimnitskiYury that's only a workaround, I don't know a better solution:

```typescript
import * as JoditESMConfig from 'jodit/config';
import * as JoditConfig from 'jodit/types/config';

const config: JoditConfig.Config & JoditESMConfig.Config = {
    readonly: true
}
```

I don't really understand why a lot of attributes are required in the types but not in the JS code examples in the docs. That's why I prefer using:

```typescript
const config: Partial<JoditConfig.Config & JoditESMConfig.Config> = {
    readonly: true
}
```
