### ISSUE TITLE
Access editors

### ISSUE THREAD

**Issue by ghianciulu** [xdan/jodit#105]
Hello. Sorry but there is nothing on stackoverflow.
Question. I have three editors on the page. How do I access the editors, to edit the text, out of the function that created them? Thank you

**Comment by xdan** [comment]
Hi, English please
```html
<textarea id="someEditorId"></textarea>
```
```javascript
var editor = new Jodit('#someEditorId');
editor.value = 'test'
```
In another place
```javascript
var editor = Jodit.instances.someEditorId
editor.value = 'another text'
```
