### ISSUE TITLE
TypeScript Error in props Config.

### ISSUE THREAD

**Issue by MustafaAgami** [xdan/jodit#1052]
I am getting an issue when i am using Jodit with typescript version.
It says types are not defined in for config props which i am passing in it.
**Jodit Version:**  1.3.39
**Source:** https://www.npmjs.com/package/jodit-react

**Browser:**  Chrome
**OS:**  Linux
**Is React App:**  True

**Code**
**Inside Component**
```
const editor = useRef(null);
  const [content, setContent] = useState('');

  const config={
    "placeholder":"start typing....",
    "showCharsCounter": false,
    "showWordsCounter": false,
    "showXPathInStatusbar": false
  }
```
**Inside Return Statement**

`<JoditEditor ref={editor} value={content} onBlur={newContent=>setContent(newContent)} config={config}/>`

**Error ScreenShot**
![image](https://github.com/xdan/jodit/assets/126065957/2050aae4-6589-40f4-a83d-4f2507a66e8f)

**Comment by xdan** [comment]
Try now plz

**Comment by arthur-overlord** [comment]
Hello. Sorry to ask here, but I got the same error on version `"jodit-react": "^4.1.2"`.

<img width="1021" alt="Capture d’écran 2024-09-10 à 23 04 38" src="https://github.com/user-attachments/assets/f5d8a1b7-0b16-460e-99d3-c5a3ec022fbc">

How can I fix it ?

Thank you
