### ISSUE TITLE
issues with text-alignment button on Playground & ESM

### ISSUE THREAD

**Issue by julianpoemp** [xdan/jodit#1074]
**Jodit Version:**  v.4.0.6

**Browser:**  Firefox, Chrome
**OS:**  MacOS
**Is React App:**  False

```
{
    maxHeight: 300,
    buttons: ["left"],
    statusbar: false,
    placeholder: 'Please write a message in German or English...',
}
```

```
import 'jodit/esm/plugins/justify/justify.js';
```
was included before calling `Jodit.make()`. I can't provide a full ESM example because the `justify` plugin is imported to an Angular app that uses the ngx-jodit package that initializes using Jodit.make(). You can find the Jodit.make() call [here](https://github.com/julianpoemp/ngx-jodit/blob/main/libs/ngx-jodit/src/lib/ngx-jodit.component.ts).

**Expected behavior:**

Should show the text-alignment button as dropdown button, not simple button.

**Actual behavior:**

- Toggling "left" on/off on [Playground](https://xdsoft.net/jodit/play.html) example removes dropdown for text-alignment. Also if you toggle any other button.
![Bildschirmfoto 2024-02-02 um 15 01 28](https://github.com/xdan/jodit/assets/25926588/c6e8be1c-e1ab-40e0-b14f-fc4e981ea4dd)
![Bildschirmfoto 2024-02-02 um 15 02 02](https://github.com/xdan/jodit/assets/25926588/8140ce21-6f48-413e-b88e-73f0e8b81e26)

- ESM version should should show text-alignment button correctly.

**Comment by CorentinFortes** [comment]
up

**Comment by julianpoemp** [comment]
@CorentinFortes I tried the latest version of Jodit, it works now. Instead of "left" use "align" in the buttons array.

**Comment by CorentinFortes** [comment]
Hello,

sorry i just have seen your message, thank you verry much for your help i will try this ASAP : )
