### ISSUE TITLE
Right-hand side of instanceof is not an object

### ISSUE THREAD

**Issue by jcelletti** [xdan/jodit#108]
See issue #100
this just seemed to move the issue to another place in the code
tried on version 3.2.26

new screenshot
![jodit_typeerror](https://user-images.githubusercontent.com/8338831/49455059-56059c80-f79b-11e8-9fcd-43a1ce1ea67c.png)

**Comment by xdan** [comment]
Hi, how i can repeat this bug?

**Comment by jcelletti** [comment]
it looks like our code blocked the proper dispose of the editor.
the repro was switching between pages on a single page app (without disposing) and trying to open the alignment modal.

with proper disposing this is no longer an issue
