### ISSUE TITLE
Jodit not hiding the raw textarea

### ISSUE THREAD

**Issue by bardolf69** [xdan/jodit#1086]
**Jodit Version:**  4.0.6

**Browser:**  Chrome, Edge, and FF
**OS:**  Windows
**Is React App:**  False

**Code**

```js
<template>
  <div ref="jodit">
    <slot />
  </div>
</template>

<script>
export default {
    props: {
        options: {
            type: Object,
            required: false,
            default() {
                return {};
            },
        },

        jsOptions: {
            type: Object,
            required: false,
            default: () => {
                return {};
            }
        },

        modelValue: {
            type: [String, Number],
            required: false
        },

        dusk: {
            type: String,
            required: false,
            default: null,
        },
    },

    emits: ["update:modelValue"],

    data() {
        return {
            instance: null,
        };
    },

    mounted() {
        const textareaElement = this.$refs.jodit.querySelector("textarea");

        import("jodit").then((Jodit) => {
            const options = Object.assign({ defaultMode: Jodit.default.Jodit.MODE_WYSIWYG }, this.options, this.jsOptions);

            this.instance = Jodit.default.Jodit.make(textareaElement, options);
            this.instance.value = this.modelValue;
            this.instance.events.on("change", newValue => this.$emit("update:modelValue", newValue));

            if(this.dusk) {
                this.instance.editor.setAttribute("dusk", this.dusk);
            }
        });
    },

    beforeUnmount () {
        this.instance.destruct();
    }
};
</script>
```

**Expected behavior:**
Shows the Jodit editor and hides the textarea that holds the raw data.

**Actual behavior:**
Shows both the Jodit editor and the textarea.  Appears to be caused by blocking of 3rd party cookies when accessing CDN copies of ace.js, beautify,min.js, theme-idle_fingers.js, beautify-html.min.js

![image](https://github.com/xdan/jodit/assets/47841636/baf0dfcc-d820-45c2-b491-cacf6994ee5e)

**Comment by bardolf69** [comment]
I have also tested with v3.24.9 of Jodit and get the same result.

https://developers.google.com/privacy-sandbox/3pcd#report-issues

**Comment by bardolf69** [comment]
Just to add information in the hope some one will look at it.  The cookies being blocked are
```
_ga_8BK794H3J9	.cloudflare.com/
_ga_SQCRB0TXZW	.cloudflare.com/
_ga	.cloudflare.com/
_ga_PHVG60J2FD	.cloudflare.com/
```
and these cookies are required to process the following requests
```
beautify.min.js
ace.js
beautify-html.min.js
theme-idle_fingers.js
mode-html.js
```
all of which are jodit related requests I beleive.  This will be hard to replicate as this new CHIPS requirment is only being gradually rolled out.  Apparently I'm just in the lucky 1% who got it first.  Basically cookies that previously used ```SameSite: None``` now need to be upgraded to ```SameSite=None; Partitioned;```

**Comment by bardolf69** [comment]
No suggestions?

**Comment by xdan** [comment]
We will check it, but now you can disable beautify and ace
```js
Jodit.make('#editor', {
    beautifyHTML: false,
    sourceEditor: 'area'
});
```

**Comment by bardolf69** [comment]
ok, that has removed the warnings but still hasn't solved the issue that brought me here in the first place, which is that it is still showing the text area below the Jodit window.

**Comment by bardolf69** [comment]
@xdan any update on this as it screws with the css of everything on the page when that text area doesn't get hidden.
