### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by BZPJoe** [xdan/jodit#1098]
Is this maintained anymore? I purchased license but the license system doesn't seem to be working and no one is responding through their email or support system.

**Comment by hutber** [comment]
I am also having the same issue after paying $800

**Comment by BZPJoe** [comment]
> I am also having the same issue after paying $800

So even the OEM version calls to a license server? Ugh.

**Comment by xdan** [comment]
@hutber Hello, please describe your problem?
If you have a problem with the OEM license, you can write to me directly by email chupurnov@gmail.com

**Comment by hutber** [comment]
> @hutber Hello, please describe your problem? If you have a problem with the OEM license, you can write to me directly by email [chupurnov@gmail.com](mailto:chupurnov@gmail.com)

Thanks for replying!! It started to work a few hours after this, so not sure what was going on, but its all good now. Sorry I had forgotten I posted this at all!

**Comment by xdan** [comment]
@BZPJoe Hello, could you tell me what your problem is?
If you have a problem with the OEM license, you can write to me directly by email [chupurnov@gmail.com](mailto:chupurnov@gmail.com)

**Comment by BZPJoe** [comment]
> @BZPJoe Hello, could you tell me what your problem is? If you have a problem with the OEM license, you can write to me directly by email [chupurnov@gmail.com](mailto:chupurnov@gmail.com)

I was using the files out of the build folder. it was calling a license server. I changed the files used to the root folder of the download and it seems to be fine for now. Sorry about that.

**Comment by hutber** [comment]
@BZPJoe I wrote an email about the OEM license, we need an answer to the export PDF issue we are having and how to get it working as there is no documentation on it. My company will not buy the OEM license without having it working first.
