### ISSUE TITLE
Incorrect controls position inside a relatively positioned div

### ISSUE THREAD

**Issue by poohitan** [xdan/jodit#11]
Hi there, at first I want to thank you for this great editor.

I have a small problem which I'm sure can be fixed with some editor options.
My editor is placed in a div with `position: relative`. It makes all the editor absolutely-positioned elements (like image or link controls) appear on incorrect places (shifted somewhere to the right and bottom). When I remove `position: relative` from parent div, they are positioned well. 

Is it possible to set the element which all calculations are relative to? I suppose currently it's `<body>`.
Or maybe you can just make all the positions calc relatively to the first parent with `position: relative` or `position: absolute` instead of `<body>`?

**Jodit Version:**  3.0.34

**Expected behavior:**
All editor controls are positioned correctly regardless parent blocks CSS positions.

**Actual behavior:**
All editor controls are positioned incorrectly when editor is placed inside a div with `position: relative`.

**Comment by poohitan** [comment]
Sorry, seems like it's already fixed in 3.1.3.

It's a bit confusing that on [releases page](https://github.com/xdan/jodit/releases) 3.0.34 is marked as the latest release, while it's not.

**Comment by xdan** [comment]
Can i close this issue?

**Comment by poohitan** [comment]
Yep, sure.
