### ISSUE TITLE
Config.ts

### ISSUE THREAD

**Issue by mykle90** [xdan/jodit#112]
**Jodit Version:**  3.2.27

Including Jodit in my code breaks the build for react-scripts-ts, but it seems like the issue is spesific to this build-system. The error im reciving are: `(792,36): Property 'iframe' does not exist on type 'Config'.` in file `Config.ts`

Digging into the where this type exsits I can not find any iframe object. The error is also displayed in Visual Studio Code using TypeScript 3.2.2

I am using a react-wrapper for this library, but im geting the problem using that or not.

**Code**

```ts
Build problem, so no actual code
```

**Expected behavior:**
The code should build

**Actual behavior:**
The build fails to buildproduction build.

**Comment by xdan** [comment]
Try in latest version - must be fixed
