### ISSUE TITLE
Customizing font size and font family buttons to display selected size and font family

### ISSUE THREAD

**Issue by kozlyakovskaya-tatsiana** [xdan/jodit#1121]
How to customize font size and font family buttons to display selected size and font family as it implemented in demo for pro version?
Or is it available only in Pro mode?
Instead of 
![image](https://github.com/xdan/jodit/assets/55045206/512ead1d-a13f-46b4-8c3b-da4da5b6de53)

I'd like to display
![image](https://github.com/xdan/jodit/assets/55045206/c2698a10-4bc5-48cf-be4c-f878fc2917d6)

**Comment by xdan** [comment]
Hi, it just component option:

```js
Jodit.make('#editor', {
        controls: {
             font: {
                component: 'select'			
            }
      }
});
```

**Comment by kozlyakovskaya-tatsiana** [comment]
It works!)
Thanks you so much for bringing your attention to that.

**Comment by kozlyakovskaya-tatsiana** [comment]
Closed
