### ISSUE TITLE
None

### ISSUE THREAD

**Issue by cathino** [xdan/jodit#1125]
I don't think it's a good practice to close an issue directly without resolving it.
﻿
I also believe that deleting comments directly without addressing the issue is not a good approach.

**Comment by newproplus** [comment]
I tried using **parcel** instead of **vite**, there are different errors:
![截图 2024-04-29 07-39-52](https://github.com/xdan/jodit/assets/92970070/c7476a7a-bd94-4553-bee4-ff13138e78a3)

**Comment by newproplus** [comment]
It works well with [rspack](https://www.rspack.dev/), using the rsbuild's default conf:

```
 "scripts": {
    "dev": "NODE_ENV=development rspack serve",
    "build": "NODE_ENV=production rspack build",
  },
```

**Comment by newproplus** [comment]
It works well using ts + rspack + react , I created a demo [jodit_rspack_demo](https://github.com/newproplus/jodit_rspack_demo)

**Comment by xdan** [comment]
Can we close it?

**Comment by newproplus** [comment]
@xdan But the problem has not been solved. It is best that all apps compiled by various packaging tools can be used normally, rather than only apps compiled by rspack not reporting errors.

**Comment by xdan** [comment]
> @xdan But the problem has not been solved. It is best that all apps compiled by various packaging tools can be used normally, rather than only apps compiled by rspack not reporting errors.

No, have you tried the latest version? Should this be resolved?

**Comment by rshekhtm** [comment]
I had the same (or similar) issue with v4.2.10 and vite where the bundles threw this error (albeit not on the same line, but one of its neighbors). After upgrading to 4.2.19 the issue went away.

**Comment by newproplus** [comment]
I'm writing a new WYSIWYG editor, it's called **Exsied**: **Ex**tremely **si**mple **ed**itor. 

It's quite simple, easy to develop and debug. It might be published in a few weeks, the repo is https://github.com/exsied/exsied.

## Features:

- No complex concepts, **exsied** is written entirely in native JavaScript events binding.

- No dependencies.

- Easy to configure / custom / develop.

- All functions are based on plugins.

- Only use **ts** and **scss**, and all icons are svg files.

- The file size after build is very small, just 34kb after gzip.
