### ISSUE TITLE
Table inline popup buttons issue

### ISSUE THREAD

**Issue by MyMonsterVR** [xdan/jodit#1129]
**Jodit Version:**  3.4.5 (PRO (happens in the free version too on your website))

**Browser:** Chromium
**OS:** Windows
**Is React App:** False

**Expected behavior:**
Buttons delete, create new row and create new column

**Actual behavior:**
Bottom 3 buttons in the inline popup (when u click on a table) to the left triggers a warning, I assume its due to the buttons not having any args since it just returns FALSE in the beforeCommand, this is due to the buttons text being "" instead of "tablebin" or similar behaviour.

Specific browser error is "Uncaught TypeError: e.toLowerCase is not a function" because e which looks to be the control is empty and therefore toLowerCase() returns it as false from what I have observed.

**Comment by cezarypiatek** [comment]
Seems to be still broken in v4.2.27
