### ISSUE TITLE
Toolbar Customization Issue When Selecting Text Inside Table Cells

### ISSUE THREAD

**Issue by ZimnitskiYury** [xdan/jodit#1131]
When text is selected within a table cell, the toolbarInlineForSelection: true setting fails to trigger the inline toolbar specific to the text selection. Instead, the toolbar that appears is the one customized for the entire cell.

**Jodit Version:**  4

**Browser:** All
**OS:** All
**Is React App:** True

**Code**

```html
<table>
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
</table>
```

Steps to Reproduce:

 1. Create an HTML table with multiple rows and columns.
 2. Insert some text into one of the table cells.
 3. Select the text inside the table cell.
 4. Observe the behavior of the toolbar.
 
**Expected Behavior:** When text is selected inside a table cell, the toolbar should appear with customization options specifically for the selected text within the cell.

**Actual Behavior:** Currently, the toolbar appears with customization options for the entire table cell, rather than just the selected text.

**Comment by PoliteIan** [comment]
@xdan Any progress on this one?

**Comment by PoliteIan** [comment]
Any update?
