### ISSUE TITLE
Unable to use Speech Recognition

### ISSUE THREAD

**Issue by snake-jhon** [xdan/jodit#1139]
**Jodit Version:**  4.1.2

**Browser:** Chrome
**OS:** Windows
**Is React App:** True
**Reproduced on xdsoft.net:** True

When I Press speech recognition button it start recording but in the console it started showing this error "Uncaught DOMException: Failed to execute 'start' on 'SpeechRecognition': recognition has already started."

**Expected behavior:**
I should record the voice and write in the editor.
**Actual behavior:**
I start recording and write a few words a stop with error.

![image](https://github.com/xdan/jodit/assets/79166501/594b3d43-2f35-452a-9478-8a91df9af48d)

**Comment by xdan** [comment]
Hi, it's chromium's bug https://github.com/MikeyParton/react-speech-kit/issues/23#issuecomment-622164389

**Comment by Rehmanali-A** [comment]
Its still have the same issue on version 4.1.2
