### ISSUE TITLE
little jquery bug on example pages

### ISSUE THREAD

**Issue by bjornweb** [xdan/jodit#114]
I've searched for other (better) ways to contact you.
On several Jodit pages I see the following jQuery example:

```
$('textarea').each(function (elm) {
    var editor = new Jodit(elm);
    editor.value = '<p>start</p>';
});
```

The jQuery each() callback function has an index and the object. Your jQuery example passes the index to Jodit() which results in an error.
It should be:

```
$('textarea').each(function (i,elm) {
    var editor = new Jodit(elm);
    editor.value = '<p>start</p>';
});
```

First time Jodit user, love it! Up and running in minuts, Thanks!

**Comment by xdan** [comment]
Thank you! Fixed

**Comment by bjornweb** [comment]
https://xdsoft.net/jodit/doc/ still needs an update.
