### ISSUE TITLE
Menu Item Popups Hidden when Jodit is inside an <dialog> element

### ISSUE THREAD

**Issue by bobgager** [xdan/jodit#1146]
**Jodit Version:**  4.xxxxx

**Browser:** All
**OS:** Mac (not tested on Windows)
**Is React App:** False

When the Jodit Editor is placed inside an html <dialog> element, the various menu item popups (Like font size or font, or whatever) all open up BEHIND the <dialog>
Tried various itterations of setting z-index and nothing worked.

**Expected behavior:**
Menu button popups should open on TOP of the Jodit Editor even when in a <dialog>

**Actual behavior:**
Menu button popups are opening behind the <dialog> element

**Comment by JClackett** [comment]
Also have his using radix dialogs

**Comment by fabian-mcfly** [comment]
I haven't tested it thoroughly, but it appears to work without issues when you set the "shadowRoot" option to the `<dialog>` element Jodit is in.
