### ISSUE TITLE
Another language support

### ISSUE THREAD

**Issue by ManyakSVK** [xdan/jodit#115]
Do you plan add next options to support another languages / translations?
We need to add new languages, for now Slovak language - (sk-SK) , next will be Czech language.

 Now we need to provide language attribute for file  like 'de' or 'ru' and jodit loads up this file. But we will greatly appreciate if we can add next language - we can create language file and send to you this translation. OR you should to create new option in language selector with interface to add translations as objects. 

We are currently using same pair key:string translations but in extremely large json file with full coverage of jodit translation. 

Please add response as soon as possible or mail : michal.oravec@antastic.sk

Thank you and have a nice XMAS!

**Jodit Version:**   "^3.2.24",

**Expected behavior:**
-- lang option as string or object
-- or new translation file added to repo

**Actual behavior:**
-- new file for each language
-- static string provider for language option

**Comment by xdan** [comment]
You can create your own file for example `yourLanguageFile-sk-SK.js`
```javascript
Jodit.lang['sk-SK'] = {
    'Type something': 'Bitte geben Sie einen Text ein',

    // About
    Advanced: 'Fortgeschritten',
    'About Jodit': 'Über Jodit',
    // https://github.com/xdan/jodit/tree/master/src/langs
}
```
and use it in your project
```javascript
<script src="build/jodit.min.js"></script>
<script src="yourLanguageFile-sk-SK.js"></script>
<script>
var editor = new Jodit('#editor', {
    language: 'sk-SK'
});
</script>
```

**Comment by xdan** [comment]
And of course you can make `Pull Request` add this file in this folder https://github.com/xdan/jodit/tree/master/src/langs
