### ISSUE TITLE
Config modifications after initialization

### ISSUE THREAD

**Issue by Tiktack** [xdan/jodit#1161]
What is the right way to update editor configuration after it already initialized? 

As an example, I want to add additional fonts after it initialized, I don't know in advance that. 
I am using vanilla Jodit.

Cannot find anything in documentation :(

**Comment by xdan** [comment]
Unfortunately, the editor was not designed to be reactive. Therefore, it does not have this feature. You can simply recreate the editor.
let jodit = Jodit.make('#editor', options1)
jodit.destruct();
jodit = Jodit.make('#editor', options2)

**Comment by Tiktack** [comment]
Thanks for confirmation.
