### ISSUE TITLE
Bug: this.j.o.resizer is undefined in jodit version 4

### ISSUE THREAD

**Issue by Spaceman2019** [xdan/jodit#1166]
I modify jodit-svelte to use svelte 4 and jodit 4. When I now want to insert an image I got an error.
The error is in line 560 of selection.js.
**this.j.o.resizer is undefined**

**Jodit Version:**  4..2.27

**Browser:** Chrome/FF
**OS:** Windows
**Is React App:** False

![jodit](https://github.com/user-attachments/assets/392b41b0-b719-4b99-929f-5a0d48a917ef)

**Comment by xdan** [comment]
Maybe you have an ESM build connected? This plugin is not included by default.

**Comment by xdan** [comment]
Hm, yes, it is a bug
