### ISSUE TITLE
Edit Link bugg when there is a iframe

### ISSUE THREAD

**Issue by Lumartic101** [xdan/jodit#1176]
**Jodit Version:**  4.2.5

**Browser:** Chrome
**OS:** Windows
**Is React App:** False
**Reproduced on xdsoft.net:** True

**Code**

```html
<p>—
    <!-- --> <a href="https://www.gutenberg.org/cache/epub/55/pg55-images.html">The Wonderful Wizard of Oz</a> <em>by L. Frank Baum</em>.
</p>
<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/1002833698?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Every Day's Like This"></iframe></div>
```

```js
// A *self-contained* demonstration of the problem follows...
```
**Expected behavior:**
When editing a URL link within the editor, which also contains an iframe elsewhere, pressing "Update" after modifying the link (anchor tag a href) should successfully update the URL.

**Actual behavior:**
However, when an iframe is present anywhere in the editor, updating a link sometimes fails. Even though the link appears to be edited, inspecting the element reveals that the URL has not changed.

**Comment by junan-trustarc** [comment]
I have same situation, editing url doesn't work at first time if there is iframe.
Second try works but always failing at first editing of link.
We can easily reproduce in jodit demo page. 

1. Add URL link
2. Add Iframe(youtube video)
3. Edit added URL and update text or URL and save (it won't save properly)
 
![image](https://github.com/user-attachments/assets/8f2ee182-40d8-4863-ad23-ec8ee4617668)
