### ISSUE TITLE
Buttons still visible eventhough off

### ISSUE THREAD

**Issue by angelovancleef** [xdan/jodit#119]
I used the online editor to generate the code. I only selected a few buttons that I want to show, but still other buttons are still visible. How can I remove them?

```
var editor = new Jodit("#editor", {
  "showCharsCounter": false,
  "showWordsCounter": false,
  "showXPathInStatusbar": false,
  "defaultActionOnPaste": "insert_clear_html",
  "buttons": "|,bold,italic,|,superscript,subscript,,ul,ol,,|,|,image,file,video,table,link,|,|"
});
```

e.g. code toggle, select font, font size and some other buttons are still displayed even though your online code generator does not display them.

Also, I added a "video" button but the button is not visible.

**Comment by xdan** [comment]
You can disable mobile plugin or disable adaptive mode
https://xdsoft.net/jodit/doc/options/toolbarAdaptive/

**Comment by angelovancleef** [comment]
Thanks that did solve my issue(s) indeed. Thanks for the fast reply!

Any chance you know why I get so much errors when doing this? https://github.com/xdan/jodit/issues/118
