### ISSUE TITLE
Editor doesn't scroll down on Enter press

### ISSUE THREAD

**Issue by poohitan** [xdan/jodit#12]
There is an issue which seems to be caused by the `enter` plugin.
When the editor is full of content and you press Enter to add some more, it doesn't scroll down and the cursor becomes invisible. I should scroll down manually to see it.
Scrolling is the default behaviour of contenteditable divs, so I hope it's easy to fix.
This issue disappears if I add `enter` to the list of disabled plugins.

**Jodit Version:**  3.1.3

**Comment by xdan** [comment]
Hi, thank you. Fixed in 3.1.4
