### ISSUE TITLE
Additional libraries claim

### ISSUE THREAD

**Issue by zakini** [xdan/jodit#120]
According to the read me, Jodit works "without the use of additional libraries" but, as mentioned in #48, that's not true.

```typescript
Config.prototype.sourceEditorCDNUrlsJS = [
    'https://cdnjs.cloudflare.com/ajax/libs/ace/1.3.3/ace.js',
];

Config.prototype.beautifyHTMLCDNUrlsJS = [
    'https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.7.5/beautify.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.7.5/beautify-html.min.js',
];
```

These are additional libraries and ought to be in `package.json`. That way users of Jodit can properly manage their dependencies using the usual tools.

**Comment by xdan** [comment]
Jodit can work without ACEEditor https://xdsoft.net/jodit/doc/options/useAceEditor/ set false
and without https://xdsoft.net/jodit/doc/options/beautifyHTML/
