### ISSUE TITLE
Unable to focus

### ISSUE THREAD

**Issue by angelovancleef** [xdan/jodit#121]
Hi,

editor is working perfect, just one strange thing that I cannot seem to solve.
When I load my page I have an auto focus and I can type and do whatever which works fine. If I type something, then leave the textarea and go back, it all works.

If I load the page, and I do NOT type anything and leave the textarea, I will be unable to get the focus back on it. I cannot click on it, I cannot select it (focus) with the TAB button, I cannot do anything.

Does anyone have an idea what this can be? it only occures when using the "inline" option.

```
	let editor = new Jodit('#editor', {
		"autofocus": true,
		"height": 150,
		"width": 500,
		"preset": "inline",
		"toolbarAdaptive": false,
		"showCharsCounter": false,
		"showWordsCounter": false,
		"showXPathInStatusbar": false,
		"defaultActionOnPaste": "insert_clear_html",
		"buttons": "|,bold,italic,|,superscript,subscript,,ul,ol,,|,|,image,file,video,table,link,|,|"
	});
```

**Comment by angelovancleef** [comment]
No one knows?

**Comment by xdan** [comment]
In inline mode "height": 150, does not work
You need set height for your editor area yourself
