### ISSUE TITLE
Bold, Italics, etc.. Do nothing when pressed

### ISSUE THREAD

**Issue by austinwitherspoon** [xdan/jodit#122]
**Jodit Version:**  3.1.xxxxx

On the official demo pages [https://xdsoft.net/jodit/play.html](url) and at [https://xdsoft.net/jodit/](url) trying to bold text doesn't do anything on most sections of text.

On the Jodit Playground, If I try to bold just "Lorem Ipsum" in the first paragraph, it does nothing. Same with underline, strike, and italics.

Same thing with the other page, I cannot highlight and bold any text. Color changes fine, but bold, italics, and underline do nothing.

The same bug occurs on a Mac (Mojave) using Firefox, Chrome, and Safari, and on my Android phone using chrome.

**Comment by zandroid** [comment]
@xdan, thanks a lot.
