### ISSUE TITLE
Prevent editor from removing markup

### ISSUE THREAD

**Issue by xpressivecode** [xdan/jodit#124]
**Jodit Version:**  3.1.xxxxx

**Expected behavior:**
A user enters a partial html block (for instance `<tr><td>...</td></tr>`) and can expect it to remain as is. 

**Actual behavior:**
The tags are removed and only the content between is left present.

We have some legacy markup for widgets that on their own aren't 100% semantic markup, but when merged with their parent wrappers etc are. Is there a way to have the editor leave the markup as is? We've tried disabling the cleanHTML plugin and disabling the beautifyHTML property, but it continues to happen.

We also tried running ace in text mode, and while the editor appears to no longer care, the value we get back has the purged markup.

**Comment by xdan** [comment]
Give an example of such markup please

**Comment by xpressivecode** [comment]
I updated the original comment. The tr > td > text is often times by itself in some widgets, and the tbody exists in a parent container which is part of a different layout. We're essentially looking to use the editor to modify the widget source. But it keeps modifying the html.

**Comment by xpressivecode** [comment]
Any chance you were able to look at this at all?

**Comment by omarragi** [comment]
Is there an option not to strip anything out of my pasted html? 
can anyone here confirm if this option exists or not?

**Comment by omarragi** [comment]
@xpressivecode @xdan ?

**Comment by plegenza** [comment]
Attach to @omarragi question.
It is any option to disable checking and removing own pasted html?

**Comment by nicohagen** [comment]
https://xdsoft.net/jodit/docs/classes/config.Config.html#editHTMLDocumentMode

**Comment by xdan** [comment]
You can't use table tags without the table itself, the browser won't let you. Unfortunately this is a limitation of the browser and not the editor.
```js
const div = document.createElement('div');
div.innerHTML = '<tr><td>test</td></tr>'
console.log(div.innerHTML); // just "test"
```
