### ISSUE TITLE
Resize table column in editor

### ISSUE THREAD

**Issue by vinhnq3001** [xdan/jodit#126]
**Jodit Version:**  3.2.34

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**

**Actual behavior:**
i need resize column feature, what can i do? i user jodit 3.2.34

**Comment by xdan** [comment]
It works out of the box 
![image](https://user-images.githubusercontent.com/794318/51313679-38e11080-1a5f-11e9-9627-9eca8640813e.png)

**Comment by dskenny** [comment]
i'm in same problem.
if edior's parents has css "position:relative", jodit_table_resizer being located at other position, i think.

![image](https://user-images.githubusercontent.com/13345689/51516771-d2dbfb00-1e5b-11e9-9fc1-b52b3fea87ca.png)

**Comment by vinhnq3001** [comment]
> i'm in same problem.
> if edior's parents has css "position:relative", jodit_table_resizer being located at other position, i think.
> 
> ![image](https://user-images.githubusercontent.com/13345689/51516771-d2dbfb00-1e5b-11e9-9fc1-b52b3fea87ca.png)

Yep, i change parent css position: no set, it work.
