### ISSUE TITLE
Broken import 

### ISSUE THREAD

**Issue by dbettini** [xdan/jodit#131]
**Jodit Version:**  3.2.34, 3.2.33, 3.2.32

[This commit](https://github.com/xdan/jodit/commit/13807fdf46db2ca75ebee84716421af424125227) has changed the way the library is exported. I'm guessing this was by mistake because I doubt it would be done on purpose in a patch version bump. Basically, it's now a named export instead of a default one. This breaks all projects that used Jodit previously and updated to the new version, and all libs that use it, for example [jodit-vue](https://github.com/WendellAdriel/jodit-vue).

**Expected behavior:**
Default export is used, so `import Jodit from 'jodit'` works as expected.

**Actual behavior:**
Named export is used, so `import { Jodit } from 'jodit'` must be used instead.

**Comment by crashkonijn** [comment]
No update on this? Kinda weird that this project got broken like this.

**Comment by dsmackie** [comment]
I use 3.2.44 and have no issue with `import Jodit from 'jodit';`.

**Comment by dbettini** [comment]
@dsmackie It seems to be fixed as a part of a completely different bugfix, as a direct commit to master, without mentioning this issue in the [commit](https://github.com/xdan/jodit/commit/ad3e43af3db2299bc2536ec4005161a3ce557397#diff-f41e9d04a45c83f3b6f6e630f10117feR70) 😄

**Comment by dbettini** [comment]
[Fixed](https://github.com/xdan/jodit/commit/ad3e43af3db2299bc2536ec4005161a3ce557397#diff-f41e9d04a45c83f3b6f6e630f10117feR70) in 3.2.43
