### ISSUE TITLE
Inserting an image while iframe mode is enabled throws an exception

### ISSUE THREAD

**Issue by xpressivecode** [xdan/jodit#132]
**Jodit Version:**  3.2.33 / 3.2.34

**Expected behavior:**
I expect to be able to insert an image with the iframe mode enable

**Actual behavior:**
Receive an error: `Error: Parameter node most be instance of Node`

This happens locally as well as on the playground found here https://xdsoft.net/jodit/play.html

To re-create just turn the iframe mode on and try to insert an image through the toolbar.

**Comment by xdan** [comment]
Fixed in 3.2.42
