### ISSUE TITLE
resize not being set for editor in modal 

### ISSUE THREAD

**Issue by prbrowne** [xdan/jodit#136]
I have instantiated Jodit editor but the set size is not shown when the editor shows in a modal window.

**Jodit Version:**  3.1.xxxxx

**var editor = new Jodit("#editor", {
  "allowResizeY": false,
  "showCharsCounter": false,
  "showWordsCounter": false,
  "toolbarButtonSize": "small",
  "showXPathInStatusbar": false,
  "askBeforePasteHTML": false,
  "askBeforePasteFromWord": false,
  "disablePlugins": "fullsize,mobile",
  "height": 320,
  "buttons": "|,bold,underline,italic,|,|,ul,ol,|,outdent,indent,|,,image,file,video,table,link,|,align,undo,redo"
});*

Instead, when clicking in the editor, the editor then resizes.  Is there a method to update the editor to set the size?

**Comment by xdan** [comment]
Hi try send resize event
var editor = new Jodit('#editor')
after open modal
editor.events.fire('resize');

**Comment by mgholam** [comment]
If I resize the modal to be smaller (after making it larger) the Jodit editor stays the same size and mangles the modal, how can I fix this and have it shrink also?
