### ISSUE TITLE
how can I use only one external toolbar for many <textarea> ?

### ISSUE THREAD

**Issue by MatrixFr** [xdan/jodit#138]
I need use only one toolbar for many rich textarea, how can I do that with Jodit ?

srr stackoverflow dosn't have any tag available about jodit... :(

**Comment by millzee01** [comment]
any update on this because i like jodit but if I cannot register multiple textareas with a single jodit editor then i can't use it.

**Comment by romarioliveira25** [comment]
I was open this about: https://github.com/xdan/jodit/issues/258
without response by now.

My workaround to try solve that was render many editors but only one with full enabled options and others with:
```
{
    ...
    toolbar: false,
    readonly: true,
    showCharsCounter: false,
    showWordsCounter: false,
    showXPathInStatusbar: false,
    ...
}

```
But isn't the best way :(

**Comment by xdan** [comment]
Hi, added https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#3314
