### ISSUE TITLE
Problems pasting MS Word and plain text

### ISSUE THREAD

**Issue by galcott** [xdan/jodit#139]
I am using version 3.1.95. When I paste from MS Word I often get some code pasted in at the top as shown in the first screenshot. When pasting text, all line breaks are dropped and it looks like the second screenshot, in which I pasted some VBScript code. Can this be fixed?
![word](https://user-images.githubusercontent.com/4509764/52251694-6554b380-28cc-11e9-9a08-af17c4acba4e.jpg)

![vb](https://user-images.githubusercontent.com/4509764/52251704-84ebdc00-28cc-11e9-93f7-31e99b7933b4.jpg)

**Comment by stevekim** [comment]
Gosh 3.1.95 is too old. You need to upgrade to the latest version mate.

**Comment by galcott** [comment]
I'm on 3.2.36 now and it's still the same. And no answer from any developer after 9 days.

**Comment by xdan** [comment]
Hi, you can show the code snippet that you copy from the Word with which the problem occurs. I tried to repeat but I did not succeed

**Comment by galcott** [comment]
I'm not sure what you're asking for. What exactly did you try? The problem with Word doesn't happen all the time, but I pretty much fixed it by setting the import option to insert_clear_html. I'm more concerned with the problem of disappearing line breaks when copying plain text.

**Comment by xdan** [comment]
I tried to copy arbitrary pieces of doc document and paste it into the editor. It was all right. It's probably in the document itself. Can you attach it here or at least part of it?

**Comment by galcott** [comment]
As I said before, I'm not so concerned with the Word issue any more. What about the disappearing line breaks when copying plain text?
