### ISSUE TITLE
append data

### ISSUE THREAD

**Issue by startbbs** [xdan/jodit#15]
**
var editor = new Jodit('#editor', {
    uploader: {
        url: '/api.php/upload/mutiupload',
        defaultHandlerSuccess:function(success,data){
	        if(success==true){
		        $('p').append('dddddddddddd');
	        }
	        
        }
    }
});
**
$('p').append('dddddddddddd'); this line(jquery) does not working.
please guild. thanks

**Comment by xdan** [comment]
Hi, can you show me your demo page?
