### ISSUE TITLE
Image upload doesn't work if iframe is true

### ISSUE THREAD

**Issue by anindya-dhruba** [xdan/jodit#151]
**Jodit Version:**  3.2.38

**Code**
Here is the jodit config where image upload works:
```js
const config = {
  uploader: {
    url: 'https://xdsoft.net/jodit/connector/index.php?action=fileUpload'
  },
  filebrowser: {
    ajax: {
      url: 'https://xdsoft.net/jodit/connector/index.php'
    }
  }
};
```
And if I add `iframe: true`, it doesn't:
```js
const config = {
  iframe: true, // <--- enabled iframe mode
  uploader: {
    url: 'https://xdsoft.net/jodit/connector/index.php?action=fileUpload'
  },
  filebrowser: {
    ajax: {
      url: 'https://xdsoft.net/jodit/connector/index.php'
    }
  }
};
```

**Expected behavior:**
Image should get uploaded and inserted in the editor

**Actual behavior:**
Image gets uploaded, but doesn't get inserted in the editor. Here is the error displayed in browser console:
<img width="570" alt="screenshot 2019-03-01 at 11 45 32 am" src="https://user-images.githubusercontent.com/2575664/53619415-86819900-3c19-11e9-8ae8-16de48e382e0.png">

**Comment by marchaos** [comment]
This is cased by the same issue that I raised here - https://github.com/xdan/jodit/issues/150
I'll have a PR for this soon.
