### ISSUE TITLE
Is this software free for commercial use? 

### ISSUE THREAD

**Issue by marchaos** [xdan/jodit#153]
@xdan  - I noticed in some of the translation files that it states "Free Non-commercial Version", but nowhere on the website does it state anything about commercial use and since this is released under GPL-2 means that free commercial use should be permitted. Care to comment on commercial use?

**Comment by xdan** [comment]
Hi @marchaos, editor is licensed under GPL2 or higher and can be used in both commercial and non-commercial projects. Transliteration remained from the version of the editor 2.x https://github.com/xdan/jodit2, which was paid for commercial use.

**Comment by marchaos** [comment]
Hey. Thanks for clearing that up!
