### ISSUE TITLE
Customize the style of the text

### ISSUE THREAD

**Issue by mirk8xr** [xdan/jodit#159]
Is there a way to customize the style of the text you are entering on the fly?
I tried to use the "beforeSetValueToEditor" event, but without success!

**Code**

```javascript
editor.events.on('beforeSetValueToEditor', function (old_value) {
   return old_value.value.replace('user&nbsp;', '<span style="color:blue;"></span>');
});
```

**Expected behavior:**
The color of the text "user" change to blue.

**Actual behavior:**
The event "beforeSetValueToEditor" is not called. 

**Jodit Version:**  Latest

**Comment by mirk8xr** [comment]
I tried to use the 'beforeGetValueFromEditor' event too, but without success.

`var editor = new Jodit('#test');
editor.events.on('beforeGetValueFromEditor', function () {
    return editor.editor.innerHTML.replace(/a/g, 'b');
});`

The value returned in the event callback is completely ignored. The editor html does not change!

**Comment by xdan** [comment]
```js
 var editor = new Jodit("#editor");
        editor.events.on('beforeSetValueToEditor', function (old_value) {
            if (old_value) {
                return old_value.replace('user&nbsp;', '<span style="color:blue;">test</span>');
            }
        });

        editor.value = 'test user&nbsp;';
        console.log(editor.value); // test <span style="color:blue;">test</span>
```

works fine. But you need listen `change` event
Smt like this
```js
editor.events.on('change', Jodit.modules.Helpers.throttle(function () {
   var
        sel = editor.selection.save(),
        value = editor.getNativeEditorValue();

    editor.value = value.replace(/user/, '<span style="color:blue;">test</span>');
    editor.selection.restore(sel);
}, 300));
```

**Comment by mirk8xr** [comment]
Ok thanks for your reply.
But I don't understand why if I replace editor value several times the editor loose the focus and does not work properly:

```javascript
var _parseEditor = function(value) {
   var _newValue = value;
   _newValue.replace(/user/, "<span style="color:blue;">$USER</span>");
   _newValue.replace(/email/, "<span style="color:blue;">$EMAIL</span>");
   return _newValue;
};

editor.events.on('change', Jodit.modules.Helpers.throttle(function () {
    var sel = editor.selection.save(), value = editor.getNativeEditorValue();
    editor.value = _parseEditor(editor.value);
    editor.selection.restore(sel);
}, 300));
```
