### ISSUE TITLE
Viewing of UPLOADED IMAGES is broken

### ISSUE THREAD

**Issue by Tisoy21** [xdan/jodit#162]
hello is this natural ? the images i upload have been broken on viewing, i used the default setting of

``uploader: {
                url: 'https://xdsoft.net/jodit/connector/index.php?action=fileUpload'
    },
   filebrowser: {
                // buttons: ['list', 'tiles', 'sort'],
                ajax: {
                    url: 'https://xdsoft.net/jodit/connector/index.php'
                }
  },``

do i need to supply my own server side script?

**Comment by marchaos** [comment]
You shouldn't rely on https://xdsoft.net/ - supply your own server side to complete the upload process.
