### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Tisoy21** [xdan/jodit#164]
Cannot convert undefined or null to object

how can i debug this 
![Screen Shot 2019-03-12 at 6 00 51 AM](https://user-images.githubusercontent.com/44186119/54161370-e6373a00-448c-11e9-8c66-b52f62321a7a.png)

**Comment by xdan** [comment]
On what request to the server or on what action did this error occur? What did the server return?

**Comment by Tisoy21** [comment]
on fileBrowser sir, it tells

`{ "success": false, "time": "2019-03-15 10:58:12", "data": { "messages": [ "Action \"\" not found", "/home/dwm2019/public_html/stages/connector/index-test.php - 2311", "/home/dwm2019/public_html/stages/connector/index-test.php - execute - 3128" ], "code": 404 }, "eslapsedTime": 0.0003559589385986328125 }`

i followed only sir your docs and examples for setting a filebrowser button i set this a property on Js like this

`filebrowser: {
     ajax: {
          url: 'https://xdsoft.net/jodit/connector/index.php'
     }
}`


the uploading of image is working to me 

Note: I used my own server to do this

only that filebrowser have problem

**Comment by xdan** [comment]
You did show response, can you show me request?

**Comment by Tisoy21** [comment]
you mean the index.php file ? based on the docs, only set it in JS side, by listener of file browser

`filebrowser: { ajax: { url: 'https://xdsoft.net/jodit/connector/index.php' } }`

how can i detect on what lines this occured ? there's no line on the stated error only on that UI file browsing when i click that button
