### ISSUE TITLE
Control the number of buttons displayed in toolbar

### ISSUE THREAD

**Issue by Tisoy21** [xdan/jodit#167]
hello i want to control the number of buttons displayed in toolbar cause i dont like to view other buttons to preserve spaces and get all those button on one line thanks

**Comment by xdan** [comment]
Hi, https://xdsoft.net/jodit/play.html?toolbarAdaptive=false&buttons=bold%2C%2C%7C%2C%7C%2C%7C%2C%7C%2C%2C%7C&currentTab=Buttons

**Comment by Tisoy21** [comment]
Thanks sir
