### ISSUE TITLE
Show file picker without WYSIWYG

### ISSUE THREAD

**Issue by SachsKaylee** [xdan/jodit#170]
Hello there!

I'd like to provide a file picker/uploader without having the actual WYSIWYG editor in some places. (e.g. favicon picker, ...)

Is there currently a way to do this? If not would you say that this is a realistic thing to implement with Jodit's current architecture?

Thank you for your time and effort put into this.

_Edit_: Tried this, but got an import error. I'll investigate more once I get home this evening. `ModuleNotFoundError: Module not found: Error: Can't resolve 'jodit/src/modules/filebrowser/fileBrowser' in '/home/patrick/Development/helios/git/pages'`

```js
import FileBrowser from "jodit/src/modules/filebrowser/fileBrowser";

const b = new FileBrowser(undefined, {
  ajax: {
    url: "/api/files/browser"
  }
});
b.open((data) => {
  console.log("opened", data)
});
```

**Comment by xdan** [comment]
Hey. All modules are available from the modules field of Jodit
Jodit.modules.Uploder
Jodit.modules.FileBrowser etc
```javascript
const b = new Jodit.modules.FileBrowser(null, {
  ajax: {
    url: "/api/files/browser"
  }
});
b.open((data) => {
  console.log("opened", data)
});
```
should work

**Comment by SachsKaylee** [comment]
Thank you very much. This seems to work. However, I am unable to upload files in the FileBrowser. No request is being made to my AJAX URL. The upload works fine in a regular file browser created by the editor.

**Comment by SachsKaylee** [comment]
Got it working. The jodit constructor wants the props in this format:
```js
filebrowser: {
  ajax: {
    url: "/api/files/browser"
  }
},
uploader: {
  url: "/api/files/upload"
}
```

The FileBrowser is this format:
```js
ajax: {
  url: "/api/files/browser"
},
uploader: {
  url: "/api/files/upload"
},
```

Thank you for pointing me in the right direction.
