### ISSUE TITLE
Convert to more permissive license?

### ISSUE THREAD

**Issue by raygesualdo** [xdan/jodit#178]
Hey @xdan! Really like Jodit and am evaluating it for use where I work. Our lawyers have issues with the GPL license. Is there any possibility it could be re-licensed under something more permissive, like the MIT license? If Jodit stays with the GPL, we sadly won't be able to continue evaluating.

**Comment by mdevDE** [comment]
Hey Valeriy, although I bought the OEM license I really would welcome a move towards the MIT License.

**Comment by xdan** [comment]
Hello everyone, I do not really understand the difference between the GPL and MIT. Can I, in addition to the GPL, also lay out under the MIT? Or just one option?
What are the cons and what are the pros?
Will the return of the OEM version save the situation? Am I doing Jodit now under OEM license

**Comment by mdevDE** [comment]
Hi Valeriy, I am not a lawyer, but as far as I understood the GPL license is more restrictive than the MIT license. Given the amount of text it is also more complicated especially for non-lawyers.

I have found some links which discuss the differences of the licenses
https://www.quora.com/What-are-the-key-differences-between-the-GNU-General-Public-license-and-the-MIT-License
https://stackoverflow.com/questions/3902754/mit-vs-gpl-license
http://mdbitz.com/2009/12/01/what-is-the-main-difference-between-mit-and-gpl-licenses/

**Comment by mdevDE** [comment]
Hi Valeriy, any news on this?

**Comment by mdevDE** [comment]
Hi Valeriy, any news on this?

**Comment by nordbit** [comment]
GPL force user to open source of own software. MIT is the real spirit of freedom.
Do not expect many stars and popularity with GPL

**Comment by xdan** [comment]
You can use Jodit under MIT and under GPL
