### ISSUE TITLE
Provide a focus method

### ISSUE THREAD

**Issue by stamminator** [xdan/jodit#180]
Feature request: add a `focus` method on the `Jodit` instance. There are many use cases in which the `autoFocus` option is not flexible enough.

**Comment by xdan** [comment]
Hi
```js
var editor = new Jodit('#editor');
editor.selection.focus();
```

**Comment by stamminator** [comment]
Thanks, that did the trick. I'm using this control inside an AngularJS 1.7 app, which has its own quirks, but when I did this, it worked fine:
```javascript
setTimeout(function() {
  editor.selection.focus();
}, 0);
```
