### ISSUE TITLE
After doing a print the background image no longer displays

### ISSUE THREAD

**Issue by mwaschkowski** [xdan/jodit#192]
**Jodit Version:**  3.1.95

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**
Print preview and then return to document and everything looks the same as originally.

**Actual behavior:**
Click on the print button and then the background image is lost/no longer displayed.

Here is the HTML that you can use to reproduce. I tried this in the playground with the same result.

Thank you for your help with this, please let me know if there is anything else that I can do!

Mark

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,maximum-scale=1.0">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<style type="text/css" media="print">
    body {
            background: rgb(204, 204, 204);
            font-family: Arial;
            font-size: 8px;
        }

        page {
            background: white;
            display: block;
            margin: 0 auto;
            box-shadow: 0 0 0.5cm rgba(0, 0, 0, 0.5);

        }

        page[size="A5"][layout="landscape"] {
            width: 210mm;
            height: 148mm;
        }

        .mainTable {
            width: 100%;
            top: 50%;
            transform: translateY(-50%);
            position: relative;
        }
        .wrapper {
              height:100%;
              width:100%;
              position: relative;
        }
        
        .background {
            background-image:url('https://pdfservice-mwaschkowski.c9.io/javascripts/fdwicked/specific/willetts/park.jpg');
            background-size:cover;
            width: 152mm; 
            height: 102mm;
        
          position: absolute;
          top: 50%;
          left: 50%;
        
          margin: -50mm 0 0 -76mm;
          box-shadow: inset 0 0 0 8px rgba(255, 255, 255, 0.5);
          z-index: 10;
        }
        .inner{
            border:1px solid white;
            width:100%;
            height:100%;
            
        }
        .celebratingDiv{
            width:100%;
            margin:auto;
            text-align:center;
            margin-top:50px;
        }
        .nameDiv{
            width:100%;
            margin:auto;
            text-align:center;
            margin-top:40px;
        }
        .dateDiv{
            width:100%;
            margin:auto;
            text-align:center;
            margin-top:40px;
        }
        .celebrating{
            color:white;
            font-size:32px;
            font-style: italic;
            font-family: "Times New Roman";
        }
        .name{
            color:white;
            font-size:46px;
            font-family: "Times New Roman";
            font-style:bold;
        }
        .date{
            color:white;
            font-size:32px;
            font-style: italic;
            font-family: "Times New Roman";            
        }
</style>
<style type="text/css" media="screen">
    body {
            background: rgb(204, 204, 204);
            font-family: Arial;
            font-size: 8px;
        }

        page {
            background: white;
            display: block;
            margin: 0 auto;
            box-shadow: 0 0 0.5cm rgba(0, 0, 0, 0.5);

        }

        page[size="A5"][layout="landscape"] {
            width: 210mm;
            height: 148mm;
        }

        .mainTable {
            width: 100%;
            top: 50%;
            transform: translateY(-50%);
            position: relative;
        }
        .wrapper {
              height:100%;
              width:100%;
              position: relative;
        }
        
        .background {
            background-image:url('https://pdfservice-mwaschkowski.c9.io/javascripts/fdwicked/specific/willetts/park.jpg');
            background-size:cover;
            width: 152mm; 
            height: 102mm;
        
          position: absolute;
          top: 50%;
          left: 50%;
        
          margin: -50mm 0 0 -76mm;
          box-shadow: inset 0 0 0 8px rgba(255, 255, 255, 0.5);
          z-index: 10;
        }
        .inner{
            border:1px solid white;
            width:100%;
            height:100%;
            
        }
        .celebratingDiv{
            width:100%;
            margin:auto;
            text-align:center;
            margin-top:50px;
        }
        .nameDiv{
            width:100%;
            margin:auto;
            text-align:center;
            margin-top:40px;
        }
        .dateDiv{
            width:100%;
            margin:auto;
            text-align:center;
            margin-top:40px;
        }
        .celebrating{
            color:white;
            font-size:32px;
            font-style: italic;
            font-family: 'Roboto', sans-serif;
            line-height: normal;
        }
        .name{
            color:white;
            font-size:46px;
            font-family: 'Roboto', sans-serif;
            font-weight:bold;
            line-height: normal;
        }
        .date{
            color:white;
            font-size:32px;
            font-style: italic;
            font-family: 'Roboto', sans-serif;       
            line-height: normal;
        }
</style>

<title></title>
<meta name="description" content="">
<meta name="keywords" content="">

<page size="A5" layout="landscape">
    <div class="wrapper">
        <div class="background">
            <div class="inner">
                <div class="celebratingDiv">
                    <span class="celebrating">test1</span>
                </div>
                <div class="nameDiv">
                    <div>
                        <font color="#ffffff" face="Roboto, sans-serif"><span style="font-size: 46px;"><strong>test2</strong></span></font>
                    </div>
                </div>

                <div class="dateDiv">test3</div>
            </div>

        </div>
    </div>

    

</page>

**Comment by mwaschkowski** [comment]
Please find the HTML attached

[nameplate (1).zip](https://github.com/xdan/jodit/files/3122576/nameplate.1.zip)

**Comment by mwaschkowski** [comment]
Hi,

Is there anything else I can provide to track down this issue?

Thank you,

Mark

**Comment by xdan** [comment]
Hi, sorry but do not understand how i can reproduce it
