### ISSUE TITLE
Javascript error when closing image edit dialog the second time

### ISSUE THREAD

**Issue by masbaehr** [xdan/jodit#193]
Browser used: Chrome

Reproduce: 
Go to :  https://xdsoft.net/jodit/play.html
Select the image, select edit 
![image](https://user-images.githubusercontent.com/38694044/56880294-66752700-6a5c-11e9-84e5-c3c303ce3189.png)
Select "Cancel".
Repeat.
Now on 'Cancel' there will be the JS error

![image](https://user-images.githubusercontent.com/38694044/56880310-7bea5100-6a5c-11e9-8fc0-6643af4d0a35.png)

**Comment by xdan** [comment]
Should be fixed in latest version
