### ISSUE TITLE
Add another font family / font style

### ISSUE THREAD

**Issue by Tisoy21** [xdan/jodit#194]
how can i add another font family/ font style on the font choice ? any idea ?

**Comment by Tisoy21** [comment]
![Screen Shot 2019-04-30 at 9 59 29 PM](https://user-images.githubusercontent.com/44186119/56968562-f36fcb80-6b95-11e9-9ece-0dfb8192f1e5.png)
like this ?

**Comment by mdevDE** [comment]
Hi please have a look at https://xdsoft.net/jodit/doc/options/controls/

var editor = new Jodit("#editor", {
controls: { fontsize: {list:  "12,14"},
                   font    : {list:  { "your new font goes here": "font name" ,
                                           "Helvetica,sans-serif" "Helvetica"      }}}});

Hope this is of any use

**Comment by Tisoy21** [comment]
Thanks sir ! appreciated

**Comment by ewth** [comment]
Thanks for that @mdevDE wasn't quite there but got me in the right direction:
`
var editor = new Jodit("#editor", {
    controls: {
        font: {
            list: {
                "Font Name": "Font Label Appears in List"
            }
        }
    }
});
`

**Comment by ewth** [comment]
Thanks @mdevDE &mdash; wasn't quite there but got me in the right direction:
```
var editor = new Jodit("#editor", {
    controls: {
        font: {
            list: {
                "Font Name": "Font Label Appears in List"
            }
        }
    }
});
```

**Comment by juanmagdaleno** [comment]
I did custom fontsize and add font-family using:  jodit jodit-react

![image](https://user-images.githubusercontent.com/8212559/180629495-ba56f21c-ce38-41e1-96b9-93b3dcaa210c.png)

http://rmamuzic.rs/node_modules/jodit/examples/index.html
