### ISSUE TITLE
Disable click events

### ISSUE THREAD

**Issue by danlobo** [xdan/jodit#199]
**Jodit Version:**  3.2.44

**Code**

Insert this snippet as source code:

```ts
<button type="button" onclick="alert('hey there!')">Click me</button>
```
or this one

```
<form action="" method="GET">
<button type="submit">Click me</button>
</form>
```
Go back to editor, click the button.

**Expected behavior:**
- Element doesn't fire it's default events, like click, double click etc, giving us the chance to edit the element properties

**Actual behavior:**
Element triggers any event associated with it. Depending on the code, page gets a refresh or jumps to another URL.

**Comment by xdan** [comment]
This is default contenteditable behavior, if you need destruct editor
