### ISSUE TITLE
"Element "[object HTMLDivElement]" should be string or HTMLElement" in IE

### ISSUE THREAD

**Issue by jallewa** [xdan/jodit#2]
Example code:
`var element = document.getElementById('<elementId>'); //  e.g. HTMLDivElement`
`new Jodit(element, options);`

Throws error: _"Element "[object HTMLDivElement]" should be string or HTMLElement"_ in every IE version.
In all other browsers, the condition in _jodit.ts_ line 153 works _(this.element instanceof HTMLElement)_.

**Comment by xdan** [comment]
Please write what options you use and in which Windows system?

**Comment by jallewa** [comment]
My options:
`
var buttons = [ 'bold', 'italic', '|', 'ul', 'ol', '|', 'font', 'fontsize', 'brush', 'paragraph', '|', 'image', 'link', '|', 'align','|', 'undo', 'redo'];
var options = {
            buttonsMD: buttons,
            buttonsSM: buttons,
            buttonsXS: buttons,
            buttons: buttons,
            placeholder: this.placeholderText,
            iframe: true,
            globalFullsize: false,
            iframeStyle: '.jodit_wysiwyg{padding:0;margin:0;}',
        }`

On Windows 10.

In my Code I use : `this.editor = new Jodit(edit, this.getEditorOption());`. And 'edit' is an HTMLElement in a iFrame (This iFrame is local)

Maybe I have a solution for line 153: `this.element instanceof HTMLElement` => `this.element.nodeType !== Node.ELEMENT_NODE`
