### ISSUE TITLE
beautify-html.min.js not loaded, beautify does not work

### ISSUE THREAD

**Issue by mguerrieri** [xdan/jodit#202]
**Jodit Version:**  3.2.44

                 var htmlEditor = new Jodit(editorElement, {
                    sourceEditorCDNUrlsJS: [
                        'https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.4/ace.js'
                    ],
                    beautifyHTMLCDNUrlsJS: [
                        'https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.10.0/beautify.min.js',
                        'https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.10.0/beautify-html.min.js'
                    ]
                });

**Expected behavior:**
Both beautify.min.js and beautify-html.min.js are loaded.

**Actual behavior**:
Only beautify.min.js is loaded.  html_beautify is never defined so beautify does not ever fire.

**Issue**:
In loadNext() of source.ts, the following code is causing the issue:

```
if (this.lastTuple) {
    this.lastTuple.element.removeEventListener('load', this.lastTuple.callback);
}

```
What is happening is beautify.min.js is loaded via appendScript(), setting the lastTuple variable.  However, before its 'load' event fires, loadNext() is called again for ace.js.  Since lastTuple is global to source.ts and is already assigned, the 'load' callback for beautify.min.js is removed so lastTuple.callback is never executed and the second url for beautify-html.min.js is never loaded.

This issue may be dependent on the fact that beautify.min.js does not finish loading quickly enough, so it may not happen depending on the beautify urls specified, but it happens to me every time.

**Comment by xdan** [comment]
Fixed
