### ISSUE TITLE
Ace editor does not scroll

### ISSUE THREAD

**Issue by mguerrieri** [xdan/jodit#203]
**Jodit Version:**  3.2.44

Go to Jodit Playground.  Turn off "Auto Height".  Set "Default mode" to either "Split code" or "Source code".  Make sure there is enough code in the editor to cause a vertical scrollbar to appear (there is by default in the demo).  Focus the source code editor and the use cursor to move down below the visible code editor window,

**Expected behavior:**
The code editor should scroll to always keep the cursor visible.  The caret should never be off-screen.

**Actual behavior:**
The code editor does NOT scroll, making the cursor invisible.  Same thing happens if you are at the bottom of the code and arrow up past the top of the editor.  You need to either scroll the scrollbar manually/use the mouse wheel, or use the resizer to resize the editor to scroll the cursor back into view.

**Comment by iktash** [comment]
Does not seem to be fixed. Currently it's not only does not scroll until you start typing, but there is also a double scroll:
![Screenshot (8)](https://user-images.githubusercontent.com/2663305/80801514-f3d9e280-8bac-11ea-9750-632e180810eb.png)
