### ISSUE TITLE
Set the default font family/ style

### ISSUE THREAD

**Issue by Tisoy21** [xdan/jodit#207]
![image](https://user-images.githubusercontent.com/44186119/58111518-2e5ca080-7c24-11e9-8963-64de2a1150f3.png)

how can i set the default font family / font style on the editor ? i want to that "Montserrat,Sans Serif"

**Comment by xdan** [comment]
Best way make something like this https://xdsoft.net/jodit/doc/options/editorCssClass/
But in new version was added `style` option
```	
editor = new Jodit(appendTestArea(), {
	style: {
		fontFamily: 'Arial'
	}
});
```
