### ISSUE TITLE
In laravel project it can't define object

### ISSUE THREAD

**Issue by AlexandrTarasov** [xdan/jodit#208]
**Jodit Version:**  3.1.xxxxx

**Project base**
Laravel 5.7
list of packages:
    "axios": "^0.15.3",
    "bootstrap": "^4.3.1",
    "cross-env": "^5.2.0",
    "jodit": "^3.2.44",
    "jquery": "^3.1.1",
    "laravel-mix": "^4.0.15",
    "lodash": "^4.17.4",
    "popper.js": "^1.15.0",
    "resolve-url-loader": "2.3.1",
    "sass": "^1.20.1",
    "sass-loader": "7.*",
    "summernote": "^0.8.12",
    "vue-template-compiler": "^2.6.10"

**Actual behavior:**
 ReferenceError: Jodit is not defined[Learn More] app.js:36803:5
    js http://tar.loc/js/app.js:36803
    __webpack_require__ http://tar.loc/js/app.js:20
    0 http://tar.loc/js/app.js:36900
    __webpack_require__ http://tar.loc/js/app.js:20
    <anonymous> http://tar.loc/js/app.js:84
    <anonymous> http://tar.loc/js/app.js:1
After proper compilation it can't create object. Other similar editors can. And it olso works if I include js of jodit from cdn

**Comment by ghost** [comment]
```
let jodit = require('jodit');
window.Jodit = jodit.Jodit;
var editor = new Jodit('#textarea');
```

**Comment by AlexandrTarasov** [comment]
I've included it directly without all this overcomplicated stuff with package managers and tricky workarounds

**Comment by ghost** [comment]
its better if you use webpack you just add 
```
let jodit = require('jodit');
window.Jodit = jodit.Jodit;
var editor = new Jodit('#textarea');
```
in your resources/app.js
and it will work but if you already managed to make it work you should close this issue
