### ISSUE TITLE
Pasting an MS Excel cell inserts the cell as image, too

### ISSUE THREAD

**Issue by davidd4** [xdan/jodit#219]
**Jodit Version:**  3.2.26

**Use case**
Copying a cell from an Excel table and pasting into the editor, when Upload module is active.

**Expected behavior:**
The cell content is pasted as (html) text.

**Actual behavior:**
The cell content is pasted as text. But additionally the cell content is pasted as an image, too. 

_Can be reproduced in Jodit playground. Upload module should be activated._

**Comment by xdan** [comment]
Fixed in previews release

**Comment by notsigma** [comment]
After attempting to updating from v3.4.15 I found this issue. Any way I can fix it or is it a bug? 

Thanks!
