### ISSUE TITLE
Error when creating a new text node

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#22]
**Jodit Version:**  3.1.68

**Code**
Jodit.modules.Dom.create('text', 'Hello world');
**Expected behavior:**
create a new text node

**Actual behavior:**
Uncaught TypeError: Cannot read property 'createTextNode' of undefined

![jodit_bug01](https://user-images.githubusercontent.com/37185489/37377576-00e18908-272b-11e8-8286-e6643138e31a.jpg)

**Comment by xdan** [comment]
Hi, `Dom.create` is depricated. 
please, use native method 
`document.createTextNode('Hello world!')`
