### ISSUE TITLE
Duplicate element IDs

### ISSUE THREAD

**Issue by willgearty** [xdan/jodit#227]
**Jodit Version:**  3.2.36

**Problem**

I'm trying to use anchors to allow users to move between different parts of the webpage, but it appears that jodit is keeping a hidden version of the visible DOM elements, such that every ID on the page is duplicated. I've found a way around this with javascript (`<a onclick="document.querySelector('.prettify #section1').scrollIntoView()">Click Me</a>`), but it'd be better if we could use the normal anchor method.

**Code**

```html
<!--within the jodit editable interface-->
<a href="#section1">Click Me</a>
<!--a bunch of stuff here-->
<p id="section1">Section 1</p>
```

**Expected behavior:**
Clicking the link should move the user to the element with the "section1" ID.

**Actual behavior:**
Nothing happens, because the first element with the "section1" ID is hidden as part of the jodit duplicate.

**Comment by xdan** [comment]
Can you show full example page here.
```html
<div id="editor">
	<div id="section1">
			<dt><dfn>Falli igitur possumus.</dfn></dt>
	</div>
</div>
<a href="#section1">Click Me</a>
<script src="./build/jodit.min.js"></script>
<script>
	const editor = new Jodit('#editor')
</script>
```
And it works

**Comment by willgearty** [comment]
Sorry, this is actually related to our specific setup, not a problem with jodit!
