### ISSUE TITLE
npm start error /npm run build error / npm test error/

### ISSUE THREAD

**Issue by marcosRaphael** [xdan/jodit#228]
![image](https://user-images.githubusercontent.com/52636397/60773438-342b1a00-a0dc-11e9-9a9b-2161eb4b63e0.png)

I'm trying to run the demo

if you want to simulate the error:
use windows 7
use node version: 10.16.0 LTS
git clone https://github.com/xdan/jodit.git
cd jodit
npm install
npm start -< error
http://localhost:2000/

**Comment by xdan** [comment]
I think you should update nodejs

**Comment by marcosRaphael** [comment]
> I think you should update nodejs

I tried with all these versions and it did not work :(
![image](https://user-images.githubusercontent.com/52636397/60777152-3f476f80-a107-11e9-961a-2c3f9e8cfb62.png)

**Comment by amrita-syn** [comment]
@marcosRaphael I had the same issue and mine went away with node 11.10.0 
Can you try deleting the node_modules and yarn/package-json lock files and reinstalling after changing to node 11.10.0 ?

**Comment by xdan** [comment]
Fixed, it was only on Windows

**Comment by StukalovSS** [comment]
@marcosRaphael , in the end, did you solve you problem? How did you do it?

**Comment by marcosRaphael** [comment]
> @marcosRaphael , in the end, did you solve you problem? How did you do it?

I changed my operating system to a linux distribution and solved the problem
