### ISSUE TITLE
Remove font family / font style

### ISSUE THREAD

**Issue by Markal03** [xdan/jodit#230]
Hello,
Is there a way to remove a specific `font-family` from the default font dropdown menu?

![Dropdown](https://user-images.githubusercontent.com/26689191/60977360-3b923380-a327-11e9-983d-a59ad339c399.PNG)

I already tried to play around with the `controls` reported below but it just doesn't seem to be working.
```ts
controls: {
      font: {
        list: {

        }
       }
 }
```

Is there anything that can be done about it?

**Comment by xdan** [comment]
https://github.com/xdan/jodit/issues/26

**Comment by Markal03** [comment]
> #26

This solution works fine if you wanted to add fonts, but it doesn't seem to remove any present font.

For instance, the following piece of code should remove `Helvetica` and add `Courier New`:

```Javascript
controls: {
	font: {
		list: {
		"Arial,Helvetica,sans-serif": "Arial",
		"Georgia,serif": "Georgia",
		"Impact,Charcoal,sans-serif": "Impact",
		"Tahoma,Geneva,sans-serif": "Tahoma",
		"'Times New Roman',Times,serif": "Times New Roman",
		"Courier New,sans-serif": "Courier New"
		}
	}
}
```
But, as you can see in the image below, `Helvetica` is still present in the font list.

![Fonts](https://user-images.githubusercontent.com/26689191/61035154-890daf80-a3be-11e9-8d84-df81ea129cad.PNG)

Thank you for your help.

**Comment by xdan** [comment]
You can use this construction for replace default Object option
```javascript
controls: {
	font: {
		list: Jodit.Object({
			"Arial,Helvetica,sans-serif": "Arial",
			"Georgia,serif": "Georgia",
			"Impact,Charcoal,sans-serif": "Impact",
			"Tahoma,Geneva,sans-serif": "Tahoma",
			"'Times New Roman',Times,serif": "Times New Roman",
			"Courier New,sans-serif": "Courier New"
		})
	}
}
```
yes, in another case it extends default object

**Comment by Markal03** [comment]
This did the trick, thank you!

**Comment by WizzardMaker** [comment]
This trick doesn't seem to work anymore, it seems.

**Comment by Indorsel** [comment]
@xdan Valeriy, answer please how can we remove this default fonts now? 
```controls: { font: { list: { ... } } } or controls: { font: { list: Jodit.Object({ ... }) } } }```
these methods can't resolve problem now.

**Comment by GFoley83** [comment]
@xdan Is the proper way to do this currently documented anywhere? 
We're trialing Jodit at the moment but the lack of documentation is really putting us off.

**Comment by xdan** [comment]
@Indorsel @GFoley83 
Hi, guys. Yes Jodet.Object was deprecated and replaced on Jodit.atom https://xdsoft.net/jodit/docs/modules/plugins_font.html
