### ISSUE TITLE
can't drop image on IE11

### ISSUE THREAD

**Issue by jerateep** [xdan/jodit#234]
**Jodit Version:**  3.2.xxxxx

**Browser:**  IE11
**OS:**  Windows 10

**Code**

```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**
Browse image with Drop image on IE 11 from local disk then image must be pasted in editor
**Actual behavior:**
Javascript error in developer console
`SCRIPT438: Object doesn't support property or method 'includes'`

**Comment by newmangreen** [comment]
IE 11 is not supporting Array.includes, add polyfill from here:
[https://developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Global_Objects/Array/includes](https://developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

**Comment by xdan** [comment]
Fixed in latest version
