### ISSUE TITLE
Refactoring out link maker

### ISSUE THREAD

**Issue by a-reisberg** [xdan/jodit#235]
**Jodit Version:**  3.2.54

First, I want to thank for the great project.

It would be nice if the hyperlink maker could be abstracted out like `applyCSS` so that we can turn a selection into a link programmatically.  Currently, it seems to be quite tied up with the link plugin and there's no way to make a hyperlink programmatically.

Another reason is that hyperlink insertion also behaves in a somewhat inconsistent way compared to `applyCSS`. Maybe it's intentional, but in case it's not, it would be nice to unify the two (especially when `applyCSS` already allows custom tags).

Suppose I have
> **this is** very cool
```html
<strong>This is</strong> very cool.
```
and my current selection is "is very".  If I turn the selection into italic, I will get
> **this _is_** _very_ cool
```html
<strong>This <em>is</em></strong><em> very</em> cool.
```
However, if I use the url tool to make a link, I will get
```html
<strong>This <a href="google.com">is very</a></strong>&nbsp;cool.
```
Note that the formatting of `very` is altered.

Thank you!

**Comment by xdan** [comment]
Fixed in 3.8.19
