### ISSUE TITLE
Editor crashes with error - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Ronny25** [xdan/jodit#24]
**Jodit Version:**  3.1.68

**Code**

```ts
var jodit = new Jodit('#editor', {
  cleanHTML: {
    cleanOnPaste: true,
    allowTags: 'p,a[href]'
  }
});
```
OR
```ts
var jodit = new Jodit('#editor', {
  allowTags: {
    p: true,
    a: {
      href: true
    }
  }
});
```

**Expected behavior:**
Clean inserted HTML with the rules above without errors both after paste HTML or changing editor's value.

**Actual behavior:**
Editor crashes  with an error - Maximum call stack size exceeded (http://joxi.ru/YmEKvEnF083xdA). No matter after which action: inserting HTML or changing editor's value like in the docs.

**Comment by xdan** [comment]
What `HTML` do you insert or edit? i can not repeat you issue.

**Comment by Ronny25** [comment]
I've tried this from your example

```js
editor.value = 'Sorry! <span></span><strong>Goodby</strong> <span>mr.</span> <a style="color:red" href="http://xdsoft.net">Freeman</a>';
console.log(editor.value);
```

And one from the website with text and link (don't think it really matters).

**Comment by xdan** [comment]
Which browser and system?

**Comment by Ronny25** [comment]
**Ubuntu** 16.04 LTS
**Chrome** 65.0.3325.146

**Comment by xdan** [comment]
```javascript
var jodit = new Jodit('#editor', {
    cleanHTML: {
        allowTags: {
            p: true,
            a: {
                href: true
            }
        }
    }
});
editor.value = 'Sorry! <span></span><strong>Goodby</strong> <span>mr.</span> <a style="color:red" href="http://xdsoft.net">Freeman</a>';
console.log(editor.value);
```
Is this code throw the error?

**Comment by Ronny25** [comment]
Yes, it does.

**Comment by Ronny25** [comment]
I've found the problem.
I'm using your Editor as a React component and it has been looped within lifecycle methods.
Seems to be working pretty fine, thanks for your quick responses!
