### ISSUE TITLE
Add attributes (like class) to html

### ISSUE THREAD

**Issue by bryanjjohnson** [xdan/jodit#243]
**Jodit Version:**  3.2.47

**Browser:**  All
**OS:**  All

I looked over the documentation, and couldn't find anything. Is there a way to add attributes to a tag? I'm using a css framework that expects certain classes added to things like headers, list, etc.

 For example:
```html
<ul class="bulleted">
   <li>Item 1</li>
</ul>
```

**Comment by xdan** [comment]
Hi @bryanjjohnson https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#3316

**Comment by Tarnn** [comment]
@xdan can't seem to get a particular stylesafterwards via

Element.style.someStyle always show as blank
