### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by millzee01** [xdan/jodit#244]
**Jodit Version:**  3.2.47

**Browser:**  All
**OS:**  All

Hi, 

Can we have a way to register mutliple textareas/divs on a page to use a single toolbar like NicEdit?

With nicEdit we can use:
<div id="textEditor" class="textEditor" unselectable="on"></div<

var myNicEditor = new nicEditor();
myNicEditor.setPanel('textEditor');   

then all we need to do is:

//add id instance to editor
$('div').each(function() {
   myNicEditor.addInstance($(this).attr("id"));
});

**Comment by xdan** [comment]
@millzee01  
Added same API
```js
var editor = new Jodit('#editor');
editor.setPanel('#textEditor');


//add id instance to editor
$('div').each(function() {
editor.addPlace('#' + $(this).attr("id"));
});
```
