### ISSUE TITLE
Images are being invisible after hitting print 

### ISSUE THREAD

**Issue by beyzakilickol** [xdan/jodit#246]
**Jodit Version:**  3.2.45

**Browser:** Chrome
**OS:**  Mac

**Expected behavior:**
   When print button is pressed, all content of the editor is expected to appear on the preview page of print window. 
**Actual behavior:**
 Images are being disappeared on both preview page and editor after hitting print button. I have checked the source code after the image is disappeared, <img> tag with the correct 'src' attribute is still there.
Thanks

**Comment by amrita-syn** [comment]
You have to use promises. This is happening because when you print the doc, it tries to fetch the images from their src but the print proceeds without waiting for them. So, you have to wait for the images.
