### ISSUE TITLE
Fixed toolbar cannot be seen on widths under 458px 

### ISSUE THREAD

**Issue by IonutQo2** [xdan/jodit#247]
**Jodit Version:**  Latest, you can test it here: https://xdsoft.net/jodit/play.html

**Browser:**  Chrome
**OS:**  Windows

![image](https://user-images.githubusercontent.com/8812334/63463006-dcb2f480-c464-11e9-867c-c2da681fb82f.png)

**Expected behavior:**
The toolbar should show on lower mobile resolutions and should remain fixed/position absolute

**Actual behavior:**
The toolbar snaps to top if the width is under 458px

**Comment by xdan** [comment]
There is options for disable this behaviour https://xdsoft.net/jodit/doc/options/toolbarDisableStickyForMobile/
