### ISSUE TITLE
How to make custom fontsize?

### ISSUE THREAD

**Issue by ghost** [xdan/jodit#249]
**Jodit React Version:**  ^1.0.26

**Browser:**  Chrome/IE/Safary/FF
**OS:**  Windows/Mac/Linux

**Code**

```js
name: 'font size',
icon: 'fontsize',
command: 'fontSize',
list: [
      '14',
      '16',
      '18',
      '20',
],
template: (editor, key, value) => value,
```

**Expected behavior:**
selected fontsize has class name jodit_active
**Actual behavior:**
selected fontsize does not has class name jodit_active

**Comment by ghost** [comment]
i have found the solution for ES6 (REACT js)
```
{
    name: 'font size',
    icon: 'fontsize',
    command: 'fontSize',
    list: [
      '14',
      '16',
      '18',
      '20',
    ],
    template: (editor, key, value) => value,
    tooltip: 'Font size',
    isActiveChild: (editor, control) => {
      const fontSize = editor.selection.getHTML().match(/font-size: (\w+);/) || ['font-size: 14px', '14px'];

      return `${control.args[1]}px` === fontSize[1];
    },
  }
```

perhaps its can help you all

**Comment by juanmagdaleno** [comment]
Hi, I did custom fontsize from: jodit jodit-react 

 
 
![JODIT, fontsize](https://user-images.githubusercontent.com/8212559/180629314-269a3dfb-f54b-437e-b4bb-8900d904706e.PNG)

https://xdsoft.net/jodit/pro/docs/how-to/add-custom-font-family.md
