### ISSUE TITLE
Is there an event for removing image?

### ISSUE THREAD

**Issue by hoop22** [xdan/jodit#251]
**Jodit Version:**  3.2.55

**Browser:**  Chrome
**OS:**  Windows
**Code**

Hi, xdan. jodit is really a cool rich editor and full packed. I'm just wondering if there is an event for removing image. For example, there is an image in the text area, and now I delete the image, which just got deleted from frontend. I need an event when the image got deleted for telling the backend to remove the image where it actually stored.

Any suggestions are pretty appreciated.

**Expected behavior:**

**Actual behavior:**

**Comment by xdan** [comment]
Example you can find here https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#3314
