### ISSUE TITLE
Shows all buttons when zooms in 

### ISSUE THREAD

**Issue by jijishthomas** [xdan/jodit#253]
**Jodit Version:**  3.1.39

**Browser:**  Chrome/IE/Safary/FF 
**OS:**   Windows/Mac/Linux 

**Code**

```var editor = new Jodit(
		'#objectives',
		{
			"toolbarSticky" : false,
			"buttons" : "bold,italic,underline,|,strikethrough,source,superscript,subscript,ul,ol,fontsize,paragraph,align,hr",
			"disablePlugins" : 'paste',
		});
```

**Expected behavior:** show only buttons listed

**Actual behavior:** shows all buttons when zoomed in

**Comment by Dahmer49** [comment]
See #119
