### ISSUE TITLE
single toolbar for many editable area

### ISSUE THREAD

**Issue by romarioliveira25** [xdan/jodit#258]
**Jodit Version:**  3.2.46

**Question**
Has any way to use a single toolbar to control many editable areas?
Like this question: https://stackoverflow.com/questions/57465949/can-i-edit-multiple-textareas-and-div-elements-with-a-single-jodit-toolbar-like

**Comment by romarioliveira25** [comment]
hello?

**Comment by xdan** [comment]
Duplicate of #244 
Added in https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#3314
