### ISSUE TITLE
Steps in getting started do not seem to work?

### ISSUE THREAD

**Issue by JwanKhalaf** [xdan/jodit#259]
I am following the steps in your [Getting Started guide](https://xdsoft.net/jodit/start.html). But I get the following error:

![image](https://user-images.githubusercontent.com/42877376/65249473-f5f2a380-daeb-11e9-895d-db6da1b30b2a.png)

Here is the error as text (for searchability):

> Error: Element #editor should be a string or HTMLElement instance.

I think the getting started guide needs updating.

**Comment by JwanKhalaf** [comment]
They don't, the usage bit is wrong. It should be:

```html
<div id="editor"></div>
<script>var editor = new Jodit(document.getElementById('editor'));</script>
```

**Comment by xdan** [comment]
> They don't, the usage bit is wrong. It should be:
> 
> ```
> <div id="editor"></div>
> <script>var editor = new Jodit(document.getElementById('editor'));</script>
> ```
Hi
```html
<script>var editor = new Jodit(document.getElementById('editor'));</script>
```
equals
```html
<script>var editor = new Jodit('#editor');</script>
```
