### ISSUE TITLE
Destroy Editor Method

### ISSUE THREAD

**Issue by grrowley** [xdan/jodit#260]
**Jodit Version:**  3.2.46

**Browser:**  Global
**OS:**  Global

**Code**

```js
let jodit
let $editor = $('.editor')
let markup = $editor.innerHtml

$editor.addEventListener('dblclick', (e) => {
    e.preventDefault();
    jodit = new Jodit($editor, { autofocus: true })
})

document.addEventListener('click', (e) => {
    if (jodit && !jodit.container.contains(e.target)) {
        const content = jodit.value
       http.post('/content/endpoint', { uid: $editor.data('uid'), content })
              .then(() => jodit.destroy());
    }
})
```

**Expected behavior:**
So hopefully you can tell this is an interesting use case. I am making inline editors for certain elements of my website for admins when logged in. I found old documentation that referenced a destory method, but I am only ever getting destroy is not a valid method. So nothing needs to be tailored to my usage but it would be nice to have a functioning destroy method. Currently my work around is (again on document click thats not inside jodit)
```
jodit.container.parentElement.removeChild(jodit.container)
$editor.style.display = ''
```

**Actual behavior:**
```
jodit.destroy is not a function
```

PS. this was all hard coded and just 30,000 foot view of what I am doing so please excuse any typos or syntax issues, I have a working solution but I would prefer a destroy method mentioned here https://xdsoft.net/jodit/v.2/doc/module-Jodit.html but in the latest version. Love your plugin if you don't fix this I won't be heart broken all love thanks for sharing :)

**Comment by xdan** [comment]
Use documentation for Jodit 3 https://xdsoft.net/jodit/doc/methods/Jodit-destruct/
```
http.post('/content/endpoint', { uid: $editor.data('uid'), content })
              .then(() => jodit.destruct());
```
