### ISSUE TITLE
editor is not defined when using in Aurelia FrameWork

### ISSUE THREAD

**Issue by maamirh** [xdan/jodit#273]
I am implementing Jodit Editor In my Aurelia Framework application but i am getting error of property "Editor" undefined .

App.ts

var Jodit = require('jodit');
export class Wysiwyg {
  public editor;
  private content: any;
  constructor() {
    // this.content = 'Hello World!';

  }
  attached() {
    let __this=this;
    debugger;
    let item = $(".editor");
    console.log("Editor Instance", item);
      $('.editor').each(function () {
        let editor = new Jodit(item);
        console.log("Jodit instance", item);
       editor.value = '<p>start</p>';
      });
    };
  }
}
[
![1](https://user-images.githubusercontent.com/46965638/67201272-60666e80-f41f-11e9-97b9-907a623ad46a.png)
![2](https://user-images.githubusercontent.com/46965638/67201274-60666e80-f41f-11e9-9247-9cff87f1e6ff.png)

](url)

**Comment by gp-slick-coder** [comment]
`import { Jodit } from 'jodit'`

**Comment by maamirh** [comment]
I am using Aurelia Framework
import { Jodit } from 'jodit' was not working in my side .

I used this and it solve my problem 
import 'jodit/build/jodit.min.css';
const **wyswyg** = require('jodit');

attached(){

this.editor = new **wyswyg**.Jodit("#editor", {
}
}
