### ISSUE TITLE
Show only custom icons

### ISSUE THREAD

**Issue by elshobokshy** [xdan/jodit#283]
Is it possible to only show only the icons we need. If for example we'd need to remove "Insert Image" button or "Insert video" button, what should we do?

I'm using the CDN import to get Jodit to work with an initialization like so : 

`var editor = new Jodit(document.getElementById('jodit'));`

Can I add a parametre array to the Jodit class that takes options in that array?

**Comment by xdan** [comment]
https://xdsoft.net/jodit/play.html?toolbarAdaptive=false&disablePlugins=mobile&buttons=%2C%2C%7C%2C%7C%2C%7C%2C%7C%2C%2C%7C%2C%7C&currentTab=Buttons
Hi

**Comment by elshobokshy** [comment]
Nice, thank you!
