### ISSUE TITLE
More button on toolbar showing before custom buttons

### ISSUE THREAD

**Issue by bhujoshi** [xdan/jodit#287]
**Jodit Version:**  v3.2.55

I have added a custom button in Editor and i noticed more button on the toolbar is showing before the custom button  

![screenshot-fb1-authors mypat in-2019 11 20-12_42_51](https://user-images.githubusercontent.com/9627563/69217032-9ec48a00-0b93-11ea-9166-162475587471.jpg)

**Expected behavior:**
More button should display at the end 
**Actual behavior:**
More button on toolbar showing before custom buttons

**Comment by xdan** [comment]
ExtraButtons always append in the end for all resolutions
You can use controls 
https://github.com/xdan/jodit/blob/master/test/tests/toolbarTest.js#L42
or simple custom button
https://github.com/xdan/jodit/blob/master/test/tests/toolbarTest.js#L3

**Comment by bhujoshi** [comment]
@xdan Yes I Agree on Custom button always appended at the end. But the problem is
the custom button not going inside more buttons. Have a look on the screenshot  
Custom button outside is ok but I think more button option needs to go at the end.

![screenshot-localhost_3000-2019 11 20-18_02_46 (1)](https://user-images.githubusercontent.com/9627563/69240824-558c2e80-0bc3-11ea-8d59-6c200f9539b3.png)

I understand this will require some work to get the custom button inside the more button when the container does not fit all the buttons I can take up this work if you wish.

**Comment by xdan** [comment]
@bhujoshi 
Use controls for this case
You can use controls
https://github.com/xdan/jodit/blob/master/test/tests/toolbarTest.js#L42
It will work

**Comment by bhujoshi** [comment]
@xdan Thanks its working
