### ISSUE TITLE
No paste toolbar button (or copy) ?

### ISSUE THREAD

**Issue by JMWC2019** [xdan/jodit#289]
There doesn't appear to be a paste or copy toolbar button.

The playground doesn't have one either.

https://xdsoft.net/jodit/play.html

Seems like an obvious missing feature?

**Comment by JMWC2019** [comment]
@xdan any suggestions about how to implement paste, I found `editor.execCommand('copy')` however paste doesn't work, not sure why.

Seems odd to have cut and not copy and paste by default.

Thanks for this repo.

**Comment by JMWC2019** [comment]
I can't see mention of Paste in the PR ??

**Comment by xdan** [comment]
@JMWC2019 In the new version added copy and paste buttons
