### ISSUE TITLE
Double click on link in editor shows the link

### ISSUE THREAD

**Issue by JMWC2019** [xdan/jodit#291]
Once you have added a link in the editor, if you then double click on it the link is shown in the same tab.

**Jodit Version:**  3.2.65

**Browser:**  Chrome
**OS:**  Windows
**Expected behavior:**
Link should not be accessible in the editor.

**Actual behavior:**
Double clicking the link show the link in the current tab

**Comment by xdan** [comment]
Hi it is feature https://xdsoft.net/jodit/doc/options/link/
set ```
Jodit.make('#editor', {link: {followOnDblClick: false}})
```
