### ISSUE TITLE
Add a link to an image, removes the image

### ISSUE THREAD

**Issue by JMWC2019** [xdan/jodit#292]
When you add an image, then click the link button, the image is removed or the anchor tag is set before the image.

I now you can add a link when you edit the image, but this isn't obvious.

**Jodit Version:**  3.2.62

**Browser:**  Chrome
**OS:**  Windows

**Expected behavior:**
Link should be added correctly.

**Actual behavior:**
Link broken.

**Comment by NitinThopate** [comment]
<a href="https://github.com/"><img src="https://miro.medium.com/max/1708/1*mtsk3fQ_BRemFidhkel3dA.png"/></a>
[test.txt](https://github.com/xdan/jodit/files/4175598/test.txt)
