### ISSUE TITLE
insertImageAsBase64URI inserts as anchor

### ISSUE THREAD

**Issue by Scaenicus** [xdan/jodit#293]
**Jodit Version:**  3.2.65 via [jodit-vue](https://github.com/WendellAdriel/jodit-vue) 2.0.0

**Browser:**  Chrome Version 78.0.3904.87 (Official Build) (32-bit) (also tested in incognito mode with disabled expansions)
**OS:**  Windows 10

**Code**

```html
<jodit-vue v-model="html_content" :config="{"uploader": { "insertImageAsBase64URI": true } }"></jodit-vue>
```
```js

                "uploader": {
                    "insertImageAsBase64URI": true
                },
```

**Expected behavior:**
+ An uploaded image is converted to base64 and entered into the code as 
`<img src="data:image/png;base64,XXXXXXXXXX==" />`

**Actual behavior:**
+ An uploaded image is converted to base64 and entered into the code as 
`<a href="data:image/png;base64,XXXXXXXXXX==">data:image/png;base64,XXXXXXXXXX==</a>`
(i.e. as text and link-target)

This happens for me even in the most basic example when only setting uploader's insertImageAsBase64URI

I tried some "afterImage" and "defaultHandlerSuccess" functions from the examples, but failed (i.e. no image was uploaded then).

I also tried the webpack-changes mentioned in #157 but this already happens in development.

**Comment by Scaenicus** [comment]
My own temporary fix is to modify the content:
```js
    html_content = html_content.replace(/\<a href\=\"data\:image\/(.*)\"\>(.*)\<\/a\>/, '<img src="data:image/$1" />')
```

**Comment by Nice2Work** [comment]
I do have the same issue, using Quasar/VueJS. I was already looking into a quick fix but I think the developer(s) are better then me. However if they are looking for sponsors.....I am game. I do the same for the people from Quasar 😁👍

**Comment by Scaenicus** [comment]
@Nice2Work We tested our temporary fix yesterday, works without any issues. That said in our case only administrators/power users enter formatted text, so my users could tackle minor issues themselves without telling me.

```js
//InputHtml-component for using v-model to get the html-code.
    methods: {
        emitInput: function(new_value) {
            this.$emit('input', this.anchorToImage(new_value) || '')
        },
        anchorToImage: function(html_content) {
            if (null == html_content) {
                return null
            }
            html_content = html_content.replace(/\<a href\=\"data\:image\/(.*)\"\>(.*)\<\/a\>/, '<img src="data:image/$1" />')
            return html_content
        },
    },

```
