### ISSUE TITLE
Image properties - Delete tooltip not shown?

### ISSUE THREAD

**Issue by JMWC2019** [xdan/jodit#294]
I believe there's a tooltip for the delete trashcan on the image properties hover.
I've included an image where I've hovered over the word 'delete' in the dom.
However the tooltip doesn't show.

![image](https://user-images.githubusercontent.com/56313532/69623369-a9bb6680-103a-11ea-9aff-7976a178aade.png)

**Jodit Version:**  3.2.62

**Browser:**  Chrome
**OS:**  Windows

**Expected behavior:**
Tooltip should show

**Actual behavior:**
Tooltip doesn't show

**Comment by xdan** [comment]
Button was moved inside footer
