### ISSUE TITLE
Hovering over alignment button options, produces z-index related issue

### ISSUE THREAD

**Issue by JMWC2019** [xdan/jodit#296]
Select the alignment toolbar button and then hover over the option.
Notice that the tooltip appears inside the dropdown.

![image](https://user-images.githubusercontent.com/56313532/69640906-18a6b880-1057-11ea-9551-c9f6f516db86.png)

**Jodit Version:**  3.2.62

**Browser:**  Chrome
**OS:**  Windows

**Expected behavior:**
There shouldn't be a tooltip on the alignment options.

**Actual behavior:**
Tooltip shown on dropdown alignment options.

**Comment by madigege** [comment]
![image](https://user-images.githubusercontent.com/34115295/70021874-1bf8f180-15cd-11ea-9b06-c16d80754bb5.png)

.jodit_toolbar_list > .jodit_toolbar li.jodit_toolbar_btn {
    display: block;
    cursor: pointer;
    white-space: nowrap;
    color: inherit;
    text-decoration: none;
    width: 90px;
    height: 54px;
    box-sizing: border-box;
    text-align: center;
  }

**Comment by madigege** [comment]
我审查了元素,发现是这个css导致的问题,这个是否会在后期修复呢?
![image](https://user-images.githubusercontent.com/34115295/70109494-08aa5c80-1687-11ea-9aa7-85c80b02974e.png)

**Comment by xdan** [comment]
Fixed in latest version
