### ISSUE TITLE
Not showing font size

### ISSUE THREAD

**Issue by bhujoshi** [xdan/jodit#299]
When pasting text from word file Jodit not showing font-size

![Screenshot from 2019-12-02 12-44-32](https://user-images.githubusercontent.com/9627563/69937832-c1df2a00-1501-11ea-8f6d-e8b666327d66.png)

**Jodit Version:**  3.2.65
**Browser:**  Chrome
**OS:**  Linux 

**Expected behavior:**
It should display font-size after text from word file

**Actual behavior:**
Not showing font-size on the text pasted from a word file

**Comment by xdan** [comment]
Show here Source html example @bhujoshi
