### ISSUE TITLE
Source Code style tags alter main website

### ISSUE THREAD

**Issue by itsmoirob** [xdan/jodit#301]
When entering style tags for general rules, or adding !important, it will modify the main website.

**Jodit Version:**  3.2.60

**Browser:**  FF & Chrome
**OS:**  Linux Mint

Example, go to https://xdsoft.net/jodit/play.html?currentTab=State chose Source Mode and paste in below code, will turn all text red.
```
<html>
    <style>
        * {
            color:red !important;
        }
    </style>
</html>
```

**Expected behavior:**

For Jodit to not alter all the text of my website.

**Actual behavior:**

will change the entire website, not just the jodit editor

**Comment by xdan** [comment]
Use iframe mode for this https://xdsoft.net/jodit/play.html?iframe=true
