### ISSUE TITLE
Uploader inserts images as links, when "insertImageAsBase64URI" mode used

### ISSUE THREAD

**Issue by StukalovSS** [xdan/jodit#302]
**Jodit Version:**  3.2.65

**Browser:**  Chrome, IE
**OS:**  Windows

**Expected behavior:**
When parametr "insertImageAsBase64URI" is enabled in config, images are inserted as "\<img\>"
**Actual behavior:**
When parametr "insertImageAsBase64URI" is enabled in config, images are inserted as links (\<a\>)

**Comment by xdan** [comment]
https://xdsoft.net/jodit/play.html?uploader%5BinsertImageAsBase64URI%5D=true in Chrome all works fine

**Comment by StukalovSS** [comment]
Yes, in v3.2.61 this option works correctly, but in latest version i see a simple link instead of an inserted picture. For example, [i inserted picture in v3.2.61](https://yadi.sk/i/ZU7hEoJcpMKBjA) and [i inserted picture in v3.2.65](https://yadi.sk/i/SMLHcXo_UCOrXw) (i dont know how to attach puctures here in another way)
My config:
`   {
                iframe: true,
		language: 'ru',
		minHeight: 600,
		askBeforePasteFromWord: false,
                askBeforePasteHTML :  false,
                defaultActionOnPaste: "insert_as_html",
		disablePlugins: 'symbols,xpath,placeholder',
                uploader: {
			insertImageAsBase64URI: true
		},
		showXPathInStatusbar: false,
		toolbarAdaptive: false,
                buttons: "..."
}`
Perhaps this should be the case in new versions, but it seemed to me that this was a bug

**Comment by StukalovSS** [comment]
I think, I can close this issue. In the latest version (3.3.2) this function works fine.

**Comment by Nice2Work** [comment]
I can confirm that it is working now, I was already working on my own uploader, and I learned a lot by doing so, but yours works great now. Tested it locally and online, with screenshots, PNG and JPG and all are now inserting the proper way.
