### ISSUE TITLE
Example popup not working 

### ISSUE THREAD

**Issue by Nice2Work** [xdan/jodit#303]
On the demo page: https://xdsoft.net/jodit/examples/toolbar/custom_button.html

Is the demo about the popup, there is an error. It is not working. Most likely the error is very small and takes perhaps less than a minute to fix

The error I think is in here :  var text = editor.helper.trim(editor.editor.innerText);
and should be :  var text = editor.helper.trim(editor.innerText);

**Expected behavior:**
A popup showing 
Words and characters showing in a popup

**Actual behavior:**
Console.log showing error: 
custom_button.html:136 Uncaught TypeError: Cannot read property 'trim' of undefined
    at Object.popup (custom_button.html:136)
    at HTMLLIElement.a.onMouseDown (jodit.min.js?v=1522844281-3.2.61:9)
    at HTMLLIElement.f (jodit.min.js?v=1522844281-3.2.61:9)

**Comment by xdan** [comment]
Thank you! Fixed!
