### ISSUE TITLE
Outdated download link on website

### ISSUE THREAD

**Issue by redking00** [xdan/jodit#305]
**Jodit Version:**  Release 3.2.46

**Browser:**  ALL
**OS:**  ALL

Polyfills included in build/jodit.js supporting IE are not included in build/jodit.min.js

**Expected behavior:**
build/jodit.min.js is the minified/uglified version of build/jodit.js
**Actual behavior:**
build/jodit.min.js **is not just** the minified version of build/jodit.js, some code is discarded or innacesible.

**Comment by xdan** [comment]
build/jodit.es2018.min.js does not have polyfills
but build/jodit.min.js has

**Comment by redking00** [comment]
Sorry, talking about version 3.2.46 (latest release, link from website)

**Comment by xdan** [comment]
Fixed thank you https://github.com/xdan/jodit/releases/latest

**Comment by redking00** [comment]
Thank you, really nice work!
