### ISSUE TITLE
Compile issues with the new CSS file

### ISSUE THREAD

**Issue by Nice2Work** [xdan/jodit#315]
**Jodit Version:**  3.3.13

**Comment by Nice2Work** [comment]
Good morning, why was this closed without a comment? I was hoping it was fixed and tried the yarn upgrade again but still the error exists, please advise, thanks. 

client?f1f8:126 [WDS] Warnings while compiling.
warnings @ client?f1f8:126
eval @ socket.js?e29c:47
sock.onmessage @ SockJSClient.js?0a33:63
EventTarget.dispatchEvent @ sockjs.js?9be2:170
eval @ sockjs.js?9be2:888
SockJS._transportMessage @ sockjs.js?9be2:886
EventEmitter.emit @ sockjs.js?9be2:86
WebSocketTransport.ws.onmessage @ sockjs.js?9be2:2962
client?f1f8:135 ./node_modules/jodit/build/jodit.min.css?2 (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-2-1!./node_modules/postcss-loader/src??ref--5-oneOf-2-2!./node_modules/jodit/build/jodit.min.css?2)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(9:42679) start value has mixed support, consider using flex-start instead

**Comment by xdan** [comment]
Hi @Nice2Work this issue was closed because it has not any content. Fixed start -> flex-start. Thank you!
