### ISSUE TITLE
Uncorrect tolltip position

### ISSUE THREAD

**Issue by StukalovSS** [xdan/jodit#316]
**Jodit Version:**  3.3.13

**Browser:**  Chrome, IE
**OS:** Windows

**Expected behavior:**
A tooltip appears near the cursor or button

**Actual behavior:**
Tooltip appears a ~two hundred pixels from the cursor, like this:
![tooltipError](https://user-images.githubusercontent.com/34316026/71849287-bffd1d80-30e2-11ea-8d37-9a7d5539c620.png)
It is look like editor calculates position relative to the window but applies it relative to the editor\`s container. You can see it in iFrame mode: https://xdsoft.net/jodit/play.html?iframe=true

**Comment by jsadzinski** [comment]
The same issue here, but I don't event created jodit on a page, and a tooltip just shows up on random page.
