### ISSUE TITLE
Text style is reset when going to a new line

### ISSUE THREAD

**Issue by StukalovSS** [xdan/jodit#323]
**Jodit Version:**  3.3.17

**Browser:**  Chrome, IE
**OS:**  Windows

**Expected behavior:**
The editor keeps text style when going to a new line by pressing "Enter" key

**Actual behavior:**
When i press the "enter" key, text style is reset. I know, the editor have "br as enter" property, but this is not what I need, because it`s work like "Shift + Enter" combination :( 
Maybe, there is another property that will help solve this problem, but I did not find anything else

**Comment by xdan** [comment]
Fixed in 3.3.18 version
