### ISSUE TITLE
Paint Format

### ISSUE THREAD

**Issue by instocky** [xdan/jodit#326]
**Jodit Version:**  3.2.xxxxx

**Browser:**   Chrome
**OS:**  Windows

Как работает кнопка **Paint Format**? http://prntscr.com/qr6teo
выделил фрагмент с нужным форматом / нажал на кнопку / выделил новый фрагмет - ничего(

что делаю не так?

**Comment by xdan** [comment]
English please. Try in new version. Should be fixed.
