### ISSUE TITLE
getEditorText() was silently removed

### ISSUE THREAD

**Issue by JaspervdK** [xdan/jodit#330]
**Jodit Version:**  3.3.17

**Browser:**  Chrome
**OS:**  Linux

**Code**

```js
var plain_text_body = jodit.getEditorText();
```
Throws
```
TypeError: joditInstance.getEditorText is not a function
```
**Expected behavior:**
For the docs or changelog file to mention the functionality was moved to `var plain_text_body =  jodit.text;`
**Actual behavior:**
Had to dive into the file changes locally

**Comment by xdan** [comment]
Sorry, return and mark as deprecated
