### ISSUE TITLE
Incorrect selection when creating a link

### ISSUE THREAD

**Issue by dexster** [xdan/jodit#331]
**Jodit Version:**  3.3.17

**Browser:**  Chrome/FF
**OS:**  Mac

**Code**

**Expected behavior:**
Selecting text and then clicking the link icon should show the selected text in the text input field. 

**Actual behavior:**
It shows the full text element on the first click and then nothing on the second click

In link.ts this code shown below sets the input value to the current text element and then sets current to false.
After that it does not set the input properly to the selected text in the last else statement

```js
if (!isImageContent && current) {
	content_input.value = current.textContent || '';
}

if (current && Dom.closest(current, 'A', editor.editor)) {
	current = Dom.closest(current, 'A', editor.editor) as HTMLElement;
} else {
	current = false;
}

if (current) {
...
} else {
    Dom.hide(unlink);
}
```
Previous versions of link.ts (3.3.2) do not initially set the input value to the text content before setting current to false. They also do set the input value to the selected text in the last else statement   
```
if (current) {
...
} else {
    ....
    val(form, 'input[name=text]', sel ? sel.toString() : '');
    ....
}
```

This could possibly be the same issue affecting others eg #189

**Comment by xdan** [comment]
Fixed in 3.3.18
