### ISSUE TITLE
Custom link popup.

### ISSUE THREAD

**Issue by HarishSha** [xdan/jodit#333]
Is there any way to change popup view when clicking on the `link` button in Jodit Editor. I want to add `labels`, change styling and change placeholders as well.

I want to change original link popup to something like below

![image](https://user-images.githubusercontent.com/19326727/73524548-5cd97f00-4433-11ea-8968-9a9575ec67ad.png)

**Comment by xdan** [comment]
Added options for template and class https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#3319

**Comment by HarishSha** [comment]
Thanks for the update :)

**Comment by dev-Ab-r** [comment]
can you please tell me how to remove classname  label and input from link pop up ?

**Comment by dev-Ab-r** [comment]
> Is there any way to change popup view when clicking on the `link` button in Jodit Editor. I want to add `labels`, change styling and change placeholders as well.
> 
> I want to change original link popup to something like below
> 
> ![image](https://user-images.githubusercontent.com/19326727/73524548-5cd97f00-4433-11ea-8968-9a9575ec67ad.png)

can you please tell how you have customised the link pop up ? did not find anything in the docs

**Comment by sashazernin** [comment]
> can you please tell how you have customised the link pop up ? did not find anything in the docs

can you please tell how you have customised the link pop up ? did not find anything in the docs

**Comment by sashazernin** [comment]
> Is there any way to change popup view when clicking on the `link` button in Jodit Editor. I want to add `labels`, change styling and change placeholders as well.
> 
> I want to change original link popup to something like below
> 
> ![image](https://user-images.githubusercontent.com/19326727/73524548-5cd97f00-4433-11ea-8968-9a9575ec67ad.png)

can you please tell how you have customised the link pop up ? did not find anything in the docs
