### ISSUE TITLE
Edit link not working.

### ISSUE THREAD

**Issue by HarishSha** [xdan/jodit#335]
Problem 1: After adding a link, click on the added link. A popup will be opened.
In that popup clicking edit link(pencil icon), the form pops up. Now I'm not able to input anything in input boxes inside that popup. Its getting closed when I click on it. 

Problem 2: Edit link won't work if the link is added without any text. 

[Example](https://xdsoft.net/jodit/play.html)

**Comment by xdan** [comment]
What is your browser and OS?

**Comment by HarishSha** [comment]
Browser : Chrome Version 81.0.4044.4 (Official Build) canary (64-bit)
OS: MacOS Mojava

The below-attached file is screen recording for your reference. 
[error.mov.zip](https://github.com/xdan/jodit/files/4163565/error.mov.zip)

**Comment by xdan** [comment]
Fixed in 3.3.21

**Comment by GuneApp** [comment]
The same issue or similar is back on last version 3.4.25.  When I try to insert a link, the form pops up but cant' write in the input boxes, they seem to be disabled or similar.

**Comment by serendipity-coding** [comment]
Hello, having same prob with the hypertext, i have the popup but i can't write in the zone text

**Comment by jamesjieye** [comment]
I had the same problem with link in bootstrap's modal. Need to remove tabindex="-1" to make it work.

Browser: Version 101.0.4951.54 (Official Build) (x86_64)
OS: MacOS Monterey 12.3.1
Jodit Version: 3.18.2
Bootstrap Version: 4.6.1

Fix source: https://stackoverflow.com/a/66047091/149487

**Comment by morgrowe** [comment]
I'm having the same problem as @jamesjieye. Removing `tabindex="-1"` from Boostrap's modal fixes the issue, but now users can tab outside of the modal.

Is there a way of addressing the issue within Jodit?

**Comment by morgrowe** [comment]
Maybe an option to add the `.jodit-popup-container` underneath the main `.jodit-container` element?

![image](https://user-images.githubusercontent.com/4726315/170256050-ad196ad2-dec2-4386-b179-3243a23105b8.png)

**Comment by jpfluger** [comment]
As an FYI for bootstrap 5.2.3, flipping the configurable `focus` option to `false` solved the problem of the Modal dialog overriding Jodit input events. [Reference](https://getbootstrap.com/docs/5.2/components/modal/#options). It didn't matter or not if `tabindex` was used.
