### ISSUE TITLE
How to remove the Edit Link(pencil) icon?

### ISSUE THREAD

**Issue by HarishSha** [xdan/jodit#337]
How to remove the Edit Link(pencil) icon?
![image](https://user-images.githubusercontent.com/19326727/73826904-9a1f8180-4824-11ea-8928-4dc98a89704f.png)

I've tried `removeButtons: ["brush", "pencil"]`. With this, I'm able to remove the brush icon but the pencil icon is still there.

**Comment by xdan** [comment]
Hi, you can redefine [`popup.a`](https://xdsoft.net/jodit/doc/options/popup/) option
```js
var editor = new Jodit('#editor', {
   	popup: {
             a: Jodit.Array(Jodit.defaultOptions.popup.a.filter(b => b.icon !== 'pencil'))
       }
})
```

**Comment by HarishSha** [comment]
Thanks for the solution.
