### ISSUE TITLE
Link color formatting does not work

### ISSUE THREAD

**Issue by crowmw** [xdan/jodit#338]
**Jodit Version:**  3.3.19

**Browser:**  Chrome
**OS:**  Windows

**Expected behavior:**
Correct formatting of the links font color.

**Actual behavior:**
When you have HTML code in the editor like:
```html
Test text 
<a href="#">
 <span>LINK</span>
</a> 
test text end
```
Select everything and choose a font color. The link colour will not change and will remain the standard blue and sometimes part of the text before the link will not be colored either.

**Comment by xdan** [comment]
May be you have !important somewhere one your site?

**Comment by crowmw** [comment]
```html
Test text 
<a href="#" style="color: green">
 <span>LINK</span>
</a> 
test text end
```
No, the problem is that the formatting is only applied to <span> inside <a> and not to <a> itself. Then formatted code looks like
```html
<span style="color: red">Test text </span>
<a href="#" style="color: green">
 <span style="color: red">LINK</span>
</a> 
<span style="color: red"> test text end</span>
```

**Comment by xdan** [comment]
But you have special brush inside popup menu 
![image](https://user-images.githubusercontent.com/794318/74035866-2f10af00-49cc-11ea-96ef-b087c3f25d20.png)
