### ISSUE TITLE
Full size and image properties/resize

### ISSUE THREAD

**Issue by TrendyTim** [xdan/jodit#34]
**Jodit Version:**  3.1.81

Using the example.default.html

If i insert an image (http://google.com/google.jpg) when full size mode is active, i do not get resize handles or the image tool popup, but if i switch back to non full size mode it works as expected.

**Comment by xdan** [comment]
Hi, already fixed https://github.com/xdan/jodit/commit/ae39c4ce0b91523043a5a38a57738c669397f214

**Comment by TrendyTim** [comment]
Awsome.

Sorry I thought i had the latest version, github doesn't show 3.1.83 on the main releases page.

Thanks

**Comment by TrendyTim** [comment]
Just a quick follow up it does work now but only the first time, once the edit dialog is opened, the tool bar doesn't show again and also the full size toggle stops working (the last one is less of an issue for me at the moment, as i want it always full size anyway but thought id mention it anyway).

**Comment by TrendyTim** [comment]
Wow i am very impressed with how quickly you fixed that one, works great thank you, i found one last one i think but ill create a new ticket for that

**Comment by banban0921** [comment]
Hi,I have got the same issues by latest veresion(V 3.2.10).
