### ISSUE TITLE
Feature request - Ability to set editor size using calc

### ISSUE THREAD

**Issue by vanillamasonry** [xdan/jodit#344]
Feature request - Ability to set editor size using calc 
ex: 
var re_component = new Jodit("#rich_editor", {
			height:calc(100% - 20px),
			  spellcheck: false,
			  showCharsCounter: false,
			  showWordsCounter: false,
.......

**Comment by xdan** [comment]
```js
var re_component = new Jodit("#rich_editor", {
height: 'calc(100% - 20px)',
spellcheck: false,
showCharsCounter: false,
showWordsCounter: false,
});
```
@vanillamasonry It is work in current version
