### ISSUE TITLE
some text auto comment

### ISSUE THREAD

**Issue by salahatwa** [xdan/jodit#345]
Jodit Version: 3.3.19

Browser: Chrome
OS: Linux,windows

some text auto comment when writing </anyTag> it's comment to 

Expected behavior:
1- when writing  </anyTag> it should be as it is .

Actual behavior:
when typing any text with '</ > ' 
1- some text auto comment when writing </anyTag> it's comment to

**Comment by salahatwa** [comment]
another example` <?xml version="1.0" encoding="UTF-8"?>`
it's commented to `<!--?xml version="1.0" encoding="UTF-8"?-->`

**Comment by xdan** [comment]
No, it is not so. Any another editor has same behaviour. WYSIWYG is about HTML, not XML

**Comment by salahatwa** [comment]
yes i know , but if i need to write sample text file with ace editor supported by jodit ,
why it's comment my text ?

**Comment by xdan** [comment]
@salahatwa It is not Jodit, contenteditable works so in all editors.
