### ISSUE TITLE
How to set buttons in preset inline mode?

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#348]
**Expected behavior:**
Being able to determine which buttons appear in inline mode

**Comment by xdan** [comment]
All buttons you can set as `popup` options https://xdsoft.net/jodit/doc/options/popup/
Where `key` is tag. But in inline mode Jodit has also empty text popup, and  for this case you can set 
`popup.selection` key. 
```js
Jodit.make('#editor', {
   preset: 'inline',
   popup: {
      selection: Jodit.Array(['bin'])
   }
});
```

**Comment by Fedeorlandau** [comment]
@xdan I'm trying to achieve the same. Determine which buttons appear on INLINE mode.
No matter what I add on the `selection` property, it always display more buttons.

```
Jodit.make('#editor', {
   preset: 'inline',
   popup: {
      selection: ["bold"]
   }
});
```

That example displays the bold button + 10 others.
