### ISSUE TITLE
Placeholder doesn't hide if start adding list

### ISSUE THREAD

**Issue by HarishSha** [xdan/jodit#352]
Without entering any text, try to add list from the toolbar. You will see placeholder colliding with  bullet(bullet list)/ number(order list). Link: https://xdsoft.net/jodit/

![image](https://user-images.githubusercontent.com/19326727/74837055-a76d5d80-5346-11ea-9f4f-11835c092eb3.png)
![image](https://user-images.githubusercontent.com/19326727/74837092-bbb15a80-5346-11ea-8315-c78969645c02.png)

**Comment by xdan** [comment]
Fixed in https://github.com/xdan/jodit/releases/tag/3.4.1
