### ISSUE TITLE
TypeError: "o is undefined" in Vue

### ISSUE THREAD

**Issue by gxkai** [xdan/jodit#355]
**Jodit Version:**  3.2.xxxxx

**Browser:**  
**OS:**  

**Code**

```js
// A *self-contained* demonstration of the problem follows...
 defaultHandlerSuccess(data) {
            this.selection.insertImage('/' + data.data.path);
 },
```

**Expected behavior:**

**Actual behavior:**
TypeError: "o is undefined" in Vue

**Comment by xdan** [comment]
Need more information about bug, Jodit has not official Vue plugin
