### ISSUE TITLE
Minified javascript does not work in Edge browser

### ISSUE THREAD

**Issue by beatle01** [xdan/jodit#356]
**Jodit Version:**  3.2.x (tested on .8 and .24)

**Browser:**  
**OS:**  

**Expected behavior:**
Jodit editor to load correctly

**Actual behavior:**
Original textarea remains visible

Error in console:
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
jodit.min.js (9,168990)

SCRIPT5009: SCRIPT5009: 'Jodit' is not defined
jodit.comments.js (1,1)

After some searching it seems that the minification introduces the error. When using the full blown script everything works fine.

**Comment by xdan** [comment]
I think this has been fixed. Check please, if no - reopen issue.
