### ISSUE TITLE
setEditorValue do not render content when defaultMode: Jodit.MODE_SOURCE

### ISSUE THREAD

**Issue by cemaprjl** [xdan/jodit#359]
**Jodit Version:**  v3.3.24
**Browser:**  Chrome
**OS:**  Windows

**Code**
```
joditEditor = new Jodit('.text_editor', {
defaultMode: Jodit.MODE_SOURCE,
});
var contentHtml = '<h1><span>Hello static page!</span></h1>
<div>
    hello world
    <div style="background-color: red; width : 500px; height : 400px;"></div>
</div>
<div>
</div>
<a href="google.com">goooooooooogle</a>';
joditEditor.setEditorValue(contentHtml);
```

**Expected behavior:**

Editor value must be shown in the editor

**Actual behavior:**

Editor is empty. but **joditEditor.value** equals to the setted **contentHtml**.
The same behavior if i'm using **joditEditor.value = contentHtml**

When MODE_SOURCE is turned off - its working perfect.

p.s the documentation https://xdsoft.net/jodit/doc/options/defaultMode/ says than the correct value for the source editor is MODE_AREA, but no reference found in jodit.min.js, And MODE_AREA is not working. Only MODE_SOURCE was found in .js source code. It looks like your documentation is deprecated or not actual

**Comment by dongnguyenvie** [comment]
i has same issue :(

**Comment by jridky** [comment]
I was able to use following workaround, but it's really ugly hack.

In configuration:
```
"events":
    {"afterInit": function (event){
                         setTimeout(function(){
                             event.jodit.toggleMode();
                          }, 200);
                      }
    }
```

**Comment by masbaehr** [comment]
This is a very annoying bug, spent a lot of time finding out this is the cause

**Comment by vanillamasonry** [comment]
Yes, is a bug. I also use an ugly hack based toggleMode after I load the script in the default mode.
Jodit code editor is based on ACE.

There is also another bug related to the code editor. When you will try to resize container that contain the ACE editor, the ACE editor will not resize (even if the background is remaining black). ACE editor must be notified and also resized

See the image:

![JODIT-ACE](https://user-images.githubusercontent.com/2625401/81457833-94e81080-914c-11ea-8f5a-9ba16e07e2e4.jpg)


Let's hope that next version will solve these bugs related to ACE integration
Thanks,

**Comment by vanillamasonry** [comment]
I have used with success ACE editor.resize(true) .
See also: https://github.com/ajaxorg/ace/issues/2797
Same problem here in Jodit
