### ISSUE TITLE
showBrowserColorPicker not working on safari and edge

### ISSUE THREAD

**Issue by huutrungdoan** [xdan/jodit#368]
**Jodit Version:**  3.2.xxxxx

**Browser:**  
**OS:**  

**Code**

```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**

**Actual behavior:**
i am setting in the code with pram showbrowsercolorpicker = true, but  color picker not show in safari and edge, please help me to check it. thank you so much. in internet exploere sometime working sometime not ... :(( 
![image](https://view.cheanhdong.com/uploads/anh-upload/1583840373374.png)

**Comment by xdan** [comment]
Enable `showBrowserColorPicker` - will show native browser color picker, but unfortunately, some browser does not support it. I will try to create a plugin for this but now you can attach some another color picker plugin.
For example something like this plugin https://narsenico.github.io/a-color-picker/
Added example for you https://xdan.github.io/jodit/examples/color-picker.html

**Comment by huutrungdoan** [comment]
thank you so much 😘

Vào Th 7, 20 thg 6, 2020 vào lúc 05:49 Valeriy Chupurnov <
notifications@github.com> đã viết:

**Comment by huutrungdoan** [comment]
but here i can not distinguish "color" or "background" tabs

Vào Th 5, 9 thg 7, 2020 vào lúc 16:29 Đoàn Hữu Trung <
huutrungdoan@gmail.com> đã viết:
