### ISSUE TITLE
Insert link doesn't trigger change event

### ISSUE THREAD

**Issue by xrado** [xdan/jodit#369]
**Jodit Version:**  3.3.24

**Browser:**  Chrome, probably in all
**OS:**  Mac

**Comment by vsubbotskyy** [comment]
When can we expect closest minor release with this fix? Thanks!

**Comment by vitaliishandra** [comment]
I suppose the issue is related to this one: https://github.com/xdan/jodit/issues/426

**Comment by vladimyr** [comment]
@xdan 3a966f7 introduced breaking change!
Changing the main module exports without incrementing the major version goes against [semver spec](https://semver.org). ⚠️
