### ISSUE TITLE
Inline mode buttons

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#38]
**Jodit Version:**  3.1.90

On Playground page Safari
and in Electron/chrome app

**Expected behavior:**
only show allowed buttons in inline mode

**Actual behavior:**
All buttons are shown in the context menu when switching to the inline mode, toolbar mode is fine

![jodit_bug5](https://user-images.githubusercontent.com/37185489/39338569-c6f64614-49c3-11e8-9851-5a0412f4e503.gif)

Furthermore on the playground page when deselecting buttons the code div shows "[object Object]" and not the selected buttons
var editor = new Jodit("#editor", {
  "buttons": "[object Object]"
});

**Comment by xdan** [comment]
If you use preset  - `inline` You should redefine `presets.inline.popup.selection` options
```javascript
var  editor = new Jodit('#editor', {
        preset: 'inline',
        presets: {
            inline: {
                popup: {
                    selection: Jodit.defaultOptions.buttons
                }
            }
        },
})
```

**Comment by xdan** [comment]
or without presets
```javascript
var  editor = new Jodit('#editor', {
            inline: true,
            toolbar: false,
            toolbarInline: true,
            popup: {
                selection: [
                    'bold',
                    'underline',
                    'italic',
                    'ul',
                    'ol',
                    'outdent',
                    'indent','\n',
                    'fontsize',
                    'brush',
                    'paragraph',
                    'link',
                    'align',
                    'cut',
                    'dots',
                ]
            },
            showXPathInStatusbar: false,
            showCharsCounter: false,
            showWordsCounter: false,
            showPlaceholder: false
})
```

**Comment by mdevDE** [comment]
Thank you for this, the last response solved the problem completely!
