### ISSUE TITLE
Custom config fontsize list problem

### ISSUE THREAD

**Issue by crowmw** [xdan/jodit#391]
**Jodit Version:**  3.3.24

**Browser:**  Chrome
**OS:**  Windows

**Code**

```js
const textArea = useRef()
const customConfig = {
  controls: {
    fontsize: {
      list: ['8', '10', '12', '14', '16', '24', '36', '48', '72']
    },
  }
}
textArea.current = new Jodit(textArea.current, customConfig)
```

**Expected behavior:**
Font size popover list should have only values declared in custom config
**Actual behavior:**
Font size popover list have values declared in custom config + default config values 
![image](https://user-images.githubusercontent.com/2963127/81912716-41077c80-95cf-11ea-910f-78d7a3892a29.png)

**Comment by xdan** [comment]
By default array will be merged. Use Jodit.Array for replacing:
```js
const textArea = useRef()
const customConfig = {
  controls: {
    fontsize: {
      list: Jodit.Array(['8', '10', '12', '14', '16', '24', '36', '48', '72'])
    },
  }
}
textArea.current = new Jodit(textArea.current, customConfig)
```

**Comment by crowmw** [comment]
@xdan Effect of using this solution:
![image](https://user-images.githubusercontent.com/2963127/82016106-8cc62e80-9680-11ea-96b2-df0c49fc56d0.png)
