### ISSUE TITLE
Pasting simple text with Ctrl+V inserts it at the beginning instead of current cursor position

### ISSUE THREAD

**Issue by antonioh** [xdan/jodit#396]
**Jodit Version:**  3.3.24

**Browser:**  FF
**OS:**  Windows

**Expected behavior:**
Pasting text with Ctrl+V should insert it at the cursor position.

**Actual behavior:**
Pasting text with Ctrl+V inserts it at the very beginning.

It happens also on the demo page: (https://xdsoft.net/jodit/) as shown in the attached gif where it can be seen how I:

1. Select text from the Editor
2. Position cursor on the next line
3. Press Ctrl+V and text is inserted at the very top instead of cursor position
4. Repeate copy, position cursor on nexte line and Ctrl+V -> Text is inserted again at the very top

![joditEditor-paste](https://user-images.githubusercontent.com/722865/82540518-7708ab80-9b4f-11ea-84a8-23b8268da9cd.gif)

**Comment by keithrz** [comment]
@xdan Thanks for the fix! Will there be a release for this fix soon?

**Comment by xdan** [comment]
@keithrz  Today!)
