### ISSUE TITLE
HTML properties are rewrite always to lowercase

### ISSUE THREAD

**Issue by florian-kittel** [xdan/jodit#397]
**Jodit Version:**  3.3.24

**Browser:**  All
**OS:** All

**Expected behavior:**
```js
// Example
<div myProperty="test">Test</div>

// ---

// or for detailed use cases
<my-button [routerLink]="['/dashboard']">to dashboard</my-button>
```

**Actual behavior:**
```js
// will become (convert to lower P)
<div myproperty="test">Test</div>

// ---

// will become (convert to lower L)
<my-button [routerlink]="['/dashboard']">to dashboard</my-button>
```

When using the code-tab and enter specific Code, the editor will rewrite all properties to lower case. I do not see any option to deactivate this. I guess it is made to clean up copy past from some sources, but in some use cases it will destroy the expected behavior.

**Comment by xdan** [comment]
It is normal HTML behaviour. All browsers works with lowercase. Try change any attribute on this page.

**Comment by florian-kittel** [comment]
We use Angular Syntax in it. It is not possible to change it. Is there an option to deactivate this "feature"?

**Comment by xdan** [comment]
You should use source editor for this
https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes
