### ISSUE TITLE
Can't to set different margins to image

### ISSUE THREAD

**Issue by sammael1106** [xdan/jodit#4]
Hi guys!
Thanks for your work. I'm trying out your product and going to buy a license, if it will be appropriate for my project.

I found a bug:
Press to edit image -> Advanced -> Unlock right/left/bottom margins -> fill it by different values (for example: 10px/20px/30px/40px) -> OK
I expected that image will have different margins, but it has only `margin: 10px;`. And the same in advanced settings :(

**Comment by xdan** [comment]
Hi, thank you again. Fixed in 3.0.36
Can i close this issue?
