### ISSUE TITLE
Inline Contextmenu Positioning

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#40]
**Jodit Version:**  3.1.90

Playground Safari
Electron/chrome app

**Expected behavior:**
After selecting the text the context menu should align with the mouse cursor

**Actual behavior:**
context menu is centered over the selected text

![jodit_bug7](https://user-images.githubusercontent.com/37185489/39340648-9299b746-49cf-11e8-9909-6d1042508da4.gif)

**Comment by xdan** [comment]
Hi, No it is normal behavior

**Comment by mdevDE** [comment]
Ok thank you for commenting.
