### ISSUE TITLE
Toolbar button active state not set / reset correctly

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#401]
<img width="795" alt="Bildschirmfoto 2020-05-29 um 16 38 50" src="https://user-images.githubusercontent.com/37185489/83272083-060a6900-a1cb-11ea-8f64-4e59820d735d.png">
<img width="793" alt="Bildschirmfoto 2020-05-29 um 16 39 20" src="https://user-images.githubusercontent.com/37185489/83272088-06a2ff80-a1cb-11ea-9ffe-1d4d8063ffe8.png">

**Jodit Version:**  3.3.24

**Expected behavior:**
Clicking a new toolbar btn will remove active from the previous clicked bin

**Actual behavior:**
Multiple active states as shown in the pictures

**Comment by xdan** [comment]
It is normal behaviour. When text has custom style - matched button should be activated
