### ISSUE TITLE
Shadow Dom support

### ISSUE THREAD

**Issue by ghost** [xdan/jodit#404]
**Jodit Version:**  3.3.24

**Browser:**  Chrome
**OS:**  Mac/Linux

**Code**

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Jodit example in shadow DOM</title>
    <meta charset="UTF-8" />
  </head>

  <body>
    <div id="app"></div>

    <script src="src/index.js"></script>
  </body>
</html>
```
```js
// index.js
import Jodit from "jodit";

const app = document.getElementById("app");
app.attachShadow({ mode: "open" });
const root = app.shadowRoot;

root.innerHTML = `
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jodit/3.3.24/jodit.min.css"/>
<h1>Jodit example in Shadow DOM</h1>
<div id="editor">
</div>
`;

var editor = new Jodit(root.getElementById("editor"), {
  globalFullsize: false
});
editor.value = "<p>start</p>";
```
**CodeSandbox**: [https://codesandbox.io/s/immutable-dew-nqblx](https://codesandbox.io/s/immutable-dew-nqblx)

**Expected behavior:**

Support Jodit in Shadow DOM in major modern browsers.
Jodit does **almost** work in `shadowRoot`. It has couple issues. **Example 1**:

1. select text in editor
2. click B button
3. slected text is bold

**Example 2**:

1. add image into content
2. select image
3. tooltip with buttons is rendered to allow image alignment, etc.

**Actual behavior:**

**Example 1:**
When you try this in Chrome, actual result is: strong element is created before selected text.
It does work in Firefox. Probable cause is somewhere around getSelection().

**Example 2:**
Tooltip with buttons to work with images is not rendered. It because it's rendered to document root, not into shadow root, which could be achieved with simple solution like:
```js
const getTargetElement = element => {
  // place popup into shadowRoot if exists
    const host = element.getRootNode()
    if (host && host.host) {
      return host
    } else
      return document.getElementsByTagName('body')[0]
    }
}
```

**Description:**
I am using Jodit on project, where i had to add shadowRoot to avoid styling conflicts. Jodit is great and it does almost work, i would appreciate if it worked without issues there.

**Comment by xdan** [comment]
Fixed in https://github.com/xdan/jodit/releases/tag/3.4.1
