### ISSUE TITLE
the props 'useSearch' doesn't work

### ISSUE THREAD

**Issue by suqiuhui** [xdan/jodit#407]
**Jodit Version:**  3.3.24

**Browser:**  
**OS:**  

**Code**
The following code is mine, it doesn't work, the search modal aways show
```js
var jodit = new Jodit('#editor', {
useSearch: false
})
```
but this is ok
```js
 var jodit = new Jodit('#editor', {
 disablePlugins: 'search'
});
```

**Expected behavior:**

**Actual behavior:**

**Comment by xdan** [comment]
Try in https://github.com/xdan/jodit/releases/tag/3.4.1

**Comment by suqiuhui** [comment]
I am sorry for this questions, it dosen't work in my code, The version I'm using is 3.4.15
