### ISSUE TITLE
so many styles dose not work

### ISSUE THREAD

**Issue by suqiuhui** [xdan/jodit#408]
**Jodit Version:**  3.3.24

**Browser:**  
**OS:**  

this is `<h1>hello jodit!</h1>`
![image](https://user-images.githubusercontent.com/19644289/84481215-594ee200-acc8-11ea-9070-b4214be1ed94.png)

this is `<h2>hello jodit!</h2>`
![image](https://user-images.githubusercontent.com/19644289/84481618-ebef8100-acc8-11ea-99ca-c9ee86b264c3.png)

this is a `<pre>` demo in there： https://xdsoft.net/jodit/play.html

![image](https://user-images.githubusercontent.com/19644289/84481722-15101180-acc9-11ea-908e-c800011ebd2a.png)

and  many other styles does not work in my code, just becuase it links https://xdsoft.net/jodit/build/css/bundle.css?v=1522844281-3.3.24 ,
but so many styles is not in the file 'jodit/build/jodit.min.css'

and other way, you used the UIkit framework, but i didn't use,so i think it is a reason for this issue

**Expected behavior:**

**Actual behavior:**

**Comment by xdan** [comment]
@suqiuhui  H1 in https://xdsoft.net/jodit/
![image](https://user-images.githubusercontent.com/794318/84756278-40497800-afcb-11ea-8f21-470815f3a8a6.png)

Do you use my CSS from my site in your project?

**Comment by suqiuhui** [comment]
@xdan 

on the page of https://xdsoft.net/jodit/
![image](https://user-images.githubusercontent.com/19644289/84848572-ff626980-b085-11ea-8566-df86732a01c5.png)


on my page
![image](https://user-images.githubusercontent.com/19644289/84848250-67648000-b085-11ea-8df8-b7a8a14b2140.png)


I used the css like this
![image](https://user-images.githubusercontent.com/19644289/84847074-cf659700-b082-11ea-8fcb-ceb6a07ea2d8.png)


I think in https://xdsoft.net/jodit/  is ok, maybe it's because you used UIkit. many styles are in UIkit but not in your 'jodit/build/jodit.min.css'

**Comment by xdan** [comment]
Fixed in https://github.com/xdan/jodit/releases/tag/3.4.1

**Comment by suqiuhui** [comment]
I am sorry for this questions, it dosen't work in my code, The version I'm using is 3.4.15
