### ISSUE TITLE
Avoid to Load External Resources

### ISSUE THREAD

**Issue by victors1681** [xdan/jodit#412]
**Jodit Version:**  3.3.24
how to avoid load external resources and host those files locally?
I'm using the jodit on React
<img width="836" alt="image-2020-06-16-09-09-19-090" src="https://user-images.githubusercontent.com/11906852/85152425-fb1f8300-b222-11ea-83e9-5abb5efe2c2e.png">

**Comment by xdan** [comment]
Disable beautify https://xdsoft.net/jodit/doc/options/beautifyHTML/
And change sourceEditor to simple textarea https://xdsoft.net/jodit/doc/options/sourceEditor/
```js
var jodit = Jodit.make('#editor', {
beautifyHTML: false, sourceEditor: 'area'
})
```
