### ISSUE TITLE
copy pasting twitter or istagram or etc not as expected

### ISSUE THREAD

**Issue by adesm** [xdan/jodit#416]
**Jodit Version:**  3.2.xxxxx

**Browser:**  Chrome
**OS:**  Mac

**Code**

```js
// when I copy embeded code from twitter & instagram, then I paste using command (command + v). 
// Text editor show the dialog to choose pasting style. I choose keep as HTML

// no code. I'am using default config
```

**Expected behavior:**
when embed code was pasted, in the code editor mode, the html looks like
<img width="1287" alt="Screen Shot 2020-06-23 at 13 30 11" src="https://user-images.githubusercontent.com/15310254/85368703-f2e28300-b555-11ea-8c03-8c4506a71460.png">
so in text editor mode, the result should be
<img width="921" alt="Screen Shot 2020-06-23 at 13 33 29" src="https://user-images.githubusercontent.com/15310254/85368854-3806b500-b556-11ea-9c52-ddc668690cef.png">
**Actual behavior:**
source code mode
<img width="1264" alt="Screen Shot 2020-06-23 at 13 30 02" src="https://user-images.githubusercontent.com/15310254/85368759-0e4d8e00-b556-11ea-9f3e-71fac832a5bf.png">
text editor mode
<img width="1390" alt="Screen Shot 2020-06-23 at 13 29 53" src="https://user-images.githubusercontent.com/15310254/85368848-32a96a80-b556-11ea-88c8-c0331a7cf581.png">

What is the problem? how to prevent adding <meta... and escaping that HTML when copy pasting an HTML text (embeded code)?

Im using Jodit-Vue and already asked to the author https://github.com/WendellAdriel/jodit-vue/issues/11

**Comment by xdan** [comment]
Twitter gives that HTML fragment:
![image](https://user-images.githubusercontent.com/794318/86542240-918abe80-bf1c-11ea-9c43-0586d962b108.png)
And I can not change this behavior. You can use the usual pasting from textarea.
![image](https://user-images.githubusercontent.com/794318/86542194-3789f900-bf1c-11ea-9741-ff9a1a313271.png)

**Comment by NandoMB** [comment]
There is a way to not parse '&' to '&amp;' after the user paste a code into editor? I'm parsing all base64 inside href and src properties, uploading it and replacing the base64 data to the link of reference, but...
When there are one or many & used to concatenate url params, the problem happens...

The code should be like this:
```html
<embed type="image/jpeg" width="300" height="470" src="http://docs.google.com/gview?url=https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf&embedded=true"></embed>
```

But the editor is sanitizing the '&' character, like this:
```html
<embed type="image/jpeg" width="300" height="470" src="http://docs.google.com/gview?url=https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf&amp;embedded=true"></embed>
```
