### ISSUE TITLE
Changing mode from code view to non-code view adds extra linebreak

### ISSUE THREAD

**Issue by voc0der** [xdan/jodit#418]
**Jodit Version:**  3.4.6
This didn't happen with 3.3.24

Steps to reproduce on Jodit playground:
1) Place cursor at the end of the text. (after verbis.)
2) Change mode to enter code view.
3) Change mode again to enter non-code  (here you'll see the problem) 
4) If you enter code view, the code is of the problem is there

**Expected behavior:**
Changing mode from code view to regular view should not change anything unless the code itself changes.

**Actual behavior:**
If you go from code view to regular view, it adds a ``<p><br></p>`` and if you keep toggling change mode, it, it'll keep adding them.

**Comment by voc0der** [comment]
I found something that may help you with the issue

I noticed that on Jodit.prototype.setCurrentPlace = function (place) {

the 'place' object being passed in switches from having an .element having no paragraph node, to having the ``<p>\n</p>`` one a blank one from the 1st to 2nd pass, so somewhere there it might be getting tripped up; e.g. if this.currentPlace === place is supposed to return out, it may not be.

Thanks for any help.

**Comment by xdan** [comment]
You can disable this behavior https://xdsoft.net/jodit/play.html?disablePlugins=wraptextnodes&currentTab=Plugins

**Comment by voc0der** [comment]
Thanks for that; I didn't know about that particular plugin or realized the intent of its design. Unfortunately in my use-case that won't be an option, because I would like the ``<p>`` tags to appear if they're valid and missing, e.g. if you ctrl+a->delete-> type ``Hello World`` you get that literally, and ``<p>Hello World!</p>``, is necessary, so the wrapping plugin is very useful.

I think there's might be a few issues anyways with the plugin enabled unless I'm still misunderstanding the intent.

With the plugin enabled, if you go to the Jodit playground and click on elements that aren't wrapped by a ``<p>``, then keep clicking "Change Mode" over and over, then look at the result after a few times, you'll notice that sometimes it just writes an extra ``<p><br></p>`` nowhere near the element you have selected, so it's not actually wrapping anything.  I guess it detects that it's already inside of a different tag (valid) and goes to the end instead. That seems like it might work for one use of that function, e.g if you double click an area or something to create a paragraph, but if you're only changing modes, it just feels like a bug.

Usually the extraneous paragraphs end up at the bottom, but sometimes it's at the top, if it's the starting position is 0. You can simply go into the playground, click "Change Mode" and then change back and see it's changing a node that it already starts with (``<p>``) into something else.

Here is a video of both of the described behaviors: https://thumbs.gfycat.com/FirstShockingBaboon-mobile.mp4

**Comment by voc0der** [comment]
Thanks for working on it; it has gotten better. But the problem I think still remains:

https://xdsoft.net/jodit/ doesn't have the issue. If you load page, click in and out of code view 10 times, nothing is added
https://xdsoft.net/jodit/play.html does have the issue. If you load the page click and out of code view 10 times, it adds a ton of random paragraphs at the end.

If I'm wrong about how this is supposed to work, please close the issue again, but it seems like a bug.

Thanks!
