### ISSUE TITLE
Change event is not working for combination  iframe: true, editHTMLDocumentMode: true

### ISSUE THREAD

**Issue by vitaliishandra** [xdan/jodit#426]
Jodit Version: 3.3.24

Browser: Chrome, probably in all
OS: Mac

Change event is not working then both options are enabled: iframe: true, editHTMLDocumentMode: true. Any workaround?

**Code**
                `var editorOptions = {
                    iframe: true,
                    editHTMLDocumentMode: true,
                };
                var editor = new jodit.Jodit(selector, editorOptions);
                editor.events.on('change', setText);`

**Expected behavior:**
Change event is triggered

**Actual behavior:**
Change event is not  triggered

**Comment by vsubbotskyy** [comment]
I was able to reproduce it after toggling into source mode and back.
[https://codepen.io/cent/pen/YzwORrV?editors=1111](https://codepen.io/cent/pen/YzwORrV?editors=1111)
Seems like somehow we lost event handlers

**Comment by vsubbotskyy** [comment]
It can be reproduced when calling `setEditorValue` after initialization as well. After further investigation I found out that iFrame contents (with all the event handlers) is cleared after `beforeSetNativeEditorValue` handler in the iframe plugin when we call [doc.open()](https://github.com/xdan/jodit/blob/4e104f23279b2736407bb5cd2c4acc7246562115/src/plugins/iframe.ts#L334). Seems like resubscribe to events is needed.
