### ISSUE TITLE
insert link overrides selected text with url

### ISSUE THREAD

**Issue by xrado** [xdan/jodit#427]
**Jodit Version:**  3.4.12  ..started in versions before

**Browser:**  Chrome/IE/Safary/FF
**OS:**  Mac  (Tested on mac only)

**Expected behavior:**
select text and inserting link, overrides selected text with entered url

**Actual behavior:**
the selected text should persist, with added link

**Comment by xdan** [comment]
It is normal behavior. If you want to replace selected text you should clear Text field
![image](https://user-images.githubusercontent.com/794318/86615911-c8fd7780-bfbd-11ea-87be-dd5a66f9dfdf.png)

**Comment by xrado** [comment]
no, the problem is that I want to add link to selected text in editor, but when I click insert selected text is overridden with url and selected text is gone. If the text is selected, the insert link form should prefill text input with selection.

**Comment by xrado** [comment]
![Screenshot 2020-07-09 14 24 50](https://user-images.githubusercontent.com/17779/87040073-7061f080-c1f0-11ea-974a-1b21a76a5bc3.png)
![Screenshot 2020-07-09 14 25 10](https://user-images.githubusercontent.com/17779/87040086-76f06800-c1f0-11ea-9b32-4522c17cf69d.png)
![Screenshot 2020-07-09 14 25 23](https://user-images.githubusercontent.com/17779/87040097-7a83ef00-c1f0-11ea-85e1-26d2b7a62c33.png)

**Comment by corrrso** [comment]
yup, it would be extremely handy if the selected text would automatically fill the "text" field
