### ISSUE TITLE
icons dont become active

### ISSUE THREAD

**Issue by psaruks** [xdan/jodit#428]
**Jodit Version:** 3.4.14
**Browser:** Chrome
**OS:** Mac

**Expected behavior:**
after pressing the "style" button, it should become active (add some class).

**Actual behavior:**
after pressing the "style" button, it does not become active (add some class).

**Attachments:**

![Screenshot 2020-07-07 at 12 14 14](https://user-images.githubusercontent.com/18167510/86757488-d82b0680-c04b-11ea-912a-2023e08512ec.png)

**Comment by kartik-budhiraja** [comment]
I am facing the same issue, if @xdan  could give some pointers, I can create a PR to fix this. I am not able to get `Jodit` set up on my local. I get `ENOENT: no such file or directory - index.html`, when I hit `localhost`.
