### ISSUE TITLE
the image editing dialog is not displayed

### ISSUE THREAD

**Issue by vaclavrozsypal** [xdan/jodit#431]
**Jodit Version:**  3.4.14

**Browser:**  Chrome
**OS:**  Windows

**Expected behavior:** after clicking on the edit icon next to the image, the edit dialog will appear

**Actual behavior:** after clicking on the edit icon next to the image, the edit dialog will not appear

**Comment by xdan** [comment]
Do you use a server-side connector?

**Comment by vaclavrozsypal** [comment]
I'm using simple self-hosted solution:

jodit.min.css (Jodit Version: 3.4.14)
jodit.min.js (Jodit Version: 3.4.14)
jodit_test.html (inside is code below)

```
<!doctype html>
<html>
<head>
    <meta charset="UTF-8" />

    <link rel="stylesheet" href="jodit.min.css" />
    <script src="jodit.min.js"></script>
</head>

<body>
    <div id="area_editor" />
    <script>
        try
        {
            var editor = new Jodit('#area_editor', {
                "fullsize": true,
                "spellcheck": false,
                "askBeforePasteHTML": false,
                "askBeforePasteFromWord": false,
                "defaultActionOnPaste": "insert_clear_html",
                "showCharsCounter": false,
                "showWordsCounter": false,
                "showXPathInStatusbar": false,
            });
        }
        catch (e)
        {
            alert(e);
        }
    </script>
</body>

</html>
```

And the image is inserted via a URL from server (not as Base64 string).

**Comment by xdan** [comment]
But for edit Image you should use filebrowser options https://xdsoft.net/jodit/doc/options/filebrowser/ And resize and crop serverside https://github.com/xdan/jodit-connectors#imageresize---resize-image

**Comment by vaclavrozsypal** [comment]
I'm not sure we're talking about the same thing:
![image](https://user-images.githubusercontent.com/54394459/87289644-326d1100-c4fd-11ea-86cc-4ba590d4e1c0.png)
