### ISSUE TITLE
bug with copy paste  from word

### ISSUE THREAD

**Issue by code1factor** [xdan/jodit#436]
**Jodit Version:**  3.2.xxxxx

**Browser:**  
**OS:**  

**Code**
<img width="1315" alt="Снимок экрана 2020-07-13 в 1 32 12" src="https://user-images.githubusercontent.com/18376867/87257998-b21cc080-c4a8-11ea-9deb-4a0915c963ee.png">

```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**

**Actual behavior:**

**Comment by xdan** [comment]
Need more information about this document
