### ISSUE TITLE
Files get renamed before upload

### ISSUE THREAD

**Issue by robertoibarra** [xdan/jodit#438]
**Jodit Version:**  3.4.14

**Browser:**  Chrome/FF
**OS:**  Windows

**Expected behavior:**
I drag a file or upload it via the filebrowser.

**Actual behavior:**
The file gets an extension appended to the name.

Examples: 
notasJCliber.txt gets renamed to notasJCliber.txt.plain
responses.csv gets renamed to responses.csv.vnd
NDA FORMATO.docx gets renamed to NDA FORMATO.docx.vnd

As far as I tested, neither images files nor PDFs get their names appended with an extension.
The renaming happens before the file gets uploaded as I viewed the POST to the uploader and it was already renamed eg.:
```
Content-Disposition: form-data; name="files[0]"; filename="responses.csv.vnd"
Content-Type: application/vnd.ms-excel
```

**Code**

I was reviewing the code from [jodit/src/modules/uploader/uploader.ts line 387](https://github.com/xdan/jodit/blob/4e104f23279b2736407bb5cd2c4acc7246562115/src/modules/uploader/uploader.ts#L387)

From what I can tell there is some type of check to see if the extension corresponds to a mime type or something like that but I guess there is some issue there.

I just patched my local jodit.js to ignore this file extension replacement code like so:

```js
//Line 17226
newName = fileList[i].name;
```

The whole section now looks like:
```js
            for (var i = 0; i < fileList.length; i += 1) {
                file = fileList[i];
                if (file) {
                    var mime = file.type.match(/\/([a-z0-9]+)/i);
                    var extension = mime && mime[1] ? mime[1].toLowerCase() : '';
                    var newName = fileList[i].name ||
                        Math.random().toString().replace('.', '');
                    if (extension) {
                        var extForReg = extension;
                        if (['jpeg', 'jpg'].includes(extForReg)) {
                            extForReg = 'jpeg|jpg';
                        }
                        var reEnd = new RegExp('.(' + extForReg + ')$', 'i');
                        if (!reEnd.test(newName)) {
                            newName += '.' + extension;
                        }
                    }
                    newName = fileList[i].name;
                    form_1.append(this.o.filesVariableName(i), fileList[i], newName);
                }
```

**Comment by SlivaNilow** [comment]
same issue

**Comment by DVDripXvid** [comment]
It seems to be fixed.
