### ISSUE TITLE
Inline Mode scroll up or down popup does not vanish

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#44]
**Jodit Version:**  3.1.91

Electron/chrome app

**Expected behavior:**
when scrolling up or down the popup menu should vanish

**Actual behavior:**
does no vanish

![jodit_bug11](https://user-images.githubusercontent.com/37185489/39411406-ca3775a8-4c09-11e8-84aa-a264acee92f3.gif)

**Comment by xdan** [comment]
Hi, how do I repeat this?

**Comment by mdevDE** [comment]
Hi, on scroll just hide the toolbar.

**Comment by xdan** [comment]
Fixed in 3.1.93
