### ISSUE TITLE
Count by html chars instead of the actual chars. 

### ISSUE THREAD

**Issue by zhangyuting1** [xdan/jodit#449]
dear all.
Any function or way to count the chars by html, eg:

**Actual behavior:**
if I have words in word "content" in red color, then the count chars is 7.

**Excepted behavior:**
in code mode, the html is 
<p><span style="color: rgb(255, 0, 0);">content</span></p>

Expect there is a way to count the chars in html mode, which in my case, count chars is 58

Thank you

**Comment by xdan** [comment]
Added https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#3416 countHTMLChars: true option
