### ISSUE TITLE
Usability issue when editing a URL name and target

### ISSUE THREAD

**Issue by robertoibarra** [xdan/jodit#453]
**Jodit Version:**  3.4.14

**Context:**
When you select a file via the Filebrowser or drop a file directly into Jodit, everything works beautifully. 

**Feature Request**
The user sees on the editor the full URL of the uploaded file and then when he presses the edit link button, he sees a popup with two inputs that show the URL. It is very hard for the user to distinguish which one is the actual URL and which one is the name of the link. I would suggest not using just a placeholder in the input (which works well when there is no data in it) but actually put on the left side a label with the field name like:
http://
Text

Thanks. I love Jodit!

**Comment by xdan** [comment]
Added labels, Thank you!
