### ISSUE TITLE
Copy paste image is allowing even after disabled the imageprocesser plugin in chrome 83

### ISSUE THREAD

**Issue by Jayaraj8905** [xdan/jodit#457]
Configuration is like below
{
          "toolbarButtonSize": "small",
          "showXPathInStatusbar": false,
          "defaultActionOnPaste": "insert_only_text",
          "askBeforePasteHTML": false,
          "askBeforePasteFromWord": false,
          "disablePlugins": "color,errorMessages,iframe,imageProcessor,imageProperties,inlinePopup,link,media,mobile,placeholder,resizer,table,tableKeyboardNavigation,search,DragAndDropElement,DragAndDrop,pasteStorage",
          "buttons": "bold,underline,italic,|,|,ol,ul,|,outdent,indent,|,fontsize,paragraph,|,|,align,undo,redo"
        }

**Comment by xdan** [comment]
When you copy something from editor - it will be pasted as-is. It is no mistake. What do you want to do?
