### ISSUE TITLE
Tab key does not give four spaces

### ISSUE THREAD

**Issue by gitsnuit** [xdan/jodit#462]
**Jodit Version:**  3.2.xxxxx

**Browser:**  Chrome 
**OS:**  Linux 

Used Jodit here: https://xdsoft.net/jodit/

1) Type something
2) Press the 'tab' key

**Actual behavior:**
Focus in the editor is switched to another button or element. 

**Expected behavior:**
I expect a tab to be four spaces

**Comment by xdan** [comment]
Nope, for form navigation - `tab` works correctly.
