### ISSUE TITLE
Buttons are disabled in html mode

### ISSUE THREAD

**Issue by vitaliishandra** [xdan/jodit#465]
**Jodit Version:**  3.4.17

**Browser:**  Chrome
**OS:**  Windows

**Code**

Almost all buttons are disabled in html mode for 3.4.17 version.
I tried to use activeButtonsInReadOnly but it did not help.
Is it the issue?

Are there any way to enable extraButtons in html mode?

**Comment by xdan** [comment]
Can you show your settings? Or show it in the playground?
