### ISSUE TITLE
Find icon not working

### ISSUE THREAD

**Issue by galcott** [xdan/jodit#469]
**Jodit Version:**  3.4.15

**Browser:**   Chrome
**OS:**   Windows

I include the "find" button in the buttons setting but it shows up as text instead of an icon and doesn't do anything.
`buttons: 'bold,underline,italic,|,superscript,subscript,|,font,fontsize,|,image,table,|,align,undo,redo,cut,copy,paste,|,hr,symbol,print,find'`

The toolbar looks like this.
![jodit](https://user-images.githubusercontent.com/4509764/89851359-505c7e80-db5a-11ea-95bb-0dc63f0465ce.jpg)

**Expected behavior:**
"Find" should show as an icon, and bring up a search box.

**Actual behavior:**
It shows up as text and does nothing.

**Comment by xdan** [comment]
Hi, use the latest version - it works out-of-the-box https://xdsoft.net/jodit/

**Comment by galcott** [comment]
Thanks. Keep up the great work!
