### ISSUE TITLE
text always being wrapped with <p>

### ISSUE THREAD

**Issue by zhangyuting1** [xdan/jodit#471]
**Jodit Version:**  3.4.22
**Browser:**   Chrome
**OS:**  Mac/Linux 

After I upgraded to latest jodit version, the value of the input is always wrapped with <p>
eg:
**Expected behavior:**
this is a pure text
**Actual behavior:**
<p>this is a pure text</p>

Is that a bug or it has purpose? 
Thank you

**Comment by xdan** [comment]
Yes, it is expected behavior. You can disable it https://xdsoft.net/jodit/play.html?disablePlugins=wraptextnodes&currentTab=Plugins
