### ISSUE TITLE
Jodit defaultHandlerSuccess function can't be customized?

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [xdan/jodit#476]
**Jodit Version:**  3.4.17

**Browser:**  Chrome 
**OS:**  Win10

**Code**

```js
const editor = new Jodit('#jodit', {
        height: 600,
        uploader: {
          url: 'https://xdsoft.net/jodit/connector/index.php?action=fileUpload',
          process: function (resp) {
            console.log('process', resp);
            const { data } = resp;
            return {
                files: data.files || [],
                baseurl: data.baseurl,
                messages: data.messages,
                success: true,
                time: "2020-08-06 06:42:21",
                isImages: [true],
                code: 220,
            };
          },
          defaultHandlerSuccess: (data, resp) => {
            console.log('defaultHandlerSuccess', data, resp);
            var i, field = 'files';
            if (data && data[field] && data[field].length) {
                for (i = 0; i < data[field].length; i += 1) {
                  const imgUrl = data.baseurl + data[field][i];
                  console.log(imgUrl)
                  editor.s.insertImage(imgUrl);
                }
            }
          },
          error: function (e) {
           console.log(e);
          }
        },
      });
```

**Expected behavior:** I want to upload image to my own sever, and custom defaultHandlerSuccess function as well;

**Actual behavior:** I wrote this demo according to the documentation： https://xdsoft.net/jodit/doc/types/IUploaderOptions/
But  in the documentation, defaultHandlerSuccess function  use `this.s.insertImage(imgUrl);`, in fact, insertImage is undefined; 

So I changed it to `editor.s.insertImage(imgUrl);`, also throw an error: 
`TypeError: Cannot read property 'toString' of undefined
    at e.insertImage (jodit.min.js:10)
    at t.defaultHandlerSuccess (myJoditEditor.js:73)
    at t.c.push.icon (jodit.min.js:10)
    at t.<anonymous> (jodit.min.js:10)
    at jodit.min.js:10
    at async Promise.all (:3001/index 0)`

**Comment by MustafaAgami** [comment]
This same issue i am facing in jodit-react version 1.3.39.
Error:
 Cannot read properties of undefined (reading 'insertImage')

**Comment by JinHe-PerkinElmer** [comment]
> This same issue i am facing in jodit-react version 1.3.39. Error: Cannot read properties of undefined (reading 'insertImage')

I am using the jodit version 3.4.17 and am not sure how react version is implemented. And I didn’t use the insertImage method in the end, but implemented it through a custom uploader interface.

**Comment by MustafaAgami** [comment]
Can we use this Jodit into react? because Jodit-react is not active as this? @JinHe-PerkinElmer

**Comment by JinHe-PerkinElmer** [comment]
> Can we use this Jodit into react? because Jodit-react is not active as this? @JinHe-PerkinElmer

Of course it can be used in react.

**Comment by MustafaAgami** [comment]
Can you please give any reference how to use it in react?

**Comment by JinHe-PerkinElmer** [comment]
> Can you please give any reference how to use it in react?

[Jodit Docs](https://xdsoft.net/jodit/docs/)

**Comment by MustafaAgami** [comment]
Do i need to import like this
```
<script type="importmap">
	{
		"imports": {
			"autobind-decorator": "https://unpkg.com/autobind-decorator@2.4.0/lib/esm/index.js"
		}
	}
</script>
<link rel="stylesheet" href="./node_modules/jodit/es2021/jodit.min.css" />
<script type="module">
	import { Jodit } from './node_modules/jodit/esm/index.js';
	import './node_modules/jodit/esm/plugins/add-new-line/add-new-line.js';
	import './node_modules/jodit/esm/plugins/fullsize/fullsize.js';
	import de from './node_modules/jodit/esm/langs/de.js';

	Jodit.langs.de = de;

	Jodit.make('#editor', {
		width: 600,
		height: 400,
		language: 'de'
	});
</script>
```
in react?

**Comment by JinHe-PerkinElmer** [comment]
> Do i need to import like this
> 
> ```
> <script type="importmap">
> 	{
> 		"imports": {
> 			"autobind-decorator": "https://unpkg.com/autobind-decorator@2.4.0/lib/esm/index.js"
> 		}
> 	}
> </script>
> <link rel="stylesheet" href="./node_modules/jodit/es2021/jodit.min.css" />
> <script type="module">
> 	import { Jodit } from './node_modules/jodit/esm/index.js';
> 	import './node_modules/jodit/esm/plugins/add-new-line/add-new-line.js';
> 	import './node_modules/jodit/esm/plugins/fullsize/fullsize.js';
> 	import de from './node_modules/jodit/esm/langs/de.js';
> 
> 	Jodit.langs.de = de;
> 
> 	Jodit.make('#editor', {
> 		width: 600,
> 		height: 400,
> 		language: 'de'
> 	});
> </script>
> ```
> 
> in react?

I wrote a demo here: [Demo](https://codesandbox.io/p/sandbox/jodit-demo-kfhgcq?file=%2Fsrc%2Findex.js%3A4%2C25)
However, two editors are displayed. I am not sure if it is a problem with codesandbox. My local code does not have this problem.

**Comment by xdan** [comment]
@JinHe-PerkinElmer 
Hi, please do not use React class component in 2024 =) And inside your code you forgot unmount
```
 componentWillUnmount() {
    this.editor.destruct();
 }
```

**Comment by JinHe-PerkinElmer** [comment]
> @JinHe-PerkinElmer Hi, please do not use React class component in 2024 =) And inside your code you forgot unmount
> 
> ```
>  componentWillUnmount() {
>     this.editor.destruct();
>  }
> ```

OK, thanks :)
