### ISSUE TITLE
Generated HTML on font change is not valid

### ISSUE THREAD

**Issue by olgweb** [xdan/jodit#477]
**Jodit Version:** 3.4.1

**Browser:** Chrome
**OS:** Windows

Hello xdan, 

We have a problem regarding fonts whose name consists of several words (e.g. Times New Roman). While changing a font of a text, Jodit internally creates a `<span>` element which contains also the style of the text. When the style is added to the `<span>` element, the font is handed over with single quotes (') but the object itself saves it with double quotes ("). The generated HTML for the text then looks like this: 

```
<span style="font-family: "Times New Roman", Times, serif;">Test</span>
```

This HTML is not valid because the quotes are not correct. The quotes should look like this: 

```
<span style="font-family: 'Times New Roman', Times, serif;">Test</span>
```

or like this: 

```
<span style='font-family: "Times New Roman", Times, serif;'>Test</span>
```

Since we define the fonts with single quotes but they are somehow changed during creation of the `<span>` object, we are not able to make sure that the single quotes are used. But modern browsers can still handle the invalid HTML to make sure it works as expected. The Google Chrome browser for example converts the wrong HTML from:

```
<span style="font-family: "Times New Roman", Times, serif;">Test</span>
```

to: 

```
<span style="font-family: &quot;Times New Roman&quot;, Times, serif;">Test</span>
```

while the Microsoft Edge browser converts the wrong HTML from:

```
<span style="font-family: "Times New Roman", Times, serif;">Test</span>
```

to: 

```
<span style='font-family: "Times New Roman", Times, serif;'>Test</span>
```

If the user uses the Microsoft Egde Browser then everything works fine but **if the user uses the Google Chrome browser we run into a problem because of a second factor:** we unescape the HTML (with the Java String method: `Strings.unescapeMarkup`) before saving the content of the editor in our database. This leads to the change of the HTML from:

```
<span style="font-family: &quot;Times New Roman&quot;, Times, serif;">Test</span>
```

back to: 

```
<span style="font-family: "Times New Roman", Times, serif;">Test</span>
```

which can not be interpreted by Jodit anymore when the content is loaded again from the database in the editor. The HTML in the editor looks then something like this: 

```
<span style="font-family: " times="" new="" roman",="" times,="" serif;"="">Test</span>
```

which leads to the fact that the style of the `<span>` is wrong and the font is changed back to the default font. You can easily reproduce it by adding the following String into the HTML editor: 

```
<span style="font-family: "Times New Roman", Times, serif;">Test</span>
```

Skipping the unescaping is not a possibility for us. And even if we would skip this step, the root cause is still that the HTML which is generated is not valid. While debugging the JavaScript we could find the place where the style is added to the `<span>`: 

css.ts line 48
```
(elm.style as any)[_key] = _value;
```
where "_value" contains a string with single quotes but afterwards the "elm.style" contains the value with double quotes. 

I guess this is a bug but do you have any suggestions how we could solve this problem in the meantime?

**Comment by xdan** [comment]
Yes, it is browser behavior and Jodit can not change it. 
I think you should change input value onSave in your db.
```js
editor.e.on('afterGetValueFromEditor', (v) => {
    v.value = v.value.replace(/style="([^"]+)"/g, (res, rules) => `style="${rules.replace(/&quot;/g, "'")}"`);
});

saveInYourDb(editor.value)
```
