### ISSUE TITLE
Wrong information in the Image Edit dialog

### ISSUE THREAD

**Issue by kartik-budhiraja** [xdan/jodit#478]
**Jodit Version:**  3.4.17

**Browser:**   N/A
**OS:**   N/A

**Code**
N/A

The image edit dialog shows link information of previous image. 

- Add one image, add link to it
- Add another image, open the image edit dialog
- It shows the link of previous image 

**Expected behavior:**

- It should not show wrong information

**Actual behavior:**

- The second image is selected, and you can see in the code, it does not have a link
- But it still shows the link of previous image in edit dialog

![Screen Shot 2020-08-12 at 12 18 50 PM](https://user-images.githubusercontent.com/34459894/90040490-fcef4b00-dc95-11ea-9cd5-88a0b4012aa1.png)

**Comment by xdan** [comment]
Fixed in 3.4.24
