### ISSUE TITLE
EU GDPR issues

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#48]
Hi Valery

I have some concerns using your editor in my project according to the new European Data protection law EU GDPR. 
- First of all Jodit makes certain connections to the sources, code below. If the cdnjs Servers are not located within the EU they are regarded as to be not 'safe harbour' and therefore not conform with the new EU GDPR law which will be introduced this month on the 25th! Are there any other sources that are loaded from the internet as well?
-  Second and also most important, I need to clarify the legal issues with the copyright of Jodit and all its direct and indirect dependencies (as shown in the code below: license of ace editor, beautifyHTML, etc.). Since German law is very restrictive and strict I need to clarify these issues in order to use the Jodit OEM license in a legal and correct way. Therefore, can you provide me with a full list of all direct and indirect dependent source codes and their licenses?

```javascript
Config.prototype.sourceEditorCDNUrlsJS = [
    'https://cdnjs.cloudflare.com/ajax/libs/ace/1.3.1/ace.js',
];
```

```javascript
Config.prototype.beautifyHTMLCDNUrlsJS = [
    'https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.7.5/beautify.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.7.5/beautify-html.min.js',
];
```

**Comment by xdan** [comment]
Hi, you can install `ace` editor and `js-beautify` packages separately
```bash
npm i --save ace-builds js-beautify
```
after this you can use these scripts from local host
```javascript
var editor = new Jodit('#editor', {
  sourceEditorCDNUrlsJS: [
     './node_modules/ace-builds/src-min/ace.js'
   ],
  beautifyHTMLCDNUrlsJS: [
    './node_modules/js-beautify/js/lib/beautify.js',
    './node_modules/js-beautify/js/lib/beautify-html.js'
  ],
 })
```

**Comment by mdevDE** [comment]
Thank you for this,

are there any other sources that will be dynamically loaded form the internet?
Can you please comment on the license issue as well?

**Comment by xdan** [comment]
1) https://www.jsdelivr.com/package/npm/ace 
https://www.jsdelivr.com/package/npm/js-beautify
2) ace-builds under BSD license, js-beautify under MIT
