### ISSUE TITLE
Handling doubleclick in Links

### ISSUE THREAD

**Issue by pvahia** [xdan/jodit#482]
Jodit Version: 3.2.xxxxx

Browser: Chrome
OS: Windows/Linux

**Steps:** 1) Insert a link
2) Double click on the link

**Actual behavior:**
Pop-up with link options is displayed, no navigation.

**Expected behavior:**
The link to open in a new tab directly.

Is there any way to achieve this?

**Comment by xdan** [comment]
You can use `link.followOnDblClick`=true option, but it will open link inside current window.
