### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#49]
Hi Valeriy,

I have multiple (more than 30 divs/textareas) which need inline mode editor support. Currently this means I have 30 Jodit instances. The number of 30 can be increased through user interaction and I don't know how many the user will insert at runtime. Therefore, to reduce overhead and complexity, it would be really good if I only need 1 inline mode instance for all divs/textareas. This would mean that I need a function with which I can register/unregister all divs/textareas (at initialization or at runtime dynamically). Or a function where I can register a className at initialization and all dynamically added divs/textareas will be supported as default without further interaction.

**Comment by xdan** [comment]
Hi, you can create instances dynamically. Something like this https://xdan.github.io/jodit/examples/oneinstance.html

**Comment by mdevDE** [comment]
Thanks for the example!!
