### ISSUE TITLE
Space before deleted character removed while using backspace

### ISSUE THREAD

**Issue by pvahia** [xdan/jodit#490]
**Jodit Version:** 3.2.xxxxx

**Browser:** Chrome
**OS:** Windows/Linux

**Step 1)** Type 'a b c d e'
**Step 2)** Set cursor after e
**Step 3)** Press backspace

**Actual behaviour:** The space after 'd' is also deleted
**Expected behaviour:** Space should not be removed

**Comment by Nice2Work** [comment]
Yes, this is a very, very annoying new behavior, wants me to go back to a much older Jodit. And at first, I was thinking it had to do with the different line breaks like <br>,<p> or <div> but that did not fix it. Also when going from editor to 'source view' and back this behavior sometimes is not there. Also now it just seems that the 'space' is still there but it is just not showing (as it takes 2 backspaces to remove the letters. It makes typing letters so awkward and so not conform other editors/word processors that this will be thrown off users.
