### ISSUE TITLE
Jodit Playground doesn't load on IE11

### ISSUE THREAD

**Issue by corrrso** [xdan/jodit#492]
**Jodit Version:**  website version on https://xdsoft.net/jodit/play.html

**Browser:**  IE11
**OS:**  Windows 10

There's a Javascript error in the Playground page of Jodit. Looks like it's there only on IE11.
I know I'm posting a lot of issues related to IE11, but my company is still forced to use it because Microsoft is still not including the browser Edge in their production SDK for MFC products. Hope this helps to improve Jodit's reliability

![image](https://user-images.githubusercontent.com/23524581/92210645-6a565c00-ee8f-11ea-90d8-893c92c6f7cd.png)

**Comment by xdan** [comment]
Should be fixed. Check, please.

**Comment by corrrso** [comment]
It is. It's a little bit slow on loading, but looks like it's IE's fault, so it's OK I guess.

Thank you once more.
