### ISSUE TITLE
buttons option not working.

### ISSUE THREAD

**Issue by Maadtin** [xdan/jodit#498]
**Jodit Version:**  3.4.26
**Browser:**  
Chrome
**OS:**  
Windows 10
**Code**
https://codesandbox.io/s/chakra-ui-027fq?file=/src/App.js
```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**
To not show any button in the toolbar
**Actual behavior:**
Shows default buttons in the toolbar

**Comment by xdan** [comment]
@Maadtin You should either disable the `mobile` plugin https://xdsoft.net/jodit/play.html?toolbarAdaptive=false&currentTab=Buttons
or check all options https://xdsoft.net/jodit/doc/options/buttonsMD/ SM, XS
