### ISSUE TITLE
Joomla errors!

### ISSUE THREAD

**Issue by lophas2** [xdan/jodit#50]
**Jodit Version:**  3.0.66

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**

**Actual behavior:**

Privet Valeriy!
Your extension looks awesome and very promising, but unfortunately does not work properly in Joomla! The package (downloaded from extensions.joomla.org) installed successfully under the newest Joomla 3.8.7 but when I try upload image, "Internal server error" is displayed. Also error occurs during the Configuration process. After removing any of the buttons, the Toolbar completly disappear, and need to use the "Restore default" button to recover it. 
The next error I found in the Components menu, when the "Jodit editor" submenu don't work, the page is empty.
My last question about the languages. How can I add another language file to the Joedit?
Under the 'media\com_jodit\js\jodit-play\node_modules\jodit\src\langs' I found some language-files, try to add another, but this is not enough!
Can You help me solve it? 
I see that Joedit - without these problems - will be by far the best editor for Joomla CMS!!!

**Comment by xdan** [comment]
Hi. Please download latest version here https://github.com/jodit/jodit-joomla/releases
Added restore defaults button

**Comment by lophas2** [comment]
Dear Valeriy!
Thanks for the restore defaults button, but THE PROBLEM IS NOT THAT!
Unfortunately, Your Jodit package COMPLETLY doesn't work properly with Joomla's latest version. (maybe not only the latest version affected)

1. Image and attachment upload don't work due to an INTERNAL SERVER ERROR!
2. In the global component configuration site no way to remove unnecessary icons!
(it seems as though it might be, but after saving the full toolbar will disappear!)

It is very unlikely that the error is unique, and and happens only to me, because I made the fresh joomla install on two different servers, and the result was the same! 
Sorry, but the Jodit in this moment not suitable for work (in joomla)!
Please check the problem, and fix it quickly!
Thanks in advance!

**Comment by xdan** [comment]
Can you give me access in your Joomla admin panel for test?

**Comment by lophas2** [comment]
I have sent the access data by email (skoder¤ya.ru)

**Comment by xdan** [comment]
Thank you. Fixed
