### ISSUE TITLE
Show/add break on toolbar

### ISSUE THREAD

**Issue by mash180** [xdan/jodit#508]
**Jodit Version:** v3.4.26

**Browser:**  Chrome
**OS:**  Windows

**Code**

```js
    buttons: "source,undo,redo,\n,font,fontsize,paragraph,brush"
```

**Expected behavior:**
    There should be a break line after the redo button, as show on playground.
**Actual behavior:**
    There are all the buttons, but the break line

**Comment by corrrso** [comment]
Try to do this:

`buttons:['source','undo','redo','\n','font','fontsize','paragraph','brush']`

It works here

**Comment by mash180** [comment]
This work perfectly, thanks a lot,
