### ISSUE TITLE
style bug in IE11

### ISSUE THREAD

**Issue by mhrezaee73** [xdan/jodit#509]
bug in ie 11 :
Style gets mixed up but correctly work in other browser
![Screen Shot 1399-06-30 at 17 52 49](https://user-images.githubusercontent.com/58993753/93712317-63f00180-fb6a-11ea-8103-c716d5bf671b.png)

**Jodit Version:**  3.2.xxxxx

**Browser:**   IE11
**OS:**   Mac

```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**

**Actual behavior:**

**Comment by corrrso** [comment]
Please try the latest version and also remember to clean cache. Usually, this problem comes out when a new .js bundle file is linked to an old .css bundle or vice versa.

**Comment by mhrezaee73** [comment]
thanks 👍
