### ISSUE TITLE
GNU License or MIT License ?

### ISSUE THREAD

**Issue by vigneshbarani24** [xdan/jodit#512]
**Jodit Version:**  3.2.xxxxx

**Browser:**  
**OS:**  

**Code**

```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**
Hello, I am planning to use Jodit but I am confused about if i can use this. I am not sure if whether the license is MIT or GNU. 
@xdan , Can you please update on this. The Repository says MIT but the Website says GNU.
**Actual behavior:**
A confirmation on the License will be helpful

**Comment by xdan** [comment]
@Vbboi24 MIT of course! Send me please link on the website about GNU, I will fix it

**Comment by vigneshbarani24** [comment]
![image](https://user-images.githubusercontent.com/20842962/93846474-c576b400-fcc1-11ea-8b35-1c4347de3919.png)
Hey @xdan , Found this on the homepage https://xdsoft.net/jodit/

Thanks for clarifying. Cheers!
