### ISSUE TITLE
Preset:inline / Link Popup Closes

### ISSUE THREAD

**Issue by perea1** [xdan/jodit#515]
**Jodit Version:**  3.4.27
**Browser:**  Chrome/IE/Safary/FF
**OS:**   Windows

https://xdsoft.net/jodit/play.html?toolbarButtonSize=large&preset=inline
You can´t enter a Link:
.) select text
.) click on the link button
.) try to enter URL or TEXT --> the popup closes

**Comment by perea1** [comment]
I noticed the same issue on the video url & image url in the popups

**Comment by Fedeorlandau** [comment]
Same issue here.

**Comment by Fedeorlandau** [comment]
@xdan I've added more information here: https://github.com/xdan/jodit/issues/582
