### ISSUE TITLE
Documentation is unavailable on the site

### ISSUE THREAD

**Issue by Dmitriy-Zavgorodniy** [xdan/jodit#516]
Hey there. Thanks for such a great tool!
The problem with the [documentation](https://xdsoft.net/jodit/doc/) - it is not displayed on the site and it is missing from the GitHub
It's hard without documentation. Please, make documentation alive again :)
Thanks in advance!

**Comment by xdan** [comment]
Thank you! Fixed!

**Comment by khaxel** [comment]
Some pages of documentation doesn't working now.
For example the page https://xdsoft.net/jodit/doc/options/disablePlugins/
Error in console: "ReferenceError: codeStyle is not defined"
Fix it please

**Comment by dennisat** [comment]
# Still is broken!
Example: https://xdsoft.net/jodit/doc/options/theme/
