### ISSUE TITLE
Insert link scrolls user to top of text area

### ISSUE THREAD

**Issue by Ako0** [xdan/jodit#519]
**Jodit Version:**  3.4.27

**Browser:**  Chrome
**OS:**  Mac

**Issue**

Insert a link at the bottom of the text area, and the editor scrolls to the top for a jarring experience.
![Screen Recording 2020-09-30 at 03 42 17 PM](https://user-images.githubusercontent.com/1160352/94732191-ef6c4e00-0333-11eb-9aca-96503b920f5f.gif)

**Expected behavior:**
The scroll position should remain the same before and after link insertion.

**Actual behavior:**
The scroll position is moved to the top of the text area.

**Comment by beeant** [comment]
Similar behavior when you blur the jodit editor, and then select an image on the lower area of the editor.
You can reproduce this by moving the image on the playground to somewhere at bottom area of the editor, scroll to the most bottom, blur the editor (by clicking somewhere outside the editor text area), and reselect the image.

**Comment by InputOutputZ** [comment]
The issue its reintroduced back again as soon as one defines an editor inside e.g. position: fixed; overflow-y: auto; height:500px, element. Getting ScrollY and calling scroll to top on first scrollable parent element to the editor seems will resolve the issue yet I couldn't figure out how to implement this, I fiddled with storeScrollState and restoreScrollState to retrieve the scrollY and X from first scrollable parent like following yet isn't working, note I tested this on inserting URL button and another custom button with pop up based input form. 

`
         function getEditorScrollParent(node) {
          const isElement = node instanceof HTMLElement;
          const overflowY = isElement && window.getComputedStyle(node).overflowY;
          const isScrollable = overflowY !== 'visible' && overflowY !== 'hidden';
        
          if (!node) {
            return null;
          } else if (isScrollable && node.scrollHeight >= node.clientHeight) {
            return node;
          }
        
          return getEditorScrollParent(node.parentNode) || document.scrollingElement || document.body;
        }

	private storeScrollState(): [number, number] {
		return [getEditorScrollParent(this.j.editor).scrollY, this.j.editor.scrollTop];
	}

	private restoreScrollState(scrolls: [number, number]): void {
		window.scrollTo(getEditorScrollParent(this.j.editor).scrollX, scrolls[0]);
		this.j.editor.scrollTop = scrolls[1];
	}
`

Anyone have any idea?
