### ISSUE TITLE
The link popup closes when trying to add it to an image inside a table.

### ISSUE THREAD

**Issue by kartik-budhiraja** [xdan/jodit#524]
The link popup closes when trying to add it to an image inside a table.
The gif below explains the issue.

**Jodit Version:**  3.4.28

**Browser:**   Chrome
**OS:**   Mac

**Code**
Popup options for image being used: 
```js
img: [
      ...Jodit.defaultOptions.popup.img.filter(
        option => option.name !== 'pencil' && option.name !== 'left'
      ),
      'align',
      'link',
      'unlink'
    ],
```

**Expected behavior:**
It should not close down.

**Actual behavior:**

![captured](https://user-images.githubusercontent.com/34459894/95621952-8fb32880-0a40-11eb-9f4a-1c75e9eccd2b.gif)

**Comment by xdan** [comment]
@kartik-budhiraja How I can repeat it? Is it react?

**Comment by kartik-budhiraja** [comment]
@xdan Yes this is react, to reproduce, you can change the `popup` options and add `link` to it for `img`, then add an image to a table and try adding `link` through the `link` in popup dialog to the image.
