### ISSUE TITLE
The enter keys getting stored as <br> instead of <br />, i.e., without end tag

### ISSUE THREAD

**Issue by dgkm** [xdan/jodit#525]
**Jodit Version:**  3.2.xxxxx

**Browser:**  All
**OS:**  All

**Scenario**

> When we use `<Enter>` for new lines, `<br>` tags will get introduced, instead of `<br /> or <br> </br>` tags with end tag format.

**Expected behavior:**
`<br /> or <br> </br>`

**Actual behavior:**
`<br>`

**Comment by xdan** [comment]
It depends on the doctype of your page and not on Jodit.
