### ISSUE TITLE
Playground is broken

### ISSUE THREAD

**Issue by adaam2** [xdan/jodit#53]
**Jodit Version:**  N/A

When playing around with button exclusion in the Playground (https://xdsoft.net/jodit/play.html), the code snippet generated after you've unchecked a few of the buttons on the right hand side doesn't seem to be serializing the options correctly:

```
var editor = new Jodit("#editor", {
  "buttons": "[object Object]"
});
```

Preview:

![screen shot 2018-05-15 at 12 10 00](https://user-images.githubusercontent.com/2907389/40053456-3a57b2cc-5839-11e8-835a-20be0671314a.png)

Just thought I'd give you the heads up!

**Comment by magictushar** [comment]
![image](https://user-images.githubusercontent.com/73274715/100070069-7edb3c80-2e5f-11eb-8c99-83048e75a934.png)
i dont know what actually happened it was working fine yesterday and now its kinda broken, plz help me?
