### ISSUE TITLE
Option to hide statusbar

### ISSUE THREAD

**Issue by Sayan751** [xdan/jodit#535]
**Jodit Version:**  3.4.29

**Browser:**  Chrome, FF 
**OS:**  Windows
**Is React App:**  False

**Code**

```js
this.editor = new Jodit(
    this.textArea,
    {
        toolbarAdaptive: false,
        useNativeTooltip: true,
        enableDragAndDropFileToEditor: true,
        uploader: this.uploader,
        buttons: [
            'undo', 'redo', '|',
            'font', 'fontsize', '|',
            'paragraph', 'brush', '|',
            'bold', 'italic', 'underline', 'subscript', 'superscript', 'outdent', 'indent', 'table', 'source', 'link', '|',
            'image', customControl1.name, customControl2.name
        ],
        controls: {
            customControl1,
            customControl2,
        },
        defaultActionOnPaste: 'insert_as_html',
        events: {
            getIcon: this.getIcon,
        }
    });
this.editor.statusbar.hide();
```

**Expected behavior:**

I would expect the statusbar to stay hidden always.

**Actual behavior:**

However, when I switch to the source view, the statusbar reappears. And it stays there even after I switch back to the rich text view.

I have expected a simple option to be there, when set the statusbar is not shown at all.

**Comment by xdan** [comment]
you can disable all of these options https://xdsoft.net/jodit/play.html?showCharsCounter=false&showWordsCounter=false&showXPathInStatusbar=false
and it will hide statusbar

**Comment by Sayan751** [comment]
Thanks @xdan! That works for me. 

I still think however that it makes more sense to add a flag option to hide the status bar.

**Comment by mufucool1** [comment]
Add css below to hide:

.jodit-status-bar-link {
  display: none !important;
}
