### ISSUE TITLE
How to disable HTML auto escape

### ISSUE THREAD

**Issue by davidoabile** [xdan/jodit#54]
I use Liquid within my editor and the editor automatically escapes the html e.g. 

```{% if a > b %}``` this gets changed to ```{% if a &gt; b %}```

Both methods 
getNativeEditorValue() and  getEditorValue() return the same thing

How can I fix this.

**Comment by xdan** [comment]
Hi, you can use 
https://xdsoft.net/jodit/doc/events/beforeGetValueFromEditor/
```javascript
var editor = new Jodit(appendTestArea());
editor.value = 'test {% if a > b %} stop {% if a < b %}';
expect(editor.value).to.be.equal('test {% if a &gt; b %} stop {% if a &lt; b %}');

editor.events.on('beforeGetValueFromEditor', function () {
        return editor.getNativeEditorValue().replace(/\{%[^\}]+%\}/g, function (match) {
                 return match
                                .replace(/&gt;/g,  '>')
                                .replace(/&lt;/g,  '<');
        });
});
expect(editor.value).to.be.equal('test {% if a > b %} stop {% if a < b %}')
```

**Comment by xdan** [comment]
Added test https://xdan.github.io/jodit/test/test.html?grep=Jodit%20Editor%20Tests%20Set%2FGet%20Change%20returning%20value%20Event%20%22beforeGetValueFromEditor%22

**Comment by salahatwa** [comment]
Hi ,

if we need to disable in whole document not specific regular expression , how can we do that ?

**Comment by salahatwa** [comment]
when writing tag like this </#list> 
it's commented to  

how to disable auto comment in jodit editor , for your gentle support
