### ISSUE TITLE
useAceEditor option is no-op

### ISSUE THREAD

**Issue by Sayan751** [xdan/jodit#544]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome/FF
**OS:**  Windows
**Is React App:**  False

**Code**

```js
this.editor = new Jodit(this.textArea, {
  useAceEditor: false,
  beautifyHTML: false,
  buttons: ['source', ....]
});
```

**Expected behavior:**
The Ace editor not be there and the CDN Url is not added to the DOM.

**Actual behavior:**
In order to actually disable the Ace editor, one need to set `sourceEditor: 'area'`. In that case, it might be better to remove that `useAceEditor` option altogether, as it is misleading.

**Comment by xdan** [comment]
@Sayan751 Sorry, `useAceEditor`will be removed in the next release.
