### ISSUE TITLE
I18n keys

### ISSUE THREAD

**Issue by ExReanimator** [xdan/jodit#546]
https://github.com/xdan/jodit/blob/25f0b49837e42d9ca52569c37e477dafe87d668f/src/plugins/clipboard/paste/paste.ts#L145

Can you please add I18n keys to translate it?

**Comment by xdan** [comment]
@ExReanimator 
There is key https://github.com/xdan/jodit/blob/master/src/langs/ru.js#L83 
In what language does not have this key?
