### ISSUE TITLE
Width breaks config

### ISSUE THREAD

**Issue by gpreapp** [xdan/jodit#551]
**Jodit Version:**  3.4.29

**Browser:**  Chrome, Edge, FF
**OS:**  Windows, Linux
**Is React App:**  false

**Code**

```js
var editor = new Jodit("#email_content", {
  //"theme": "dark", //This should be changed when the theme of the site changes.
  
  "toolbarButtonSize": "small",
  "enter": "DIV",
  "buttons": "undo,redo,|,bold,strikethrough,underline,italic,,,,,,,,,,,,,,,,align,\n",
  "width" : "400px"
});
```

**Expected behavior:**
the textarea should be limited to 40% of the width and buttons and other parts should work as expected.

**Actual behavior:**
Width is set correctly, but suddenly I see all the buttons as well.

Tried to reproduce with jsfiddle, but seems it failed to properly work there at all.

https://codepen.io/gborbonus/pen/bGexWzw (you'll see 2 versions, one without the width and the other with the width set. The "buttons" are configured exactly the same.

**Comment by gpreapp** [comment]
It also breaks in the playground. (remove bold and use the size option to resize it). 
It's also breaking when changing the size of the container (mobile).

I don't know what the conditions within the code are. I have not dug that far into it.

**Comment by xdan** [comment]
@gpreapp It is expected behavior, you should disable adaptive toolbar https://xdsoft.net/jodit/play.html?toolbarAdaptive=false&currentTab=Buttons

**Comment by gpreapp** [comment]
I literally just saw this and fixed it. Thanks for getting back to me but sorry I wasted time. Love this editor!
