### ISSUE TITLE
dynimic id

### ISSUE THREAD

**Issue by oncd** [xdan/jodit#554]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome/IE11
**OS:**   Windows
**Is React App:**  

**Code**

```js
// A *self-contained* demonstration of the problem follows...
```
dynimic id error
**Expected behavior:**
id : #42dab4cea90123070a305a403b256951_brd_content

**Actual behavior:**
error message :
jodit.min.js:10 Uncaught TypeError: String "#42dab4cea90123070a305a403b256951_brd_content" should be valid HTML selector
    at Object.t.error (jodit.min.js:10)
    at Object.t.resolveElement (jodit.min.js:10)
    at new Jodit (jodit.min.js:10)
    at i (jquery-1.12.4.min.js)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.min.js)
    at Function.ready (jquery-1.12.4.min.js)
    at HTMLDocument.K (jquery-1.12.4.min.js)

**Comment by xdan** [comment]
@oncd 
> The HTML 4.01 spec states that ID tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens (-), underscores (_), colons (:), and periods (.). For the class attribute, there is no such limitation. Classnames can contain any character, and they don’t have to start with a letter to be valid.

**Comment by oncd** [comment]
@xdan Thank you. Have a nice day.
