### ISSUE TITLE
Fill color or text color change order

### ISSUE THREAD

**Issue by oncd** [xdan/jodit#555]
hi!
Fill color or set the text color -> text color or Fill color
change order
default change
Is it possible?

**Comment by oncd** [comment]
Because it uses more of the 'text color'.

**Comment by xdan** [comment]
Hi @oncd, https://xdsoft.net/jodit/doc/options/colorPickerDefaultTab/

**Comment by oncd** [comment]
@xdan  Thank you. Have a nice day.
