### ISSUE TITLE
Custom Button with mode:3

### ISSUE THREAD

**Issue by mdevDE** [xdan/jodit#56]
Jodit Version:**  3.1.96

**Code**
```javascript 
{
    name    : 'list_test',
    iconURL : 'stuf/dummy.png',
    mode    : 3,
    list    : {
        h1: 'insert Header 1',
        h2: 'insert Header 2',
        clear: 'Empty editor'
    },
    exec    : function(this:any, editor: any) {
        var key = this.args[0],
        value = this.args[1];
        if (key === 'clear') {
            this.val('');
            return;
        }
        editor.selection.insertHTML('&nbsp;{{test'+key+'}}&nbsp;');
    },
    template: function(key: string, value: string){
        return '<div>' + value + '</div>';
    }
}
```
**Expected behavior:**
1. The Button should be active in source code mode
2. The list items should also be active
**Actual behavior:**
1. ok
2. all items are disabled

![jodit bug](https://user-images.githubusercontent.com/37185489/40569584-2f39e4bc-6083-11e8-867e-57eded8b8f2a.gif)

**Comment by salahatwa** [comment]
this.config.extraButtons= [{
                name: 'OnlyParagraph',
                icon: 'fa fa-superscript',
                mode    : 1 | 2 | 3,
                tooltip:"EXTERA",
                isActive:true,
                exec: (editor) => {
                  var selection = editor.selection;
                  var text = editor.selection.getHTML();
                  console.log(text);
                  var html = '<p>' + text + '</p>'
                  console.log(html);
                  editor.selection.remove();
                  editor.selection.insertHTML(html);
                }
              }]
