### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by virart** [xdan/jodit#574]
Jodit eats up a huge amount of RAM without freeing it up.

The error is reproduced in the playground - https://xdsoft.net/jodit/play.html?uploader%5BinsertImageAsBase64URI%5D=true

In linux, after entering 1000 characters, the browser tab took up 6.5 GB of RAM. Each new character increases the amount of memory used. After 15 minutes of downtime, only 200 MB was released. In Windows OS, the tab displays an out of memory error after it takes up 7GB of RAM.

Error repetition algorithm:
1. Drop any image file from disk to Jodit. ( >2 MB for a better presentation)
2. Type any text.

***
Jodit съедает огромное количество оперативной памяти не освобождает её.

В libux после ввода 1000 символов вкладка браузера занимала 6.5 гб оперативной памяти. Каждый новый символ увеличивает занимаемую память. После 15 минут простоя освободилось всего 200мб.

В ОС Windows вкладка выдает ошибку "Out of memory" того как займет 7GB оперативной памяти.

Ошибка воспроизводится в песочнице - https://xdsoft.net/jodit/play.html?uploader%5BinsertImageAsBase64URI%5D=true

Повторение ошибки:
1. Переносим файл изображения драгНдропом. Чем больше, тем нагляднее будет.
2. Печатаем любой текст.

**Jodit Version:**  3.4.23, 3.4.29

**Browser:**  Chrome 85.0.4183.121 on Ubuntu, Chrome 87.0.4280.88 on Windows 7
**OS:**  Ubuntu 19.10 (Kubuntu), Windows 7
**Is React App:**  False

**Code**
```js
var editor = new Jodit("#editor", {
  "uploader": {
    "insertImageAsBase64URI": true
  }
});
```

**Comment by xdan** [comment]
Need to implement `maxHistoryLength` option.
