### ISSUE TITLE
Clear formatting control does not clear all styles (keeps underline and strikethrough)

### ISSUE THREAD

**Issue by liadbe** [xdan/jodit#575]
**Jodit Version:**  3.4.29
**Browser:**  Chrome
**OS:**  Windows
**Is React App:**  True

**Expected behavior:**
In Jodit playground (and in my own project), I'm selecting a piece of text and choosing the following styles - font-size, font-family, bold, strikethrough, italic, underline, align-center, link, bg-color, text-color, superscript, block-format (heading  1).

My expectation is that when I press on the control Clear Formatting (eraser icon) my text will go back to normal OR keep ONLY the block-format, link and text-align.

**Actual behavior:**
I reality the styles that should disappear and are staying as styles even after clicked the clear formatting are - strikethrough, underline (both should not stay), also what is staying is the link, block-format and alignment (which are up for debate...)

**Comment by yaronism** [comment]
Very much needed!

**Comment by xdan** [comment]
Fixed in 3.5.1.
