### ISSUE TITLE
Question: How can I append to the html?

### ISSUE THREAD

**Issue by gpreapp** [xdan/jodit#579]
Simple question and maybe I'm just overlooking a really simple method, but I don't think it was clear in the docs.

I already know how to use editor.selection.insertHTML This is specifically for adding content to the very end of the textarea.

Thanks in advance.

**Comment by xdan** [comment]
Hi @gpreapp , use vanila JS)
```js
editor.editor.appendChild(editor.createInside.fromHTML('some html'))
```

**Comment by gpreapp** [comment]
Thanks. I appreciate that.

**Comment by gpreapp** [comment]
After testing this, I see that it's not doing something correctly as the injection is NOT apart of the saved body. Is there some disconnect?

**Comment by gpreapp** [comment]
I just sent an empty object into the editor after creating that. But I'm seeing another issue I'll bring up in a issue.
