### ISSUE TITLE
Determining buttons on inline mode doesn't work.

### ISSUE THREAD

**Issue by Fedeorlandau** [xdan/jodit#580]
**Code**
```js
Jodit.make('#editor', {
   preset: 'inline',
   popup: {
      selection: ["bold"]
   }
});

```

**Expected behavior:**
Determine which buttons appear on INLINE mode.
No matter what I add on the selection property, it always display more buttons.

Should display only the bold button on text selection.

**Actual behavior:**
That example displays the bold button + 10 others.

**Comment by Fedeorlandau** [comment]
Update: If I use Jodit.Array(["bold"]) I get:
```
jodit.min.js:10 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at t.setContent (jodit.min.js:10)
    at t.showPopup (jodit.min.js:10)
    at t.o [as showPopup] (jodit.min.js:10)
    at t.onSelectionChange (jodit.min.js:10)
```

**Comment by xdan** [comment]
Try in 3.5.1. But use **Jodit.atom(** instead of Jodit.Array(
Jodit.Array( - is deprecated

**Comment by Fedeorlandau** [comment]
@xdan  Didn't work. I've tried
```
  buttons: Jodit.atom(['bold', 'italic']),
popup: {
    a: null,
    selection: Jodit.atom(["bold", "italic"])
  },
```

And it's still showing me the align, dots, ol controls

**Comment by Fedeorlandau** [comment]
It worked it was my bad. I was doing a deepmerge after declaring this.
