### ISSUE TITLE
3.5.1: Cannot find module 'autobind-decorator' or its corresponding type declarations.

### ISSUE THREAD

**Issue by dylang** [xdan/jodit#584]
**Jodit Version:**  3.5.1

**Browser:**  n/a
**OS:**  n/a
**Is React App:**  n/a
**TypeScript**: 4.0.5

**Code**

`tsc`

**Expected behavior:**

no error

**Actual behavior:**

> node_modules/jodit/src/core/decorators/index.ts:15:37 - error TS2307: Cannot find module 'autobind-decorator' or its corresponding type declarations.
> 
> 15 export { default as autobind } from 'autobind-decorator';
>                                       ~~~~~~~~~~~~~~~~~~~~

It appears `autobind-decorator` was included as a `devDependency` but is used as a dependency in index.ts.

https://github.com/benmosher/eslint-plugin-import may help avoid these issues in the future.

**Comment by Fedeorlandau** [comment]
Hi @dylang looks like xdan fixed it here. https://github.com/xdan/jodit/issues/583

Cheers,
