### ISSUE TITLE
Не инициализируется редактор

### ISSUE THREAD

**Issue by blackish-gh** [xdan/jodit#585]
**Jodit Version:**  3.5.1/3.5.2

**Browser:**  All
**OS:**  Windows
**Is React App:**  False

**Expected behavior:**

Не инициализируется редактор.

**Actual behavior:**

![изображение](https://user-images.githubusercontent.com/33609494/102802141-e765fc80-43be-11eb-89f8-6678fa8482b7.png)

**Comment by blackish-gh** [comment]
После обновления такая история. Предыдущие версии ставали без проблем

**Comment by xdan** [comment]
@blackish-gh English please, other guys will look for information on this issue, will not find it, and will create a duplicate issue.

**Comment by xdan** [comment]
Fixed in 3.5.3
