### ISSUE TITLE
controls.list of object are merged, not replace

### ISSUE THREAD

**Issue by s-renier-taonix-fr** [xdan/jodit#586]
**Jodit Version:**  3.4.xxxxx

**Browser:**  FF
**OS:**  Linux
**Is React App:**  False

**Code**

```js
Jodit.make('#editor' ,{
      controls: {
	      font: {
		      list: {
			      'Liberation,Serif': 'Liberation Serif',
		      }
	      }
      }
});
```

**Expected behavior:**
The list specified in this code should replace the default list

**Actual behavior:**
The list specified in this code is append to the default list

**Comment by xdan** [comment]
@s-renier-taonix-fr It is normal behavior, use `Jodit.atom` for replacing
```js
Jodit.make('#editor' ,{
      controls: {
	      font: {
		      list: Jodit.atom({
			      'Liberation,Serif': 'Liberation Serif',
		      })
	      }
      }
});
```

**Comment by s-renier-taonix-fr** [comment]
Oups ! Sorry.
I don't find this tip on Google.
I close this issue.
