### ISSUE TITLE
From Jodit 3.5.1 on, popup z-index is lower than the modal (Ant Design) z-index

### ISSUE THREAD

**Issue by liadbe** [xdan/jodit#587]
**Jodit Version:**  3.5.2 (jodit-react 1.0.68)

**Browser:**  Chrome
**OS:**  Windows
**Is React App:**  True

**Expected behavior:**
We are using Ant Design components in our app, and when using the editor inside a modal (https://ant.design/components/modal/), clicking the list controls does not show the popup window (the list items). Using dev-tools, I notice that the popup opened but since z-index (7, seems like dynamically calculated) is smaller than the modal z-index (1000) it is now shown.

**Actual behavior:**
When I click a list (popup) control - the popup opens.

**Current code work-around:**
I added to my css this piece of code and it solves the issue (not so happy with that though)
```js
.jodit-popup {
    z-index: 1300 !important;
}
```

Is there a better solution to that problem?

**Comment by xdan** [comment]
Should be fixed in 3.5.4
