### ISSUE TITLE
How to use limit.js

### ISSUE THREAD

**Issue by komen205** [xdan/jodit#594]
**Jodit Version:**  3.4.25

**Browser:**  Chrome
**OS:**   Windows
**Is React App:**  False 

**Code**

Jodit.plugins.add('limit', function (editor) {
    editor.events.on('someEvent', function (text) {
        limitChars: 100;
    });
});

var editor = new Jodit('#editor',{
    buttons: ['source', '|', 'bold', 'italic', '|', 'ul', 'ol', '|', 'font', 'fontsize', 'brush', 'paragraph','left', 'center', 'right', 'justify', '|', 'undo', 'redo', '|', 'hr', 'eraser', 'fullsize'],
});

**Expected behavior:**

Limiting the words/characters to a certain number.

**Actual behavior:**
I can add more characters than I selected

![image](https://user-images.githubusercontent.com/59452877/103480917-52580000-4dcf-11eb-96cd-779a89ba6012.png)

**Comment by xdan** [comment]
Jodit already has this plugin https://xdsoft.net/jodit/doc/options/limitChars/
and
https://xdsoft.net/jodit/doc/options/limitWords/
Just enable options
