### ISSUE TITLE
Spacing html code

### ISSUE THREAD

**Issue by kobra117** [xdan/jodit#595]
**Jodit Version:**  3.4.xxxxx

Browser: Chrome/FF
OS: Windows
Is React App: False

is there a chance to set the editor not to change the position of the html code as in the pictures I use it for ebay auctions and after changing the position of the code it breaks the ebay editor.

When i copy html into editor it looks like this
<img src="https://i.ibb.co/ZSZFvyY/2.jpg">

but when try to go back to html its making the code like this
<img src="https://i.ibb.co/rm8KnTF/1.jpg">

**Comment by xdan** [comment]
@kobra117 https://xdsoft.net/jodit/doc/options/beautifyHTML/ disable this otptions

**Comment by kobra117** [comment]
how do i disable it ?

**Comment by kobra117** [comment]
After a few attempts and failures, I was able to fix it, thank you very much for your help and for such a great tool.
