### ISSUE TITLE
Build is not ES5 compliant

### ISSUE THREAD

**Issue by vitorhsb** [xdan/jodit#596]
Current build is not ES5 compliant which means that Internet Explorer 11 is not supported at the moment.

When trying to use it in IE11 it throws a "SyntaxError: Unexpected token" due to the presence of arrow functions syntax "=>".

Maybe use `es-check` on build action to validate if is safe ES5? https://www.npmjs.com/package/es-check

**Jodit Version:**  3.5.4

**Browser:**  IE11
**OS:**  Windows
**Is React App:** False

**Expected behavior:**

Support IE11 browser by building a convenient ES5 syntax build.

**Actual behavior:**

Build creates a ES6+ version of the editor which does not work on IE 11.

**Comment by fkranenburg** [comment]
Please fix this. We use this component inside MS add-in which still uses embedded IE11 on most systems.

**Comment by Fedeorlandau** [comment]
Would love to have this. Thanks @vitorhsb for raising this up.

**Comment by ozcoder** [comment]
I think **webpack.config.js** needs
`target: 'es5'`
in the _config_ object, but I don't know enough about **webpack** to be sure.
