### ISSUE TITLE
Photo albums are not available on the phone

### ISSUE THREAD

**Issue by yunfeiguan** [xdan/jodit#60]
**Jodit Version:**  3.1.xxxxx

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**

**Actual behavior:**

**Comment by korzhanov** [comment]
Selecting an image and uploading from the phone also does not work. v3.2.6

**Comment by stevekim** [comment]
@xdan Does this fix work without enabling the file browser?
