### ISSUE TITLE
Hotkeys "Cmd+B" open bookmark panel in Firefox on MacOS

### ISSUE THREAD

**Issue by TimurSeyidov** [xdan/jodit#61]
Hi. I'm run Jodit on Mac OS High Sierra in Firefox browser. Hotkeys "Cmd+B" run firefox bookmarks panel but not set strong font

**Comment by xdan** [comment]
Unfortunately, I can not repeat this error in VMWare. Try changing the hotkey settings. https://xdsoft.net/jodit/examples/another/shortcuts.html
