### ISSUE TITLE
remove font family name escaped quote

### ISSUE THREAD

**Issue by helvenk** [xdan/jodit#613]
Font family name that includes space will be escape with html entity quotes, how to remove this behavior or custom the output, such as the following results:
```js
// single quote in double quote
style="font-family: 'Times New Roman';"

// double quote in single quote
style='font-family: "Times New Roman";'
``` 
![image](https://user-images.githubusercontent.com/20789074/105674131-03ab0b00-5f22-11eb-8f26-8a488153ba16.png)

**Comment by xdan** [comment]
It is normal browser behavior. Try select some elment in inspecotor and execute in console this line
```js
$0.style.fontFamily = "'Times New Roman', Arail";
console.log($0.outerHTML);
```

**Comment by helvenk** [comment]
Yes it is browser behavior, but my boss who is OCD does not like the escaped quote symbol, and I finally use following code to replace the escaped quote with single quote: 
```js
function removeEscapedQuotes(html: string) {
  return html.replace(/style="font-family:.*?"/g, (match) => match.replace(/&quot;/g, "'"));
}

editor.events.on('beforeGetNativeEditorValue', () => {
  const html = editor.editor?.innerHTML;
  if (html) {
    return removeEscapedQuotes(html);   
  }
})
```

**Comment by helvenk** [comment]
Yes it is browser behavior, but my boss who is OCD does not like the escaped quote symbol, and I finally use following code to replace the escaped quote with single quote: 
```js
function removeEscapedQuotes(html: string) {
  return html.replace(/style="font-family:.*?"/g, (match) => match.replace(/&quot;/g, "'"));
}

editor.events.on('beforeGetNativeEditorValue', () => {
  const html = editor.editor?.innerHTML;
  if (html) {
    return removeEscapedQuotes(html);   
  }
})
```
