### ISSUE TITLE
Create own file manager (image browser) module/plugin

### ISSUE THREAD

**Issue by coax** [xdan/jodit#615]
The idea is to make my own file manager, a simple image browser which will insert image (onclick) into editor.
So far, I've managed to prepare everything but I cannot execute JavaScript in Dialog popup. Is there a way to do it with Dialog or any other way? If not, can I make Ajax call inside popup? Thanks.

```
var editor = new Jodit(this, {
...
    extraButtons: [{
          name: 'File manager',
          tooltip: 'File manager',
          icon: '/filemanager.png',
          exec: function(editor) {
                var dialog = editor.getInstance('Dialog'),
                html = editor.create.fromHTML('<div class="files">/* images will be listed here with JavaScript */</div>\
                <div id="preview">\
                    <div>/* image will be shown here with JavaScript */<button>Insert</button></div>\
                </div>\
                <script>/* JavaScript here */</script>');
                html.querySelector('button').onclick = function () {
                    editor.selection.insertHTML('/* insert image into editor */')
                }
                dialog.setHeader('File manager');
                dialog.setContent(html);
                dialog.setSize(Math.min(900, screen.width),Math.min(640, screen.width));
                dialog.open(true);
          }
    }]
...
});
```
![filemanager](https://user-images.githubusercontent.com/189817/107087177-58406700-67fb-11eb-80da-021c05283698.png)

**Comment by xdan** [comment]
@coax `<script>/* JavaScript here */</script>` will be not executed, why do you do it here?
You can execute your code after `dialog.open(true);`

**Comment by coax** [comment]
> @coax `<script>/* JavaScript here */</script>` will be not executed, why do you do it here?
> You can execute your code after `dialog.open(true);`

Thank you for replying. I understand it's not running script tag from dialog, hence the question, but also I cannot run code after `dialog.open(true);` as DOM elements do not exist yet. Any tips on how bind my own JS after opening dialog window?

**Comment by xdan** [comment]
Hmm, you can use the `afterOpen` event, but IDialog.open is a synchronous method and after it all the DOM elements already exist.

```js
var dialog = editor.getInstance('Dialog');

dialog.e.on('afterOpen', () => {
 // do somthing
});

dialog.open();
```

**Comment by coax** [comment]
You're right, DOM elements already exist so there's no need for `afterOpen`. I made a typo in my code (duh!).

Thank you for your time answering me and for this great WYSIWYG editor you made.
