### ISSUE TITLE
Version for react 17.0.1

### ISSUE THREAD

**Issue by igordps** [xdan/jodit#623]
Do you have a forecast for a version compatible with react 17.0.1?

**Jodit Version:**  3.4.xxxxx

**Browser:**  
**OS:**  
**Is React App:**  

**Code**

```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**

**Actual behavior:**

**Comment by xdan** [comment]
@igordps Is the current version incompatible? Did you try? Have errors?

**Comment by pdambrauskas** [comment]
It does work on React 17.0.1, only problem is that it throws some warning messages, when installing:
```
warning " > jodit-react@1.0.70" has incorrect peer dependency "react@~0.14 || ^15.0.0 || ^16.0.0".
warning " > jodit-react@1.0.70" has incorrect peer dependency "react-dom@~0.14 || ^15.0.0 || ^16.0.0".
```

**Comment by rjumatov** [comment]
That's not the only problem unfortunately:
[https://github.com/jodit/jodit-react/issues/106](url)

I cannot use Jodit with React 17 without having fatal errors.
