### ISSUE TITLE
Incorrect character count

### ISSUE THREAD

**Issue by galcott** [xdan/jodit#631]
**Jodit Version:**  3.6.1

**Browser:**   Chrome/FF 
**OS:**   Windows
**Is React App:**  False 

![jodit-charcount](https://user-images.githubusercontent.com/4509764/109325820-609d2800-7824-11eb-80dc-30dc600f9ccf.jpg)

**Expected behavior:**
Correct character count is 247.
**Actual behavior:**
Character count shown is 209.

In some cases like this, the character count shown is less than the actual count (it's never more). It doesn't happen all the time and I can't see any pattern to when it happens.

**Comment by xdan** [comment]
@galcott Hi, your text has 209 characters without spaces. Do you need to count spaces too?

**Comment by arjitinshorts** [comment]
> @galcott Hi, your text has 209 characters without spaces. Do you need to count spaces too?

How to include spaces ?

**Comment by galcott** [comment]
Look for this line in the Jodit code.
 var o = t.j.o.countHTMLChars ? t.j.value :
e.replace(i.SPACE_REG_EXP(), " ");
Change it to this.
 var o = t.j.o.countHTMLChars ? t.j.value : e;

	-----------------------------------------From: "Arjit Kansal" 
To: "xdan/jodit"
Cc: "galcott", "Mention"
Sent: Monday July 5 2021 5:22:29AM
Subject: Re: [xdan/jodit] Incorrect character count (#631)

	@galcott [1] Hi, your text has 209 characters without spaces. Do you
need to count spaces too?  

	How to include spaces ? 

	—
 You are receiving this because you were mentioned.
 Reply to this email directly, view it on GitHub [2], or  unsubscribe
[3]. 

Links:
------
[1] https://github.com/galcott
[2] https://github.com/xdan/jodit/issues/631#issuecomment-873955136
[3]

**Comment by mauriciodeleonc** [comment]
@xdan I have the exact same issue / problem with:
**jodit-react:** 1.1.20,

**Browser:** Chrome/FF
**OS:** Windows
**Is React App:** True

The character counter doesn't change when typing spaces, is there a way for us to change that behavior through another prop in the config?

I've looked in the documentation but can't seem to find any config that solves this issue.
Please let me know if you need any more information or any way I can help you with.

**Comment by dangkhoaphung** [comment]
@xdan , I'm also facing same issue for counting character. It didn't count space and html tag.
"jodit-react": "^4.1.2"

Browser: Chrome/FF
OS: Mac OS
Is React App: true

May I know whether this issue will be fixed?

Thanks
