### ISSUE TITLE
Logical OR assignment operator prevents code from compiling with typescript < 4.x

### ISSUE THREAD

**Issue by kfgodel** [xdan/jodit#634]
**Jodit Version:**  3.6.1

**Browser:**  Any
**OS:**  Any
**Is React App:**  True

**Code**
The assignment in [this line](https://github.com/xdan/jodit/blob/master/src/core/ui/helpers/get-control-type.ts#L28) 
```
controls ||= Config.defaultOptions.controls;
```
is using the _logical OR assignment_ operator only supported from typescript 4 and beyond. Which results in a compilation error when using previous typescript versions: 

Code snippet to reproduce error [available here](https://www.typescriptlang.org/play?ts=3.9.7&ssl=5&ssc=23&pln=1&pc=1#code/DYUwLgBAxg9gdmATjYBnAXBARjFICGcEAvBEgK4gDcAsAFD2wLJoQA+bpAZvmtfY3io8AOmAwA5gAomSFKgCUVIA)

**Expected behavior:**
I expect to include Jodit 3.6.1 as a dependency in a project with typescript 3.9.7 and be able to compile without errors.
Or have an explicit requirement on the typescript version to prevent version mismatch.

**Actual behavior:**
After adding the dependency, I get an unexpected compilation error coming from jodit code.
```
node_modules/jodit/src/core/ui/helpers/get-control-type.ts:29:13 - error TS1109: Expression expected.
```

**Suggestion**: 
Use older assignments method for retro-compatibility?
Or maybe add a peerDependencies entry for typescript >=4 ?

Thanks for the wonderful editor

**Comment by andrem0** [comment]
@xdan I'm getting this error as well.

- Jodit v 3.6.5
- jodit-react v 1.0.74
- Typescript v 4.3.0
- Target: ES5

Wouldn't it be just as fine doing it like this?
```
if (!controls)
    controls = Config.defaultOptions.controls;
```
