### ISSUE TITLE
defaultHandlerSuccess() config option get ignored when uploading a file using the UI menu for image and file.

### ISSUE THREAD

**Issue by stevekim** [xdan/jodit#64]
**Jodit Version:**  3.1.95

When uploading a file using copy & paste or direct drag and drop to the textarea, it's respecting the defaultHandlerSuccess() configured as an init option. However, when selecting a file or drag and drop using the editor's UI menu, it doesn't seem to be respecting it any more. It just defaults to the original code.

**Comment by stevekim** [comment]
I have a solution for this issue.
In the Widget.ts, line273, it needs to be changed to:

new Uploader(editor).bind(dragbox, (resp: UploaderData) => {
                if (typeof(editor.options.uploader.defaultHandlerSuccess || callbacks.upload) === 'function') {
                    (editor.options.uploader.defaultHandlerSuccess || callbacks.upload).call(editor, {
                        baseurl: resp.baseurl,
                        files: resp.files,
                        path: resp.path,
                        isImages: resp.isImages,
                        messages: resp.messages
                    });
                }
                close();

**Comment by NGumby** [comment]
I have the same problem

**Comment by sammael1106** [comment]
same!

**Comment by marchaos** [comment]
Same with me.

**Comment by Nicholass** [comment]
Hi! Are any updates planned on this? Maybe @stevekim 's fix could be done as a Pull Request?

**Comment by matteobassan** [comment]
Same here.

**Comment by JordanMunroe** [comment]
How is this still an issue more than a year later? (v 3.2.55)

**Edit**: I went ahead and created a PR for the above fix
#288
