### ISSUE TITLE
Uncaught TypeError: t.sourceName is undefined

### ISSUE THREAD

**Issue by Andrewsuares** [xdan/jodit#641]
**Jodit Version:**  3.6.1

**Browser:**  FF
**OS:**  Windows 8.1
**Is React App:**  False

**Expected behavior:**
On click of the browse button in images, filebrowser needs to show thumbnails

**Actual behavior:**
Modal appears without thumbnails.  Error in the console.
Uncaught TypeError: t.sourceName is undefined

**Comment by Andrewsuares** [comment]
It appears to be a problem with the response API for the filebrowser. Did something change in the API response? If I use my API which worked in the previous 3.5 version, it results in the error above. Did something change in the API?

**Comment by xdan** [comment]
Yes, the back end has been updated. Therefore, there was a release of 3.6. The handle now returns the list of sources as an array
