### ISSUE TITLE
Feature request: allow disabling imageDefaultWidth (using actual image with as default)

### ISSUE THREAD

**Issue by Uninen** [xdan/jodit#642]
Current uploading functionality inserts image using `imageDefaultWidth` configuration. It would be really helpful to allow inserting / uploading images with their actual size instead of a predefined value.

**Comment by xdan** [comment]
Hi @Uninen , just define this option as null
```js
Jodit.make('#editor', {
    imageDefaultWidth: null
})
```

**Comment by Uninen** [comment]
Oh, that works well. Thanks! 👍
