### ISSUE TITLE
[BUG] Inserting images/videos scrolls user to top of text area

### ISSUE THREAD

**Issue by tetreum** [xdan/jodit#644]
Incredible editor, fast to setup and simple! TY FOR CREATING IT!
Now let's head to the bug:

**Jodit Version:**  3.6.1 CDN

**Browser:** Chrome
**OS:**  Windows
**Is React App:**  False

**Explanation**

Same thing that was happening here: https://github.com/xdan/jodit/issues/519 but when inserting images and videos.

It can be tested here:
1. https://tetreum.github.io/brickcraft/?/blog-editor
2. Select as entry to edit `Devblog 1 ....`
3. Scroll down and add an image or a video at the end of the post. 
BOOM it will scroll up.

**Comment by azurre** [comment]
Any news about that?

Also it could be reproduced by clicking on image when editor isn't  focused
