### ISSUE TITLE
Font-size reset on click bold, italic or underline

### ISSUE THREAD

**Issue by jallewa** [xdan/jodit#65]
**Jodit Version:**  3.2.6

**Code**
There is no code yet.

**Expected behavior:**
No font-size reset on click bold, italic or underline

**Actual behavior:**
Whether inline editor or normal: The font size is always reset if you click bold, italic or underline.

Example: Set the font size to 30 and then click bold.

Is there perhaps a workaround or is this a bug?

**Comment by xdan** [comment]
Fixed in 3.2.7
