### ISSUE TITLE
Weird character '&#65279;' causes Chinese input methods work wrong.

### ISSUE THREAD

**Issue by vylan** [xdan/jodit#66]
**Jodit Version:**  3.2.6
**Description**

When insert a new line, '&#65279' appears. It will cause Chinese input methods work wrong (See the following pic). I've tried to remove the character by hand, problem solved, So the problem is how to remove it by default?

![image](https://user-images.githubusercontent.com/8390531/41637908-1bf54f1c-7489-11e8-9153-064170b21b3d.png)

**Expected behavior:**
Remove this character by default.

**Comment by vylan** [comment]
The real reason is removing invisible chars if node has another chars when 'keyup' fires. So I remove that function.

**Comment by sid-ihycq** [comment]
> The real reason is removing invisible chars if node has another chars when 'keyup' fires. So I remove that function.

Please explain it in detail, tks!
