### ISSUE TITLE
<br> tags are removed when directly before a closing tag

### ISSUE THREAD

**Issue by ZdejPoham** [xdan/jodit#664]
**Jodit Version:**  3.6.x

**Browser:**  Any
**OS:**  Any
**Is React App:**  false

**Steps to reproduce:**
Visit Jodit demo page https://xdsoft.net/jodit/play.html. In editor make a line-break (shift+enter) at the end of "Illum mallem levares, quo optimum atque humanissimum virum, Cn." - which has a light-yellow background. You can check in code-view that the `<br>` tag was created just before the `</mark>` closing tag.
Now in wysiwyg view move the cursor around (using arrow keys or mouse) and notice, that the `<br>` was removed.
I have tried and obsereved this in FF, Chrome and Edge on Linux and Windows 10.

**Expected behavior:**
If I insert a `<br>` tag anywhere it should stay there.

**Actual behavior:**
The `<br>` tag is removed if it is directly before a closing tag.

**Comment by NickR49** [comment]
`<br>` tag removal is causing an issue for me with migrating HTML into Jodit from another editor.

**Comment by lbrcs** [comment]
hi there, seeing the exact same behaviour in our implementation as well as in the jodit playground. is there a workaround so far?  @xdan
