### ISSUE TITLE
Selection insertNode() Works, But Not eachSelection()

### ISSUE THREAD

**Issue by dqjauthentrics** [xdan/jodit#666]
**Jodit Version:**  3.5.4

**Browser:**  
N/A
**OS:**  
N/A
**Is React App:**  
False
**Code**

```js
this.editor.selection.eachSelection((node: any) => {
    console.log('each:', node);  // never appears
});
this.editor.selection.insertNode(img); // this works, but always at beginning position
```

**Expected behavior:**
Selected text would be shown in the console  log.  

**Actual behavior:**
Text is selected in the editor, but does not show up here.  The insertNode() always inserts at the start, not replacing what is selected.

**Comment by dqjauthentrics** [comment]
I have tried selection.save() and selection.restore(), just in case, since it is based on a toolbar button click that summons a custom dialog.  The text remains highlighted, but not available in the code.

**Comment by dqjauthentrics** [comment]
It wasn't clear from the documentation, but I tried saving the value from the selection.save and passing it to the restore, and that appears to work.

**Comment by dqjauthentrics** [comment]
When selection.save() is called, it destroys the selection.current() selection, which is needed by the caller.  If I try to save selection.current() to a variable (using cloneDeep), it isn't usable.

The process I'm trying to support is a formula editor that produces an SVG image. When I select that image, it uses that selection to populate the formula editor.  This works great, except that I can't replace that image on completion of formula editing, because Jodit somehow loses the selection.  If I use selection.save() or copy the selection.current(), the value is lost and not available to the caller.  It's like the Heisenberg principle in physics; as soon as you try to capture it, it isn't available.

**Comment by xdan** [comment]
Try this code in the latest version (this.editor.s.save is called automatically on onBlur)
```js
this.editor.s.focus();
this.editor.s.restore();
this.editor.selection.insertNode(img);
```
