### ISSUE TITLE
The editor is very slow when working with tables in IE

### ISSUE THREAD

**Issue by StukalovSS** [xdan/jodit#673]
In IE, if you create a table, the editor starts to slow down.

**Jodit Version:**  3.6.15

**Browser:**  IE
**OS:**  Windows
**Is React App:**  False

**Expected behavior:**
The editor works in IE with tables as well as in other browsers.

**Actual behavior:**
The editor starts to slow down, when I try to work with tables in IE. It is almost impossible to enter text into any cell of the table, the size of the table is resized with a huge delay.
The bug is reproducible in the playground in "div" mode and "iFrame" mode.

**Comment by xdan** [comment]
Please, try in the latest version. Should be fixed
