### ISSUE TITLE
Remember last opened folder with FileBrowser

### ISSUE THREAD

**Issue by saosangmo** [xdan/jodit#675]
**Jodit Version:**  3.6.16

**Browser:**  Chrome/IE/Safary/FF
**OS:** Mac
**Is React App:**  False

**Context**
I have a folder tree:

Root
- Folder 1
- - Folder 1.1
- - Folder 1.2
- Folder 2
- - Folder 2.1
- - - Folder 2.1.1
- - - Folder 2.1.2
- - Folder 2.2
- ....

**Expected behavior:**
Today, I only work with folder name "Folder 2.1.2", I upload some files into it. Then I insert some images into editor area. Some days after, I can not remember the last folder name I worked.

**Actual behavior:**
Always open the root folder.

**Comment by paulgodard** [comment]
Hi.  I am struggling with the file manager... can you help with a simple working example?
