### ISSUE TITLE
isUrl add rtmp schema

### ISSUE THREAD

**Issue by getchu** [xdan/jodit#677]
**Jodit Version:**  3.6.*

**Browser:**  
**OS:**  
**Is React App:**  

**Code**

```js
jodit\src\core\helpers\checker\is-url.ts

return ['https:', 'http:', 'ftp:', 'rtmp:', 'file:'].includes(url.protocol);
```

**Expected behavior:**

rtmp:

**Actual behavior:**

dosn't have rtmp

**Comment by getchu** [comment]
[add video tag] (https://github.com/xdan/jodit/issues/676)

**Comment by xdan** [comment]
Hi @getchu Can you create PR?
