### ISSUE TITLE
Remove No follow option

### ISSUE THREAD

**Issue by Tomk77** [xdan/jodit#68]
**Jodit Version:**  3.1

**Expected behavior:**
I'm missing an option to remove the no follow option in the hyperlink:
https://i.imgur.com/uWJOGye.png

**Actual behavior:**
An option to remove this button.

I can't find it in the documentation, so I assume it's not possible. Could you let me know if it is, and possibly add the option?

**Comment by Tomk77** [comment]
Thanks

**Comment by xdan** [comment]
Added two options https://xdsoft.net/jodit/doc/options/link/
 "noFollowCheckbox": true,
  "openInNewTabCheckbox": true
