### ISSUE TITLE
TypeScript error in node_modules/jodit/src/core/component/view-component.ts(52,11): ';' expected.

### ISSUE THREAD

**Issue by serhiibartkiv** [xdan/jodit#685]
50 | 
    51 |        /** @override */
  > 52 |        override destruct(): any {
       |                 ^
    53 |                this.j.components.delete(this);
    54 |                return super.destruct();
    55 |        }

**Comment by mburakkalkan** [comment]
![IMG_1280](https://user-images.githubusercontent.com/4182925/122353496-c854bb80-cf58-11eb-8bc9-f57fe4f5a327.jpg)

Same here !!

**Comment by xdan** [comment]
It is TypeScript 4.3.2 override  https://github.com/xdan/jodit/blob/3.7.1/CHANGELOG.MD#371

**Comment by mburakkalkan** [comment]
> It is TypeScript 4.3.2 override https://github.com/xdan/jodit/blob/3.7.1/CHANGELOG.MD#371

So what is the solution?

**Comment by danz232** [comment]
I have the same issue and haven't found any workaround yet.

**Comment by danz232** [comment]
I fixed the issue by upgrading Typescript to 4.3.4.

**Comment by hrahimi270** [comment]
You need to upgrade it to the newest version of the typescript.

**Comment by JosephG3001** [comment]
Upgraded Typescript to 4.3.4.  Got another error:

```
C:/a/b/node_modules/jodit/src/core/helpers/utils/utils.ts
TypeScript error in C:/a/b/node_modules/jodit/src/core/helpers/utils/utils.ts(187,14):
Argument of type 'string' is not assignable to parameter of type 'never'.  TS2345

    185 |
    186 |       for (const key in obj) {
  > 187 |               props.push(key);
        |                          ^
    188 |       }
    189 |
    190 |       return props;
```

EDIT:

I see there's an outstanding PR that should fix this: https://github.com/xdan/jodit/pull/697
