### ISSUE TITLE
TypeScript error when building my project with Jodit. (Easy solution suggested)

### ISSUE THREAD

**Issue by mendes-jc** [xdan/jodit#693]
**Jodit Version:**  3.7.1

**Browser:**  
**OS:**  Linux
**Is React App:**  True

**Code**

**src/core/helpers/utils/utils.ts** - line 179
```ts
export const keys = (obj: object, own: boolean = true): string[] => {
	if (own) {
		return Object.keys(obj);
	}

	const props = [];

	for (const key in obj) {
		props.push(key);
	}

	return props;
};
```

**Expected behavior:**
I'm using Jodit in my React project, so I would expect it would compile with my project withou any type problems.

**Actual behavior:**
When compiling my project, TypeScript is throwing an error on the statement:
```ts
props.push(key).
```
It says: **TS2345: Argument of type 'string' is not assignable to parameter of type 'never'**

When declaring **const props = []**, for some reason, it is giving the **props** variable the **never[]** type.

**Solution suggestion:**

One easy way to solve it, without causing any side-effects, would be declaring the **props** variable as a **string[]**. So the final code would look like:

**src/core/helpers/utils/utils.ts** - line 179
```ts
export const keys = (obj: object, own: boolean = true): string[] => {
	if (own) {
		return Object.keys(obj);
	}

	const props : string[] = [];

	for (const key in obj) {
		props.push(key);
	}

	return props;
};
```

I tested this, changing the statement inside my node_modules folder. It would be amazing if you could publish it so I can solve my production problem :pray:

**Comment by hrahimi270** [comment]
Same issue here.
 Also tested with the same version of typescript that Jodit is using (4.3.2).

**Comment by hugomaxbr** [comment]
Same problem here

**Comment by ElladanTasartir** [comment]
Same, it's been really impacting my work

**Comment by patrick-bf** [comment]
same here
