### ISSUE TITLE
The underline remains black when colouring the text

### ISSUE THREAD

**Issue by AnastasiiaChaplits-zz** [xdan/jodit#701]
**Jodit Version:**  3.4.xxxxx

**Browser:**   Chrome
**OS:**   Mac
**Is React App:**   True

**Code**

```js
// A *self-contained* demonstration of the problem follows...
```
The issue happens when clicking first Underline, and after this Color Picker
![ezgif com-gif-maker (45)](https://user-images.githubusercontent.com/49317594/125799489-e93c9352-7252-4218-9e4a-363de3b710cf.gif)

**Expected behavior:** The underline is coloured with the text

**Actual behavior:** The underline is always black

**Comment by xdan** [comment]
Fixed in 3.8.2
