### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [xdan/jodit#702]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by xdan** [comment]
Added [SECURITY.md](https://github.com/xdan/jodit/blob/master/SECURITY.md) Thank you!

**Comment by ready-research** [comment]
@xdan Is there any update on huntr reports?
https://www.huntr.dev/bounties/a278cd3e-d305-40e9-a7cc-5c77808d150b/
https://www.huntr.dev/bounties/d1f61911-b21f-44f8-a7c0-6742cea26c20/

**Comment by xdan** [comment]
@JamieSlome Thank you! Fixed in 3.8.3

**Comment by ready-research** [comment]
@xdan Please validate the above 2 reports by clicking `mark as valid` and also please `confirm the fix`. Thank you.
