### ISSUE TITLE
Popup doesn't follow the toolbar on scroll

### ISSUE THREAD

**Issue by sammael1106** [xdan/jodit#703]
**Jodit Version:**  3.7.2

**Browser:**  Chrome
**OS:**  Mac
**Is React App:**  False

If Jodit has `overflow: auto` parent, it's popups stops repositioning on scroll. You can see this on playground page, if you'll add `overflow: auto` to `.uk-offcanvas-content` element.
![image](https://user-images.githubusercontent.com/2659283/126333045-78a25774-c512-4e16-a58d-04c85631e23b.png)

**Expected behavior:**
Opened popup will follow the toolbar

**Actual behavior:**
Opened popup has fixed position on page

**Comment by xdan** [comment]
Fixed in 3.8.3
