### ISSUE TITLE
Font and font size settings are not applied to all text if part of it has been changed earlier

### ISSUE THREAD

**Issue by StukalovSS** [xdan/jodit#706]
**Jodit Version:**  3.5.1 - 3.7.2

**Browser:**  all
**OS:**  all
**Is React App:**  False

**Introductory**
In the unformatted text I entered, I highlight part of the word and apply a font size style to it, for example, 24px. 
![image](https://user-images.githubusercontent.com/34316026/126993739-72869b21-27a8-45d0-8ed7-d17d16825ccf.png)
Then I select the entire word and apply a 8px font size style to it.

**Expected behavior:**
The new font size value is applied to all selected text.

**Actual behavior:**
The new font size value applies only to earlier unformatted text. The fragment that was changed earlier retained the previous value of the font size.
![image](https://user-images.githubusercontent.com/34316026/126993849-17564b87-8d6e-4a3b-9993-f2269ccb89bf.png)

A similar situation with font settings.
![image](https://user-images.githubusercontent.com/34316026/126994723-1472dc2a-c75e-43d2-a2eb-4e95642a75b2.png)
![image](https://user-images.githubusercontent.com/34316026/126994774-c37d8341-04f4-4cd1-a518-9564b76bd7ce.png)

**Comment by Surton** [comment]
Same issue. Any solutions?
