### ISSUE TITLE
Mismatched anonymous define() module: function(){return{js_beautify:t}} - AURELIA

### ISSUE THREAD

**Issue by eltonstrydompersonal** [xdan/jodit#710]
**Jodit Version:**  3.7.2

**Browser:**   Chrome, Edge, Mozilla
**OS:**  

 generateJodit() {
    this.jodit = new Jodit('#editor', {
      "uploader": {
        "insertImageAsBase64URI": true
      },
      "buttons": "source,bold,italic,underline,strikethrough,eraser,ul,ol,indent,outdent,left,font,fontsize,brush,image,copyformat,paste,table, preview, print, fullsize"
    });
  }

When running jodit I get the following error:

![image](https://user-images.githubusercontent.com/71158801/127880451-ebc3963f-86f1-4d59-a8ba-8d5c6ff892c6.png)

I am able to use jodit but it does break some elements on my web page. 
I am using aurelia.io framework. Have anyone dealt with this before?

**Comment by xdan** [comment]
Try to disable this option
https://xdsoft.net/jodit/doc/options/beautifyHTML/
new Jodit('#editor', {beautifyHTML: false})

**Comment by eltonstrydompersonal** [comment]
> Try to disable this option
> https://xdsoft.net/jodit/doc/options/beautifyHTML/
> new Jodit('#editor', {beautifyHTML: false})

You are a legend. Thanks works 100%.
