### ISSUE TITLE
Feature Request: Make  editor ui elements colorizable by config

### ISSUE THREAD

**Issue by janniemeyer** [xdan/jodit#719]
I am using jodit in an angular Project. I have been trying all possibilites I could think of, yet  I haven't been able to find a way to change the color for most ui elements of jodit editor. It would be great if one could set their color from the configuration options. I was thinking of something like this:
var editor = new Jodit("#editor", {
  "toolbarBackground-color":  '#fafafa'
});

**Comment by xdan** [comment]
Added option https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#rocket-new-feature in 3.8.2
