### ISSUE TITLE
Please publish compiled typescript types instead of pointing to the uncompiled src - should fix many issues.

### ISSUE THREAD

**Issue by dylang** [xdan/jodit#720]
**Jodit Version:**  3.7.2

**TypeScript:**  4.4.2

## Code

```js
import type { IJodit } from "jodit";
```

## Expected behavior

No TypeScript errors when importing types of Jodit.

## Actual behavior

```
tsc:
node_modules/jodit/src/core/selection/style/apply-style.ts:365:9 - error TS2339: Property 'nodeName' does not exist on type 'never'.

365     elm.nodeName.toLowerCase() !== this.style.defaultTag);
            ~~~~~~~~

node_modules/jodit/src/core/selection/select.ts:91:31 - error TS2339: Property 'getSelection' does not exist on type 'ShadowRoot'.

91    return this.j.o.shadowRoot.getSelection();
                                 ~~~~~~~~~~~~

node_modules/jodit/src/core/selection/select.ts:174:18 - error TS2339: Property 'caretPositionFromPoint' does not exist on type 'Document'.

174     if (this.doc.caretPositionFromPoint) {
                     ~~~~~~~~~~~~~~~~~~~~~~

node_modules/jodit/src/core/selection/select.ts:175:29 - error TS2339: Property 'caretPositionFromPoint' does not exist on type 'Document'.

175      const caret = this.doc.caretPositionFromPoint(x, y);
                                ~~~~~~~~~~~~~~~~~~~~~~

node_modules/jodit/src/core/selection/select.ts:185:19 - error TS2531: Object is possibly 'null'.

185      rng.setStart(caret.startContainer, caret.startOffset);
                      ~~~~~

node_modules/jodit/src/core/selection/select.ts:185:41 - error TS2531: Object is possibly 'null'.

185      rng.setStart(caret.startContainer, caret.startOffset);
```

## To Reproduce

Full reproduction here: https://stackblitz.com/edit/node-36qyyf?file=index.ts

Run `tsc` in the terminal there to see the errors.

Just importing the IJodit interface is enough to cause it.

## What about `"skipLibCheck": true`?

That is set in this example. `skipLibCheck` can only skip pre-compiled type definitions (`d.ts`), for Jodit, it *must* compile the `src/**/*.ts` files, which result in the errors above.

## How can we fix this?

1. Never point to the `./src` in any `.d.ts`, such as https://github.com/xdan/jodit/blob/master/index.d.ts#L8
3. Use `tsc` to compile the code instead of, or in addition to babel.
4. Include the generated `.d.ts` from `tsc`.
5. Point to _those_ types in the `package.json`.
6. Use `files` in `package.json` as an array of what files you want to include in the published package. Do not include `src`, `test`, or other directories unnecessary for developers using jodit, such as `docker` and `examples`. As a bonus, this will make the package smaller and faster to install.

**Comment by JClackett** [comment]
Yeah also really struggling with this, have to keep downgrading my Typescript to 4.3.5 to get it to work again

**Comment by xdan** [comment]
@dylang Try you playground with 3.8.2. Should be fixed

**Comment by dylang** [comment]
@xdan Thank you for looking into this problem and working towards addressing it!

It first glance it seems like those errors are no longer happening with the latest TypeScript or beta for the next version! 

However, I'm not having luck getting the API to work as documented.

```ts
// ERROR: This expression is not constructable. Type 'IJodit' has no construct signatures.
var editor = new Jodit('#editor');
editor.value = '<p>start</p>';
```

```ts
// ERROR: Property 'make' does not exist on type 'IJodit'
const editor = Jodit.make('#editor');
editor.value = '<p>start</p>';
````

https://stackblitz.com/edit/node-36qyyf?file=index.ts

```
"name": "jodit",
"version": "3.8.2",
```

It seems like the types in the published code still points to the source instead of compiled `d.ts` files.

**Comment by xdan** [comment]
@dylang  Please try again. Added type generation, but I couldn't do it with `tsc`. For some reason it does not compile the ./src/types folder
```bash
tsc --project . --declaration --declarationDir types --outDir types --emitDeclarationOnly --removeComments false
```
It does not work correct. 

So I did like this

```bash
cp -r ./src/types ./types/types && tsc --project . --declaration --declarationDir types --outDir types --emitDeclarationOnly --removeComments false
```
There are also problems with the `types/styles/icons/index.d.ts` file, there should be svg files, but they are not.
There seem to be no errors in your playground

**Comment by dylang** [comment]
Still lots of problems, maybe from this code in `types/index.d.ts`:

```ts
import './styles';
import { Jodit as DefaultJodit } from './jodit';
export declare const Jodit: typeof DefaultJodit;
```

* Because of that `const` there's no `type` called `Jodit`.
* Why are we importing `styles`?

I've updated the playground example: https://stackblitz.com/edit/node-36qyyf?file=index.ts

This should probably be something more like

```ts
export { Jodit } from './jodit';
```

> For some reason it does not compile the ./src/types folder

```
--declarationDir types --outDir types
```

These are the same directory?

Also check your `tsconfig.json` `includes` and `excludes` paths. Seems like you are also using `files`, I've never seen a project need to use `files`, but I'm not an expert in this.

I also would think any file you want compiled needs to be `.ts`, not `.d.ts` - because those are already definitions. The `.ts` should be imported where needed, not assumed global, otherwise we'll need to have your tsconfig settings for `types`. But, again, I'm not an expert in this, so I could be wrong.

**Comment by xdan** [comment]
@dylang Check now please.

**Comment by dylang** [comment]
Stackblitz suddenly [broke](https://github.com/stackblitz/webcontainer-core/issues/342) so I can't test there, but in one of our projects it seems to be working! I'll have more to report tomorrow. Great work @xdan!

Just so you know, the releases page doesn't seem to be getting updated with these fixes: https://github.com/xdan/jodit/releases

**Comment by dylang** [comment]
@xdan types seem to be working! I think this ticket can be closed!

I also appreciated the the change from `IJodit` to `Jodit` for the interface. That was the only change we needed in our code after upgrading to the latest TypeScript and Jodit.
