### ISSUE TITLE
cleanHTML replaceOldTags doesn't seem to do anything

### ISSUE THREAD

**Issue by presleyd** [xdan/jodit#728]
**Jodit Version:**  3.8.5

**Browser:**  FF
**OS:**  Windows
**Is React App:**  False

**Code**

```js
var editor = new Jodit('#editor', {
    "cleanHTML": {
        "replaceOldTags": {
            'i':'em',
            'b':'strong',
            'h1':'p',
         },
     }
});
```

**Expected behavior:** 

Any < i> tags will get converted to < em> tags, < b> to < strong> and < h1> to < p> when pasting in HTML

**Actual behavior:** 

Nothing seems to happen to any of the existing tags. allowTags works fine for completely removing a tag.

**Comment by waynecamara061** [comment]
ldlçskd
kdlsdksldks]lçsldl
kldskdlskd
kdlsdks
