### ISSUE TITLE
Bug Overflow Important

### ISSUE THREAD

**Issue by Faks** [xdan/jodit#73]
**Jodit Version:**  v.3.1.39 
Project is based upon Admin Press but with latest Bootstrap 4.1 with heavy modifications and many customization that are not part of original version.

Image
![Image of dropdown bug](https://i.paste.pics/3GF1M.png)

**Expected behavior:**
Dropdown not to overflow the container of body

**Actual behavior:**
Dropdown overflow textarea body

**Comment by xdan** [comment]
For parent container set overflow: "auto";
