### ISSUE TITLE
all popups and dialogs are outside shadow dom 

### ISSUE THREAD

**Issue by grzegorzewskiflyingdog** [xdan/jodit#731]
if jodit is initialized inside shadow dom the editor itself is inside  shadow dom which is expected behaviour, but all dialogs and popups create by editor are outside, which requires adding jodit css to window, which is agains idea of using shadow dom.
Even if move back to shadow dom by changing code : 
 
 
             ```
           const box = c.element(tag, {
                            className: `jodit jodit-${(0,_helpers___WEBPACK_IMPORTED_MODULE_2__.kebabCase)(name)}-container jodit-box`
                        });
                        box.classList.add(`jodit_theme_${view.o.theme || 'default'}`);
                        //body.appendChild(box); 
                       // change to ::
                        shadowrootelement.appendChild(box);
 


 this solves the css problem but then clicking anywhere even inside or outside popup, close this popup(should close only on outside click). So it could be solved something like : 

   ```
  
  closeOnOutsideClick(e) {
                          if (!this.isOpened) {
                              return;
                          }
                          if (!e.target) {
                              this.close();
                              return;
                          }
                          const box = ui_element/* UIElement.closestElement */.u.closestElement(e.target, Popup);
                          if (box && (this === box || box.closest(this))) {
                              return;
                          }
                          //this is fix for shadow dom
                          let haspopupinshadow = false;
                          e.composedPath().forEach((el)=>{if(el.classList && el.classList.contains('jodit-popup-container')) haspopupinshadow=true;})
                          if(haspopupinshadow) return;
  
                          this.close();
                      }

//The same problem for editing table cells menu.

**Comment by xdan** [comment]
Should be fixed in 3.8.7

**Comment by astroforgit** [comment]
Ok this is kind of fixed, but not all.  All popups are is shadow dom but still 2 problems : 
1) click button image upload, then the popup is ok, but then clicking on this popup closes it, instead of making click action.
2) if you create a table, there is no edit actions for table rows(little menu popup)
3) i havent test it  in your fix, but there could be problem , when you insert image, then on edit it (click pensil on popup image menu), there should be another popup, which should be in shadow dom as well.

**Comment by grzegorzewskiflyingdog** [comment]
Ok this is kind of fixed, but not all. All popups are is shadow dom but still 2 problems :

1) click button image upload, then the popup is ok, but then clicking on this popup closes it, instead of making click action.
2) if you create a table, there is no edit actions for table rows(little menu popup)
(3)(maybe) i havent test it in your fix, but there could be problem , when you insert image, then on edit it (click pensil on popup image menu), there should be another popup, which should be in shadow dom as well.

**Comment by Infuser** [comment]
I have the most up to date version of Jodit installed our project sits within multiple shadowroots but when I open jodit font-picker popup appears outside of shadowroot, is there anything I need to configure to get this working?
