### ISSUE TITLE
When I merged some cells by dragging it to change its width.

### ISSUE THREAD

**Issue by jiangji1** [xdan/jodit#737]
When I merged some cells by dragging it to change its width.
It occurs a bug.
in the file, src/modules/table.ts, it should be modified like the following:
in the function of setColumnWidthByDelta 
line: 914
In the following, what it is your codes before I modified them:
```
for (i = 0; i < box.length; i += 1) {
	w = box[i][j].offsetWidth;
	percent = ((w + delta) / table.offsetWidth) * 100;
	Table.__mark(
		box[i][j],
		'width',
		percent.toFixed(consts.ACCURACY) + '%',
		marked
	);
}
```

after I modified, the codes: 
```
for (i = 0; i < box.length; i += 1) {
	let left = box[i][j - 1]
	, cur = box[i][j]
	if (left === cur) {
		// @ts-ignore
		w += box[i][j].offsetWidth
	} else {
		w = box[i][j].offsetWidth;
	}
	// @ts-ignore
	percent = ((w + delta) / table.offsetWidth) * 100;
	Table.__mark(
		cur,
		'width',
		percent.toFixed(consts.ACCURACY) + '%',
		marked
	);
}
```

**Comment by xdan** [comment]
@jiangji1 Hi. I didn't understand the essence of the bug. Please describe in more detail what is wrong?

**Comment by jiangji1** [comment]
![2021-10-20-下午6 07 13](https://user-images.githubusercontent.com/37925842/138075642-e5de058b-a3c5-4560-9a27-45c602de8d74.gif)
