### ISSUE TITLE
Change html tags when list style on/off

### ISSUE THREAD

**Issue by EiThinzarWinMaung** [xdan/jodit#738]
**Jodit Version:**  3.4.29

**Browser:**  Chrome/IE/FF
**OS:**  Windows/Mac
**Is React App:**  

I didn't get the original typed style of html tags after removing list style of text.
For example,
step 1 => type in editor "Apple [enter] Orange [enter] Mango" 
step 2 => view in source view " `p` Apple `/p` `p` Orange `/p` `p` Mango `/p` "
step 3 => select all text and choose one of list style (to enable style)
step 4 => select again that list style (to disable style)
step 5 => view in source view " `p` Apple `br` Orange `br` Mango `br` `/p` " 
                 There is changed tags. 

I used v3.4.29. Although I'd like to use updated version but latest version is not available on IE11 browser.

**Expected behavior:**
`p` Apple `/p` `p` Orange `/p` `p` Mango `/p` (original typed style)

**Actual behavior:**
`p` Apple `br` Orange `br` Mango `br` `/p`

**Comment by xdan** [comment]
@EiThinzarWinMaung Fixed work in IE11. But haven't fixed this error yet.
