### ISSUE TITLE
IdleRequestCallback Type is missing

### ISSUE THREAD

**Issue by netizen01** [xdan/jodit#743]
Compiling in a TypeScript project and getting this with the latest release:
`Cannot find name 'IdleRequestCallback'.`

**Jodit Version:**  3.9.3

**Browser:**  Typescript compiler
**OS:**  macOS 16
**Is React App:** no - Vue App, using the Jodit lib directly

**Comment by xdan** [comment]
Can you use TS 4.4 https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029 ?
