### ISSUE TITLE
Problem with textarea container

### ISSUE THREAD

**Issue by s-renier-taonix-fr** [xdan/jodit#745]
**Jodit Version:**  3.9.4

**Browser:**  FF
**OS:**  Linux
**Is React App:**  False

**Code**

```js
<!doctype html>
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jodit/3.9.4/jodit.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jodit/3.9.4/jodit.min.js"></script>
</head>
<body>
  <textarea id="editor">&lt;foobar&gt;</textarea>
  <script>var editor = new Jodit('#editor');</script>
</body>
</html>
```

**Expected behavior:**
```html
<p>&lt;foobar&gt;</p>
```

**Actual behavior:**
```html
<p>
    <foobar></foobar>
</p>
```

When we use a textarea container for the wysiwyg, the html entities are decoded !
No problem with a div container.

**Comment by xdan** [comment]
It is expected behaviour =) 
This is not done by Jodit, but this is how html works
Try to just assign text to value
```js
document.getElementById('editor').value = '<div>test</div>'
```

**Comment by s-renier-taonix-fr** [comment]
Oh ok!
Sorry for the wrong issue!
So I changed my <textarea> for a <div>, it's work fine now.

You can close this ticket.
