### ISSUE TITLE
FontSize button does not appear as a dropdown on Firefox.

### ISSUE THREAD

**Issue by AndreeaStirbu** [xdan/jodit#752]
**Jodit Version:**  3.9.4

Browser: Firefox
OS:  Windows
Is React App: True

Expected behavior:
Font Size button should be a dropdown

Actual behavior:
The dropdown does not work
![image](https://user-images.githubusercontent.com/33423894/142224630-c457bf32-a508-4a16-afdb-fd81bce07617.png)

**Comment by xdan** [comment]
Show me you code please

**Comment by AndreeaStirbu** [comment]
I am sorry, I cannot share my code, but I did not do anything special, just having the JoditEditor react component and the config object where I say what buttons I want in the toolbar. It now happens on Chrome as well.
This is the error that I get in the console log:
![image](https://user-images.githubusercontent.com/33423894/142853818-22258bf4-a01b-48f7-a4c1-3dd495cd655a.png)

Thank you for your time :)

**Comment by AndreeaStirbu** [comment]
I have fixed the issue, the config file was adding the "fontSize" button instead of "fontsize".
