### ISSUE TITLE
<style> tag wrapping problem

### ISSUE THREAD

**Issue by EdgarIsaiSC** [xdan/jodit#754]
**Jodit Version:**  3.9.6

**Browser:**  Chrome/FF/Opera
**OS:**  Linux
**Is React App:** True

**Expected behavior:**
Using the style tag should not be affected when using WYSIWYG

**Actual behavior:**
When I use `<style>` tag then WYSIWYG wraps it in `<p>` tag

same problem as in https://github.com/xdan/jodit/issues/620

**Comment by xdan** [comment]
Duplicate of #620
