### ISSUE TITLE
New lines are removed when pasting plain text in the jodit editor

### ISSUE THREAD

**Issue by kdeclerck** [xdan/jodit#755]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome
**OS:**  Windows
**Is React App:**  False

**Code**

I'm pasting this snippet into the Jodit Playground (https://xdsoft.net/jodit/play.html?enter=BR&defaultMode=3):
```
This text should be

on different

lines
```

**Expected behavior:**
I'd expect two br tags after each line so the resulting output in the WYSIWYG editor is the same as the original snippet you paste.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/20278305/144044451-50d8412c-0f0e-453d-9bf6-bf29a7a7aac6.png)

The output depends on where you copy the snippet from. If I paste it from the github issue here then the output is all on one line. If I paste it from notepad or without formatting (like in the screenshot above), the output is on three lines but doesn't have the additional new line in between them. The resulting html then contains one br after each line and the new line, but that new line doesn't translate to another new line in the WYSIWYG editor.

**Comment by lievenjanssen** [comment]
There's a bug in the nl2br replace function here: https://github.com/xdan/jodit/blob/master/src/core/helpers/html/nl2br.ts

Was looking into fixing it myself and open a PR.

@xdan do you know why `([^>])` is needed in the regular expression?
