### ISSUE TITLE
Page always scrolls to top of parent when editor gains focus

### ISSUE THREAD

**Issue by jonyen** [xdan/jodit#761]
**Jodit Version:**  3.8.5

**Browser:**  Chrome
**OS:**  Mac
**Is React App:**  True

**Code**

I have an application in which the editor is located at the bottom of the page. Whenever I click to enter the text editor, the page scrolls to the top of the parent window. I was looking at the code here and I noticed that `preventScroll` is not used here, and was wondering if it ever was working before. 
https://github.com/xdan/jodit/blob/master/src/core/selection/select.ts#L406

**Expected behavior:**
Should not jump to the top of the page when the editor gains focus

**Actual behavior:**
Scrolls to the top of the page whenever the editor gains focus

**Comment by xdan** [comment]
A specific case caused by a monkey patching prototype.js

**Comment by oshri6688** [comment]
@jonyen @xdan 
this issue still occurs when using `sourceEditor: 'area'` config ([demo](https://codesandbox.io/s/jodit-forked-wpvx43?file=/src/Editor.jsx))
