### ISSUE TITLE
Double click at div.jodit-wysiwyg create a new line 

### ISSUE THREAD

**Issue by LuisLima2002** [xdan/jodit#764]
This bug occurs at the jodit [playground](https://xdsoft.net/jodit/play.html)

**Expected behavior:**
When double clicking, the text in the last line  is selected 

**Actual behavior:**
When double clicking bellow the text in the editor, it apper a new p tag empty

**Comment by xdan** [comment]
It is expected  behaviour  https://xdsoft.net/jodit/docs/classes/config.Config.html#addNewLineOnDBLClick
