### ISSUE TITLE
What is support email address?

### ISSUE THREAD

**Issue by woowa-koronya** [xdan/jodit#768]
I wrote email to chupurnov@gmail.com 
(what is described on jodit pro website)
about license question 2021.12.21. 

but still today, There is no reply. 
Is this not correct email address?

If then, What is correct email address?

**Comment by xdan** [comment]
Yes, this is a correct email, but it is better to write questions about using the PRO version in the issue tracker https://xdsoft.net/jodit/pro/cab/issues

**Comment by woowa-koronya** [comment]
Thanks @xdan.
I wrote question about license on your comment's link.

If I wrote inappropriate question, then tell me.
I just wanna know communication method, before get pro or oem license.

**Comment by xdan** [comment]
Wrote answers https://xdsoft.net/jodit/pro/cab/issues/42073037-15e8-406f-86e9-71acae5b0474
