### ISSUE TITLE
Can't remove inserted video

### ISSUE THREAD

**Issue by sammael1106** [xdan/jodit#77]
**Jodit Version:**  3.2.9

_It can be repeated on playground without any additional options._ 

Insert the video iframe with button **"Insert youtube/vimeo video"** in any place of the content. Then set cursor on the line after and try to remove it with BACKSPACE/DELETE. It disappears on the moment and appears again in the same place. Video can be deleted only with whole text (CTRL+A) or through the source mode.

**Expected behavior:** I think video should be deleted with pressing BACKSPACE/DELETE or there should be popover on it with removing button (http://prntscr.com/kdrruz).

**Comment by ilyes-kechidi** [comment]
possible related issue #88
