### ISSUE TITLE
Form tag is getting removed on code view toggle

### ISSUE THREAD

**Issue by pranjalkoshti** [xdan/jodit#774]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome 97.0
**OS:**  Linux
**Is React App:**  true

**Expected behavior:**
When editing html with form elements, Form tag should be intact when toggeling between code view and normal view.
Tried with both jodit and jodit-react

**Actual behavior:**
Form tag is getting removed.

**Comment by vinodsonigara** [comment]
Same issue. How can we stop the editor from removing form tags
