### ISSUE TITLE
Pasting content from PDF to jodit editor, doesn't have any line breaks or styles as we copied

### ISSUE THREAD

**Issue by Rathikala** [xdan/jodit#779]
**Jodit Version:**  1.1.14

Browser:Chrome
OS:  Windows
Is React App:True

**Code**

Expected behavior:Pasted content should be in the same format as copied in PDF.

Actual behavior:Pasted content doesn't have any line break and style as it is in PDF.

PDF Content:
![PDFimage](https://user-images.githubusercontent.com/99397225/153397035-148f6d8c-3279-469f-b428-bcc190270ed2.png)

When pasted from PDF to editor (Keep as HTML and Insert only Text - doesn't have line break and style)
![JoditImage](https://user-images.githubusercontent.com/99397225/153397066-7a3d1cb3-e035-402c-876e-e21c484d980d.png)

**Comment by xdan** [comment]
When viewing a pdf document, the text is copied and not the HTML, so there is no hyphenation. This is how all editors work. It's more the viewer's fault than the editor's.
