### ISSUE TITLE
When {"enter": "BR"} option is enabled, pasting copied text is broken

### ISSUE THREAD

**Issue by stevekim** [xdan/jodit#78]
**Jodit Version:**  3.2.9

When copy and pate html or text, it removes the existing text in the editor and doesn't paste anything. This only happens when {"enter": "BR"} option is enabled.

**Comment by xdan** [comment]
In which browser does this happen?

**Comment by stevekim** [comment]
This happens on Chrome and Safari on Mac. 
When I enter several lines of text and then press the 'Command' key, then the editor removes all existing text. 
You can test it on https://xdsoft.net/jodit/play.html?enter=BR. Please remove the example text first.

**Comment by stevekim** [comment]
@xdan Any updates on this?
