### ISSUE TITLE
Cannot format table cells in PRO version

### ISSUE THREAD

**Issue by at1623** [xdan/jodit#786]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Mozilla
**OS:**  Windows

**Expected behavior:**

When a table cell is highlighted, an formatting panel should appear to allow you to format it e.g. change border color, background color etc. 

This occurs when you insert a table in the free demo and highlighting the cells (https://xdsoft.net/jodit/)

![](https://i.imgur.com/pCT3TnB.jpg)

**Actual behavior:**

These table/cell formatting options do not appear when cells are highlighted in the Pro or OEM versions. You can recreate this in the pro demo as well: https://xdsoft.net/jodit/pro/

![](https://i.imgur.com/8O0L15I.jpg)

**Comment by xdan** [comment]
Thank you! Fixed
