### ISSUE TITLE
Plugin to add div page-wrapper

### ISSUE THREAD

**Issue by wscode99** [xdan/jodit#787]
**Jodit Version:**  3.13.4

**Browser:**  Chrome/Safary/FF
**OS:**  Windows/Mac/Linux
**Is React App:**  False

**Code**

```js
Jodit.plugins.add("page-wrapper", function(editor) {
    editor.events.on("afterInit", function() {
      if (editor.value === "") {
        editor.value = "<div class='page-wrapper'></div>";
      }
    });
    editor.events.on("change", function(value) {
      var txt = "";
      if (value.indexOf("page-wrapper") > -1) {
        txt = value.replace("<div class=\"page-wrapper\">", "").replace("</div>", "");
      }
      editor.value = "<div class='page-wrapper'>" + txt + "</div>";
    });
  });
```

**Expected behavior:**
The default is to all elements be inside the "jodit-wysiwyg" ```<div>```.
Trying to create a plugin where all new or copy&pasted elements of editor (like p, ul, ol, hr, table, etc), be inside a new "page-wrapper" ```<div>``` which is a child of "jodit-wysiwyg" ```<div>```
**Actual behavior:**
After initialization, the "afterInit" event is fired and the ```<div>``` is corretly created, but when the user starts typing, the cursor position always goes to the top after each change, creating a new ```<p>``` for each typed character. For example, if the user type the word: "Test", the result in document is:

```js
<div aria-disabled="false" tabindex="-1" class="jodit-wysiwyg" contenteditable="true">
  <div class="page-wrapper">
    <p>t</p>
    <p>s</p>
    <p>e</p>
    T
  </div>
</div>
```
What modifications are needed to behave as expected?

**Comment by xdan** [comment]
Try that:
```js
editor.events.on("afterInit", function() {
      editor.editor.removeAttribute('contenteditable');
      editor.value = "<div contenteditable="true" class='page-wrapper' ></div>";
 });
```
but it's best to handle how it will end up being saved to the native input

```js
editor.events.on("afterGetValueFromEditor", function(data) {
    data.value = `<div class='page-wrapper' >${data.value}</div>`;
});
console.log(editor.value);
```
