### ISSUE TITLE
Ordered Bullets are getting changed to unordered bullets after copy and pasting within the editor

### ISSUE THREAD

**Issue by abhishek-v-sfs** [xdan/jodit#789]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome
**OS:**  Windows/Mac/Linux
**Is React App:**  True

If we are creating an ordered list and trying to copy and paste it in the editor, the bullets are getting changed to unordered bullets.

**Expected behavior:**
Bullets format should be same after copy and paste
<img width="901" alt="image" src="https://user-images.githubusercontent.com/69140032/156107647-497acd47-1692-4ada-90d5-ea387ecdbc76.png">

**Actual behavior:**
Bullets format is not maintained
<img width="911" alt="image" src="https://user-images.githubusercontent.com/69140032/156107684-81287772-b17e-416b-97c0-a175807380ea.png">

**Comment by abhishek-v-sfs** [comment]
Hi @xdan I found the issue, when we copy the ordered list, the ol tag is not being copied. Can you please point me in the right direction as to where the copy logic for the editor is handled?

**Comment by xdan** [comment]
Here it is probably necessary to correct not the copying logic, but the selection logic. If all UL/OL elements are selected, then the entire list must be selected there as well. I'll try to write a plugin for this

**Comment by abhishek-v-sfs** [comment]
I'm willing to be a contributor in this project. Please let me know if I can help in anyway.
