### ISSUE TITLE
Custom Bullets  from MS  word are replaced by default bullets

### ISSUE THREAD

**Issue by marygrace1235** [xdan/jodit#794]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome
**OS:**   Windows
**Is React App:**  True
When copy-paste the bullets from MS word and paste in the Jodit Editor ,it is replaced by default bullets.

**Expected behavior:**

![image](https://user-images.githubusercontent.com/90672801/157174174-57d2c78b-60a8-4ac7-9f3f-9c0118565a01.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/90672801/157174291-fa68de7d-4703-437c-98ad-e2b01d102510.png)

**Comment by xdan** [comment]
Unfortunately, the copied document does not contain the necessary information, the extra photos were removed and made into a regular list
