### ISSUE TITLE
Copy Paste image from MS Word is showing Broken Image 

### ISSUE THREAD

**Issue by marygrace1235** [xdan/jodit#795]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome
**OS:**   Windows
**Is React App:**  True
Copy paste the content with Image from MS Word to Jodit Editor,image is showing broken image

**Expected behavior:**
![image](https://user-images.githubusercontent.com/90672801/157175839-8e7c37fb-b981-48fe-b7c6-25d6c9455221.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/90672801/157175743-20a1818f-85a1-45f1-959b-ed5369614997.png)

**Comment by chijete** [comment]
Has the bug been resolved?
I keep getting the same wrong result.

**Comment by VanGoghDev** [comment]
Faced the same problem...
Jodit Version 3.24.1
Problem is that while pasting from word with text, jodit renders it`s like a file from clipboard

`<img width="499" height="182" src="file:///C:/Users/User/AppData/Local/Microsoft/Windows/Clipboard/HistoryData/%7B73077249-0BBB-41B7-9DA7-BC93291B5604%7D/%7BB8D8B04A-B5CA-4CE7-A3A1-26BC4D1BC50F%7D/ResourceMap/%7B7A8E8B7A-95BE-4C72-9C08-B91096E7E804%7D">`

But when copy paste **only** image it renders like base 64 image:

`<img src="data:image/png;base64,base_64data=" alt="">`

Any ideas how to solve it?

**Comment by mstein-kbi** [comment]
+1 same issue, maybe @xdan has a workaround since it is closed?
