### ISSUE TITLE
Copy paste the content from MS Word,  extra spacing between words

### ISSUE THREAD

**Issue by marygrace1235** [xdan/jodit#796]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome
**OS:**  Windows
**Is React App:**  True

Copy paste the content from MS Word to Jodit Editor showing extra spacing between  words
**Expected behavior:**
![image](https://user-images.githubusercontent.com/90672801/157178747-2ec7743a-f074-4f26-abca-5ae7289dd876.png)
![image](https://user-images.githubusercontent.com/90672801/157178880-32a4e27a-e054-4748-bc45-cf6dac8212af.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/90672801/157176843-75850137-de5e-4f6b-afb5-4530d4a9a207.png)

**Comment by xdan** [comment]
Can you attach a document here?
