### ISSUE TITLE
TypeScript doesn't recognize the constants that in `Jodit` 

### ISSUE THREAD

**Issue by oshri6688** [xdan/jodit#806]
**Jodit Version:**  3.15.3

**Browser:** Chrome 
**OS:** Windows  
**Is React App:** True  

**Expected behavior:**
All the constants should be defined in `Jodit` to be able to used it with TypeScript ([constants file](https://github.com/xdan/jodit/blob/0b5ecc0611faee0353592e502d6e5de898c5e2f8/src/core/constants.ts))

**Actual behavior:**
TypeScript doesn't recognize the constants that in `Jodit` (e.g. `MODE_SOURCE`)
![image](https://user-images.githubusercontent.com/45387790/158053041-1543f599-cf7b-4c23-a261-8a9ce45252bb.png)

**Comment by xdan** [comment]
Added `Jodit.constants`. Please use it instead. I don't know how to do it differently
