### ISSUE TITLE
Sass compile error Css3 min()

### ISSUE THREAD

**Issue by romarioliveira25** [xdan/jodit#809]
**Jodit Version:**  3.16.1

**Browser:**   Chrome
**OS:**   Linux
**Is React App:**   False

**Code**
No need. Issue is about conflict between CSS3 function and SASS.

The file [preview.less](https://github.com/xdan/jodit/tree/master/src/modules/file-browser/styles/preview.less) is using  css ``min()`` and when compile SASS importing jodit styles occurs the error ``SassC::SyntaxError: Internal Error: Incompatible units: 'px' and '%'``.

So, to fix it, how CSS3 is not case sensitive could be used something like ``Min()`` instead of ``min()`` preventing SASS compile errors.

**Expected behavior:**

**Actual behavior:**

**Comment by xdan** [comment]
Try now please

**Comment by romarioliveira25** [comment]
Fixed! Thanks.
