### ISSUE TITLE
If I click outside the editor, JoditEditor is re-rendering. means onBlur event is triggering.

### ISSUE THREAD

**Issue by naganand123** [xdan/jodit#816]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome
**OS:**  Windows
**Is React App:** True

**Code**

```js

const handelRichTextContent = (newContent: any) => {
        setEditorData(newContent);
    };
 <Box>
                    <JoditEditor
                        value={editorData}
                        config={config}
                        onBlur={(newContent: any) => handelRichTextContent(newContent)}
                        /> </Box> : <Box className={classes.editorSection} dangerouslySetInnerHTML={{ __html: editorData }}></Box>}
```

If I click outside the editor, JoditEditor is re-rendering. means onBlur event is triggering.
**Expected behavior:**
If I click outside the editor, onBlur event should not trigger.
**Actual behavior:**
If I click outside the editor, onBlur event is triggering

**Comment by xdan** [comment]
Why does onBlur cause you to redraw the editor? Are you changing your config for this event?
