### ISSUE TITLE
Image hyperlink is not working without https://

### ISSUE THREAD

**Issue by naganand123** [xdan/jodit#821]
**Jodit Version:**  3.4.xxxxx

**Browser:**  
**OS:**  
**Is React App:**  

**Code**

```js
// if I add hyperlink with out https or http it not working
link is appeinding to the current url like this 'https://xfqokc.csb.app/www.google.com'.
How to append https to the url if URL not having the https
```
![image](https://user-images.githubusercontent.com/38246490/162388980-4ff39a55-fe1f-4ae4-85e9-e8d0f7778281.png)

**Expected behavior:**
hyperlink should work if user missed to eneter https
**Actual behavior:**
hyperlink is not working if user missed to enter https

**Comment by xdan** [comment]
it is not always possible to guess whether this is a local image image.jpg or a site like that https://image.com. Added a little heuristic.
