### ISSUE TITLE
How to resize image with the handle bars without fixed aspect ratio

### ISSUE THREAD

**Issue by mauserzjeh** [xdan/jodit#839]
Hi!

I would like to know if there is a way to resize the images with the handle bars in the editor to another size/aspect ratio. Only the corners of the handle bars seem to be draggable and this way the aspect ratio stays the same. Is there a way or option to be able to drag the sides of the handle bars thus changing the size and aspect ratio of an image with this method?

Thanks!

**Comment by xdan** [comment]
@mauserzjeh Added functionality when pressing the Alt button, you can resize without taking into account the ratio
