### ISSUE TITLE
Types are not working

### ISSUE THREAD

**Issue by Zwergenpunk** [xdan/jodit#84]
**Jodit Version:**  3.1.10

I installed Jodit with the installed version in my typescript project.

**Expected behavior:**

No compilation problems

**Actual behavior:**

![image](https://user-images.githubusercontent.com/7661170/44717861-8ebc1880-aabe-11e8-950b-852f20c55b96.png)

The problem is generated because of the custom.d.ts file in the root directory of the project. The file is not correctly referenced or something.

Thank you

**Comment by Oranji-Aka** [comment]
yup got the same problem too, been trying to figure out a way to fix it.

**Comment by Zwergenpunk** [comment]
You can use thre previous version ;)

**Comment by Zwergenpunk** [comment]
Any plans to solve that issue?

**Comment by mykle90** [comment]
Anyone got a workaround or are there plans to fix this issue?

**Comment by xdan** [comment]
In 3.2.19 i think fixed
