### ISSUE TITLE
Change the Font Size of the headings, with numbered  bullets. Numbered Bullets are not changed

### ISSUE THREAD

**Issue by marygrace1235** [xdan/jodit#854]
Copy  Paste the content from word with numbered bullets and text. Change the Font Size of the headings, with numbered  bullets
![image](https://user-images.githubusercontent.com/90672801/173795715-315a682e-8c3e-43b6-8931-ddc6ca7a1637.png)

**Expected behavior:**
Changes should affect both the text and numbered bullets
![image](https://user-images.githubusercontent.com/90672801/173797979-042cf96b-175b-4b82-ab9e-e949ed4124da.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/90672801/173797522-3f638ef3-1640-4e37-b9df-143bbd5fe13a.png)
Changes are not affecting the numbered bullets

**Comment by xdan** [comment]
You should use special styles https://xdsoft.net/jodit/pro/docs/plugin/paste-from-word
