### ISSUE TITLE
Change editor defaults

### ISSUE THREAD

**Issue by NGumby** [xdan/jodit#86]
I tried to ask on StackOverflow, but the tag Jodit doesn't exist.

Is there anyway to change the defaults for the editor, for example, the text color, the text aligment, etc.  Is it just using the current css styles?

Also is there a way to specify which colors should be included in the color picker?

**Comment by Ross-Blakeney** [comment]
https://xdsoft.net/jodit/play.html?currentTab=Themes

It seems to be pure css

**Comment by kakadais** [comment]
I still don't know why I don't understand how to control Jodit, I could have controled some style without pur css something like this

constr editor = new Jodit('#editor');
editor.editorDocument.body.style.color = "black"

In the editor, there's some method to control it, but coudln't figure it on the document exactly.

**Comment by kakadais** [comment]
I don't think this is a best approach, but it works on me and easy.

const editor = new Jodit();
editor.workplace.style.cssText = 'width: auto; height: auto; min-height: 500px; color: black';

**Comment by xdan** [comment]
Better use 'editor'
```js
const jodit = new Jodit();
jodit.editor.style.cssText = 'width: auto; height: auto; min-height: 500px; color: black';
```

**Comment by xdan** [comment]
or use https://xdsoft.net/jodit/doc/options/style/
