### ISSUE TITLE
Using BR tag as enter element results reset of cursor while typing in newlines.

### ISSUE THREAD

**Issue by ferrykranenburgcw** [xdan/jodit#860]
**Jodit Version:**  3.18.4

**Browser:**  Chrome
**OS:**  Windows
**Is React App:**  False

**Expected behavior:**

When we use `BR` as our enter element then after a few new lines, starting to type makes our cursor jump the first character of the newline. So if my sentence starts with `Test` then it would result in `estT` because after the first input the cursor is being reset. The problem is easy to reproduce on your playground by setting `BR` as the enter element. I have included a video where I show the difference.

**Actual behavior:**

You can see a video of this behaviour here: https://vimeo.com/725984938/aa84b59caf

**Comment by ferrykranenburgcw** [comment]
Downgrading to Jodit version `3.17.1` fixes this for now.

**Comment by GonzaloManoukian** [comment]
Hii! This keeps happening to me using "jodit-pro-react ^1.3.39" (current to date) :(

**Comment by SharePointPro** [comment]
Just confirming  this bug still exists, even i the latest version.
I had to go back to 3.17.1

To replicate:
```

 joditConfig = {
                beautifyHTML: false,
                width: "100%",
                enter: "br",
                enterBlock: "div",
                tabIndex: tabIndex,
                useSplitMode: false,
                buttonsXS: [],
            };

var editor = jodit.Jodit.make("#" + id, joditConfig);

```

Then press Enter on a new line and start typing. every new line besides the first will reset the cursor to position 1.
