### ISSUE TITLE
 copy and paste the content from word to Jodit Pro, it doesn’t copy all the points. Jodit Free version retains all the formatting

### ISSUE THREAD

**Issue by marygrace1235** [xdan/jodit#861]
Copy-paste the word document with the numbered bullets, it doesn't copy all the text from word in Jodit Pro version,but in Jodit Free version it copy all the points.

Please find the attached Document for the copy-paste issue https://docs.google.com/document/d/1Z4CdBbR1C6IHdK3TsNslhB0xkAiRLNsx4YF7zVWdXfw/edit?usp=sharing

Please find the attached  video for the reference
https://drive.google.com/file/d/1U34whZ-czYrMoPAAIqfgrPNUCQ0R0llN/view?usp=sharing

**Expected behavior:**

Copy-paste the word document with the numbered bullets, it should copy-paste all the content and bullet points same as jodit Free  version
**Actual behavior:**

Copy-paste the word document with the numbered bullets, it doesn't copy all the text from word like jodit Free version

**Comment by xdan** [comment]
Fixed now

**Comment by Rajat-eks** [comment]
i  am unable to use images when i copy text and images from word or mail.
