### ISSUE TITLE
Content panel becomes unresponsive when pressing backspace with no content

### ISSUE THREAD

**Issue by Ross-Blakeney** [xdan/jodit#87]
**Jodit Version:**  3.2.10

This can be seen on the demo at:
https://xdsoft.net/jodit/play.html

repro:

1. Delete all content of the editor

2. Once there is no content, hit backspace or delete again

**Expected behavior:**

User can continue to use the control and add content.

**Actual behavior:**

Editor content panel becomes unresponsive until refresh.

**Comment by CAgorski** [comment]
Also running into this issue

**Comment by mdevDE** [comment]
Same problem here.

MacOs Safari 11.1.2, Chrome 68.0.3440.106
