### ISSUE TITLE
activeButtonsInReadOnly: ['source', 'preview'] is not working.

### ISSUE THREAD

**Issue by patiencendiligence** [xdan/jodit#878]
### Discussed in https://github.com/xdan/jodit/discussions/877

<div type='discussions-op-text'>

<sup>Originally posted by **patiencendiligence** August 16, 2022</sup>
Hello, Somebody help me. plz.
(My jodit is the latest version. - free)

I want to the buttons such as 'source', 'preview' are working in readonly state.
So, I set like this my jodit editor config.
```
config: {
  readonly: true,
  activeButtonsInReadOnly: ['source', 'preview'],
  ...,
}
```

Then, The 'source' button works.
But.. The preview button looks like working - is active - . Actually, It is not working.
When I click the preview button, it is nothing happens. (not visible preview dialog..)

How can I make that preview button work in readonly state?
Thank you in advance.

</div>

**Comment by xdan** [comment]
In readonly mode, any commands other than select-all are prohibited. The preview button works by registering the preview command and essentially just calls `editor.execCommand('preview')`
I will add in the new version a white list of commands that can be called in readonly

**Comment by xdan** [comment]
Now, you can repeat all preview's functionality in the button
https://codesandbox.io/s/jodit-vanila-6dxexm?file=/src/index.js

**Comment by patiencendiligence** [comment]
@xdan Thank you! 👍

**Comment by xdan** [comment]
Added options
