### ISSUE TITLE
Issues with type definitions

### ISSUE THREAD

**Issue by julianpoemp** [xdan/jodit#887]
### Background

I would like to use jodit in one of my angular projects. At first I tried [jodit-angular](https://github.com/jodit/jodit-angular) but it seems it's based on an old version of angular (8.x) and an old version of jodit. So I consider either contributing to that project or creating an own angular component with jodit.

That's why I had a look on the v12 branch and I'm curious why Jodit is imported via "require(...)" instead of import like it should be done in those days ([see here](https://github.com/jodit/jodit-angular/blob/master/projects/jodit-angular-lib/src/lib/jodit-angular.component.ts)).

Because jodit does have Typescript definitions I wonder why it isn't used. That's why I created a [test project here](https://github.com/julianpoemp/jodit-angular-test).

### Questions

1. What is the way to properly import Jodit in Typescript project? The way I did it should work, but didn't ([see m here](https://github.com/julianpoemp/jodit-angular-test/blob/a44e3d09ea627b50ecb79e7ad10f901775a6b67e/src/app/app.component.ts#L17))

I get the following error:

````
Error: node_modules/jodit/types/core/dom/lazy-walker.d.ts:7:26 - error TS2307: Cannot find module 'jodit/core/event-emitter/eventify' or its corresponding type declarations.

7 import { Eventify } from 'jodit/core/event-emitter/eventify';
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/jodit/types/core/ui/button/button/button.d.ts:8:27 - error TS2307: Cannot find module 'jodit/core/ui/element' or its corresponding type declarations.

8 import { UIElement } from 'jodit/core/ui/element';
                            ~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/jodit/types/core/ui/button/button/button.d.ts:10:22 - error TS2420: Class 'UIButton' incorrectly implements interface 'IUIButton'.
  Type 'UIButton' is missing the following properties from type 'IUIButton': jodit, j, setParentView, i18n, and 31 more.

10 export declare class UIButton extends UIElement implements IUIButton {
                        ~~~~~~~~


Error: node_modules/jodit/types/core/ui/element.d.ts:7:31 - error TS2307: Cannot find module 'jodit/core/component' or its corresponding type declarations.

7 import { ViewComponent } from 'jodit/core/component';
                                ~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/jodit/types/core/ui/element.d.ts:8:28 - error TS2307: Cannot find module 'jodit/core/traits' or its corresponding type declarations.

8 import { Elms, Mods } from 'jodit/core/traits';
                             ~~~~~~~~~~~~~~~~~~~
````
and a lot more.

2. How do you create type definitions for typescript? Am I correct that you create a part of it manually and another part of it using `tsc`? ([see here](https://github.com/xdan/jodit/blob/e6ff50559380e9a36ccd96ec2d2a6201c61bc4d4/package.json#L34))
3. What do you think about using [rollup.js](https://rollupjs.org/guide/en/)? It can make the creation of TS and JS libraries very easy and offers creating packages with high compatibility. [Here is a demo](https://github.com/julianpoemp/rolltsup-sample) I created some time ago.

**Comment by xdan** [comment]
You cannot use Jodit types in your runtime code.
You can include the original TypeScript code:
```typescript
import { UIElement } from 'jodit/src/core/ui/element';
console.log(UIElement);
```
Or use runtime
```typescript
import type { UIElement as IUIElement } from 'jodit/core/ui/element';
import {Jodit} from "jodit"
const UIElement: IUIElement = Jodit.modules.UIElement;
console.log(UIElement);
```

**Comment by julianpoemp** [comment]
Issue is solved with the latest version. Thank you!

**Comment by jeffschulzusc** [comment]
having hard time with Jodit in angular 15 project:

`Error: node_modules/jodit/types/plugins/enter/interface.d.ts:6:16 - error TS2436: Ambient module declaration cannot specify relative module name.`
`6 declare module '../../types/events' {`

project is here:
https://github.com/jeffschulzusc/jodit-angular/tree/v15

anyone know how i can resolve this build error ?
thanks much

**Comment by jeffschulzusc** [comment]
resolved:

To avoid TS2436 error on ng build, must set
"skipLibCheck": true 
in tsconfig.json.

Could the Jodit team build the npm package with stricter typing and not use relative paths ?

thanks for the awesome editor :)
