### ISSUE TITLE
OEM version buying process 

### ISSUE THREAD

**Issue by loridae** [xdan/jodit#889]
As a company, I want to receive an invoice for payment, it will help me with loans.

Also, I can't receive any answers to my question. Any response to chat messages, email also doesn't work

"Your message couldn't be delivered to support@xdsoft.net. Their inbox is full, or it's getting too much mail right now."

How I can contact the owner to discuss questions that I am interested in?

**Comment by xdan** [comment]
Hi, did you make issue in private issue tracker?

**Comment by loridae** [comment]
I have created and I hope it will help.

Number dd74734a-795c-4701-bcdf-3c6cc400095d

**Comment by xdan** [comment]
Answered in ticket. I close this one. Further communication under an OEM license only in a private tracker
