### ISSUE TITLE
Toolbar not loading correctly in desktop view

### ISSUE THREAD

**Issue by Oranji-Aka** [xdan/jodit#89]
**Jodit Version:**  3.2.6

**Expected behavior:**
Load toolbar in full width
**Actual [behavior:**]
Load in mobile view.

Basicly i have a component that contain a jodit editor, it will be either modal or non-modal.
It seems when it get loaded the first time in a modal view it load in Adaptative.
![microsoftteams-image](https://user-images.githubusercontent.com/8930020/45498160-7e0ad400-b747-11e8-930f-e51513bb63f2.png)

If i switch tab it will load the toolbar the way i want it.

The way i found to counter the problem is by setting the toolbarAdaptive to false.

**Comment by xdan** [comment]
Disable mobile plugin
```javascript
var editor = new Jodit('#editor', {
disablePlugins: ['mobile']
})
```
