### ISSUE TITLE
Changing the language has no effect

### ISSUE THREAD

**Issue by edlinger-ma** [xdan/jodit#905]
**Jodit Version:**  3.22.1

**Browser:**  Chrome
**OS:** Windows
**Is React App:** True

**Reproducible** on the playground page: https://xdsoft.net/jodit/play.html

**Expected behavior:**  
When I change the language, the aria lables and generally the text in the editor (e.g. when uploading 'Drop Image or Click') are displayed in the respective language.

**Actual behavior:**  
Changing the language has no effect. The text is always in English.

**Comment by xdan** [comment]
May be you use eng version of build? 
https://cdnjs.cloudflare.com/ajax/libs/jodit/3.24.1/jodit.es2018.en.min.js
but you need full version
https://cdnjs.cloudflare.com/ajax/libs/jodit/3.24.1/jodit.es2018.min.js

Playground just use only eng version

**Comment by edlinger-ma** [comment]
Thank you ! 
Something was wrong with the build
