### ISSUE TITLE
Not possible to remove superscript/subscript

### ISSUE THREAD

**Issue by prp1** [xdan/jodit#91]
**Jodit Version:**  3.2.10

When I select text that is superscripted or subscripted, the corresponding button in toolbar does not get highlighted. If I wan't to remove superscript or subscript, it is not possible by clicking corresponding button in toolbar.

![image](https://user-images.githubusercontent.com/19374323/45876163-89db4380-bda2-11e8-8aed-f63190a28269.png)

**Comment by agatamagier** [comment]
Hi, thanks for this awesom tool. I have a simmilar problem as above. I'm not able to deactivate superscript/subscript button, it only works on double click. Is it how it's supposed to work?
I doesn't get the arria-pressed atrribute set to true.
Many thanks
