### ISSUE TITLE
How I can open popup via JS?

### ISSUE THREAD

**Issue by sammael1106** [xdan/jodit#94]
I need emulate click on toolbar button with JS to open it's popup

I have tried trigger it with jQuery:
`
$('.jodit_toolbar_btn.jodit_toolbar_btn-image a').trigger('mouseDown')
$('.jodit_toolbar_btn.jodit_toolbar_btn-image span').trigger('mouseDown')
$('.jodit_toolbar_btn.jodit_toolbar_btn-image a').trigger('click')
$('.jodit_toolbar_btn.jodit_toolbar_btn-image span').trigger('click')
`
no reation

Also i tried to call control's popup
`
editor.toolbar.__buttons[25].control.popup(editor.toolbar.__buttons[25].jodit)
`
it only returns HTML-element of inner form

And there is a method in documentation, but I don't understand how to use it
[https://xdsoft.net/jodit/doc/methods/ToolbarPopup-doOpen/](https://xdsoft.net/jodit/doc/methods/ToolbarPopup-doOpen/)

**Comment by xdan** [comment]
Added "click-{buttonName}" events

Now you can click on some toolbar button use same code
```js
var editor = new Jodit('#editor');
editor.events.fire('click-image-btn');
```

**Comment by xdan** [comment]
And this code should work
```js
$('.jodit_toolbar_btn.jodit_toolbar_btn-image').trigger('mousedown') 
```

**Comment by ilyauts** [comment]
Does this functionality still work, I'm having issues replicating this under the newer versions of Jodit
