### ISSUE TITLE
joomla fatal error missed helperfile

### ISSUE THREAD

**Issue by PierreCorell** [xdan/jodit#95]
Hello, 

nice extension. As I install the current release on a local environment, I got a fatal error after install at the url administrator/index.php?option=com_jodit

```ts
Fatal error: require_once(): require_once(/var/www/html/administrator/components/com_jodit/helpers/jodit.php): failed to open stream: No such file or directory in /var/www/html/administrator/components/com_jodit/jodit.php on line 24

```
**Jodit Version:**  3.1.11

**Actual behavior:**

If I comment the line out, the next missing file comes up with a fatal error at helpers/JoditApplication.php
This package is definitively broken. 

Thanks in advance,
Pierre.

**Comment by xdan** [comment]
Please try latest version https://github.com/jodit/jodit-joomla/raw/master/tmp/pkg_jodit.zip
