### ISSUE TITLE
No disabled state

### ISSUE THREAD

**Issue by Ross-Blakeney** [xdan/jodit#97]
Jodit Version:**  3.1.xxxxx

**Expected behavior:**
Some method of setting a disabled state on the entire editor.

**Actual behavior:**
Can't disable the entire wysiwyg

**Comment by xdan** [comment]
Now you can use setDisabled method or disabled option
```html
<textarea id="editor" disabled/>
```
```javascript
var editor = new Jodit('#editor');
console.log(editor.getDisabled()); // true
```
```javascript
var editor = new Jodit('#editor', {disabled: true});
console.log(editor.getDisabled()); // true
```

**Comment by Ross-Blakeney** [comment]
Thanks so much xdan! Not sure how I missed this. Keep up the good work. :)
