### ISSUE TITLE
Error when using in angular 13

### ISSUE THREAD

**Issue by Velmoren** [xdan/jodit#977]
Use packages:

     "jodit": "~3.23.3"
     
     &&
     
    "@angular/animations": "~13.3.11",
    "@angular/common": "~13.3.11",
    "@angular/compiler": "~13.3.11",
    "@angular/core": "^13.3.11",
    "@angular/forms": "~13.3.11",
    "@angular/platform-browser": "~13.3.11",
    "@angular/platform-browser-dynamic": "~13.3.11",
    "@angular/router": "~13.3.11"
    
    &&
    
    "typescript": "~4.6.4"
    
    But i have error
    
```
Error: node_modules/jodit/types/plugins/search/interface.d.ts:6:16 - error TS2436: Ambient module declaration cannot specify relative module name.

6 declare module '../../types/events' {
                 ~~~~~~~~~~~~~~~~~~~~
Error: node_modules/jodit/types/plugins/search/interface.d.ts:28:16 - error TS2436: Ambient module declaration cannot specify relative module name.

28 declare module '../../types/jodit' {
                  ~~~~~~~~~~~~~~~~~~~
Error: node_modules/jodit/types/types/types.d.ts:280:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'font' must be of type 'HTMLFontElement', but here has type 'HTMLElement'.

280   font: HTMLElement;
      ~~~~
  node_modules/typescript/lib/lib.dom.d.ts:17141:5
    17141     "font": HTMLFontElement;
              ~~~~~~
    'font' was also declared here.

× Failed to compile.
```

**Comment by Velmoren** [comment]
The error appears immediately after adding the line
```
import * as EditorModule from 'jodit'

or

import { Jodit } from 'jodit'
```

**Comment by MrElectroNick** [comment]
Hi, if you're trying to use Jodit directly and w/o jodit-angular wrapper. Try making import that way:
```typescript
declare const require: any;
const EditorModule: any = require('jodit');
```
This is how jodit is imported into jodit-angular wrapper - this should work at least for Angular 13 and 14 - not sure about 15 and 16
Please try ;-)

**Comment by Velmoren** [comment]
> 

Yes, it works great, thank you! If I may have another question.

If using jodit-angular package how to implement two things:
1) ~~It is necessary to scatter two groups of buttons in the toolbar along the edges. What selector to use?~~
2) ~~Is there a method for inserting content at the cursor locations and how to do it correctly? How to get a Jodit instance from a component?~~
