### ISSUE TITLE
how to avoid the user to press enter?

### ISSUE THREAD

**Issue by Agus-Pinto** [xdan/jodit#982]
**Jodit Version:**  3.4.xxxxx

**Browser:**   FF
**OS:**   Linux
**Is React App:**   True

**Code**

```js
// This is the configuration: 
  const configTitle = useMemo(() => ({
    placeholder: 'Title...',
    toolbarAdaptive: false,
    allowResizeY: false,
    allowResizeX: false,
    buttons: "font,fontsize,bold,italic",
    height: '12vh',
    readonly: false,
    minHeight: '5vh',
    width: '73vw',
    showCharsCounter: false,
    showWordsCounter: false,
    showXPathInStatusbar: false,
    limitChars: 30,
    limitWords: 10,
    style: { overflow: 'hidden', backgroundColor: '#06386d', color: 'white' },
  }), []);

//this is how im using the editor: 
<JoditEditor ref={titleRef} config={configTitle} className='document-render-textarea-title' onBlur={handleBlur} onChange={handleTitleChange} value={title} />


```

**Expected behavior:**
i want to use the editor as a title box, but i want the user not to be able to press enter, so the editor would have only one line of text.

**Actual behavior:**
I didn't find any property that disables multi line, i created an event in order to stop the enter using ```event.stopPropagation()``` but it didn't work as expected.

**Comment by julianpoemp** [comment]
did you try this

```
event.preventDefault();
event.stopPropagation();
```
in a handler for the onKeyDown event if enter key was pressed?

**Comment by Agus-Pinto** [comment]
> did you try this
> 
> ```
> event.preventDefault();
> event.stopPropagation();
> ```
> 
> in a handler for the onKeyDown event if enter key was pressed?

@julianpoemp i did, i was able to catch the event, but it doesn't stop it.

**Comment by julianpoemp** [comment]
@Agus-Pinto I tested it and it seems that an event has to be set to off before preventing defaults. See this example here

https://stackblitz.com/edit/web-platform-mhr5e5?file=index.html

I don't use React so I cant provide an React example.

**Comment by xdan** [comment]
You can just return false in beforeEnter handler
```js
const configTitle = useMemo(() => ({
   // ...
   events: {
	beforeEnter() {return false }
   }
}), []);
```

**Comment by Agus-Pinto** [comment]
Thanks!! @xdan, it's just what i need
