### ISSUE TITLE
v3 & v4: Ambient module declaration cannot specify relative module name.

### ISSUE THREAD

**Issue by kzimny** [xdan/jodit#984]
**Jodit Version:**  3.24.9 & 4.0.0-beta-50

**Browser:**  Chrome/IE/Safary/FF 
**OS:**  Windows
**Is Angular App:**  True

**Code**

```js
declare module '../../types/events' {
    interface IEventEmitter {
        /**
         * Emitted every time after the plugins have been initialized
         * or a deferred plugin has been loaded and also initialized
         */
        on(event: 'updatePlugins', callback: () => void): this;
    }
}
```

**Expected behavior:**
```js
declare module 'some-module-name' {
    interface IEventEmitter {
        /**
         * Emitted every time after the plugins have been initialized
         * or a deferred plugin has been loaded and also initialized
         */
        on(event: 'updatePlugins', callback: () => void): this;
    }
}
```

**Actual behavior:**
error in Angular project:
```
node_modules/jodit/types/core/plugin/interface.d.ts
node_modules/jodit/types/core/selection/interface.d.ts
node_modules/jodit/types/plugins/bold/interface.d.ts
node_modules/jodit/types/plugins/enter/interface.d.ts
node_modules/jodit/types/plugins/fullsize/config.d.ts
node_modules/jodit/types/plugins/search/interface.d.ts
node_modules/jodit/types/plugins/search/interface.d.ts
```
![image](https://github.com/xdan/jodit/assets/12007674/835eea2f-6cb1-4f17-b29e-863e612b9f37)

@xdan : thank you for your excellent work. Jodit is the best editor I have ever seen. After installation of jodit package and compilation of angular project errors "Ambient module declaration cannot specify relative module name." occurs. When I add ```skipLibChecks: true``` errors goes away, but I prefere to not use this option. Could you please rename the module declarations?

**Comment by xdan** [comment]
Hi, fixed in beta

**Comment by kzimny** [comment]
You are the best! Thank you.

**Comment by wanting615** [comment]
> Hi, fixed in beta

hi. Can you fix it in v3? thanks very much.
