### ISSUE TITLE
Why are the beta packages of v4 not tagged with beta in npm?

### ISSUE THREAD

**Issue by julianpoemp** [xdan/jodit#985]
Is it intentional that the beta versions of v4 were not tagged with "beta" in npm?

````
npm publish --tag beta
````

Actually if you install jodit using `npm install`it automatically installs the latest beta package. Is that intended? 

If the beta packages were tagged with `beta` npm install would install the latest v3 package. I think it would better for people to install the v3 by default and v4 beta if they install it using `npm install jodit@beta` because v3 is a stable version.

**Comment by xdan** [comment]
Unfortunately I didn't know that, sorry

**Comment by julianpoemp** [comment]
No problem :)
