### ISSUE TITLE
Buttons are not all displaying event though there is room, most are in the button overflow dialog

### ISSUE THREAD

**Issue by natilivni** [xdan/jodit#99]
**Jodit Version:** 3.2.21

**Code**

```js
  var jodit = new Jodit(element, {
      enter: 'DIV',
      removeButtons: 'fullsize',
      allowResizeX: true,
      width: 718,
      toolbarButtonSize: 'small'
    });
```

**Expected behavior:**
All buttons appear on the toolbar

**Actual behavior:**
Only some buttons appear on the toolbar

![jodit_editor](https://user-images.githubusercontent.com/10357945/48352175-c9ccf180-e694-11e8-8af8-19167219f508.png)

**Comment by xdan** [comment]
Disable adaptive https://xdsoft.net/jodit/play.html?toolbarAdaptive=false&currentTab=Buttons
