### ISSUE TITLE
how to remove following empty <p><span>&nbsp;</span></p> 

### ISSUE THREAD

**Issue by meltingflowers** [xdan/jodit#995]
**Jodit Version:**  3.4.xxxxx

**Browser:**  
Html PHP
here is original text which replace by following 
```html
<p><span>&nbsp;</span></p> 
<p class="MsoNormal" style="margin: 0px 0px 11px; line-height: 107%; font-size: 15px; font-family: Calibri, sans-serif;"><span style="font-size: 16px; line-height: 107%;">&nbsp;</span></p>
```
**Code**

cleanHTML: { 
          cleanOnPaste: true,
          fillEmptyParagraph: false, // Disable filling empty paragraphs
          removeEmptyElements: false, // Disable removing empty elements
          replaceNBSP: true, // Disable replacing &nbsp; with spaces
          replaceEmptyTags: false // Disable replacing empty tags with their content
        },
```

**Expected behavior:**

**Actual behavior:**

**Comment by xdan** [comment]
Sorry, I will close this issue. Please fix everything properly, i don't understand what is the problem

**Comment by savelifeme** [comment]
@meltingflowers 你解决了该情况了吗？

**Comment by rylwl** [comment]
@savelifeme @meltingflowers 
I use these config and find it may be right.
```
      cleanHTML: {
        fillEmptyParagraph: false
      },
      wrapNodes:{
        emptyBlockAfterInit: false
      }
```
